### ISSUE TITLE
Calling halt twice in a pipe_through causes a ResponseAlreadySent error.

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#1146]
The following router causes a ResponseAlreadySent error when it calls the `stop` function the second time. Obviously in a real application you probably wouldn't call the same function twice, but I discovered it when calling a plug to authenticate a user and then one to authorize the user in the same pipe_through call.

```elixir
defmodule PlugHalt.Router do
  use PlugHalt.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
  end

  pipeline :halt do
    plug :stop
  end

  pipeline :halt_again do
    plug :stop
  end

  scope "/", PlugHalt do
    pipe_through [:halt, :halt_again, :browser] # Use the default browser stack

    get "/", PageController, :index
  end

  defp stop(conn, _opts) do
    conn |> send_resp(200, "This errors the second time") |> halt
  end
end
```

The error is:

```
[error] #PID<0.331.0> running PlugHalt.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Plug.Conn.AlreadySentError) the response was already sent
        (plug) lib/plug/conn.ex:428: Plug.Conn.resp/3
        (plug) lib/plug/conn.ex:415: Plug.Conn.send_resp/3
        (plug_halt) web/router.ex:28: PlugHalt.Router.stop/2
        (plug_halt) web/router.ex:12: PlugHalt.Router.halt_again/2
        (plug_halt) web/router.ex:2: PlugHalt.Router.match/4
        (plug_halt) web/router.ex:1: PlugHalt.Router.do_call/2
        (plug_halt) lib/plug_halt/endpoint.ex:1: PlugHalt.Endpoint.phoenix_pipeline/1
        (plug_halt) lib/plug/debugger.ex:90: PlugHalt.Endpoint."call (overridable 3)"/2
        (plug_halt) lib/phoenix/endpoint/render_errors.ex:34: PlugHalt.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by Gazler** [comment]
Here is an example repo if you want to check it locally: https://github.com/Gazler/phoenix-plug-halt
