### ISSUE TITLE
mix run fails - upgrade to elixir 1.1

### ISSUE THREAD

**Issue by erlanger** [phoenixframework/phoenix#1237]
`mix run` now fails with elixir 1.1 - of course it is because of the changes in Access, mix needs to be updated.
```
$ mix run
** (UndefinedFunctionError) undefined function: Access.List.get/2 (module Access.List is not available)
    Access.List.get([app: :bitbox, version: "0.0.1", elixir: "~> 1.1", deps: [], escript: [main_module: BitboxCli, emu_args: "+t 3048576"], aliases: [c: "compile", es: "escript.build"], build_per_environment: true, build_embedded: false, default_task: "run", deps_path: "deps", elixirc_paths: ["lib"], erlc_paths: ["src"], erlc_include_path: "include", erlc_options: [:debug_info], lockfile: "mix.lock", preferred_cli_env: [], start_permanent: false], :apps_path)
    (mix) lib/mix/project.ex:171: Mix.Project.umbrella?/1
    (mix) lib/mix/tasks/app.start.ex:78: Mix.Tasks.App.Start.start/2
    (mix) lib/mix/tasks/app.start.ex:68: Mix.Tasks.App.Start.run/1
    (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

**Comment by chrismccord** [comment]
As a sanity check can you `rm -rf _build` and retry? Everything is fine on my end on 1.1, so let's start there.

**Comment by dmarkow** [comment]
I had the same issue this morning, `rm -rf _build` fixed it. Thanks!

**Comment by zztczcx** [comment]
Thanks for same issue

**Comment by chrislaskey** [comment]
Thanks, cleaning out `_build` worked for me too. Appreciate it!
