### ISSUE TITLE
Upgrade path for 1.0.3?

### ISSUE THREAD

**Issue by stavro** [phoenixframework/phoenix#1243]
It appears as though there might need to be code changes added to the CHANGELOG.md to properly upgrade to 1.0.3.  After upgrading to 1.0.3 I get `(KeyError) key :heartbeat not found in` errors in my output:

```
[error] Ranch protocol #PID<0.359.0> (:cowboy_protocol) of listener ASDF.Endpoint.HTTP terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (KeyError) key :heartbeat not found in: [serializer: Phoenix.Transports.WebSocketSerializer, timeout: :infinity, transport_log: false]
            (elixir) lib/keyword.ex:165: Keyword.fetch!/2
            (phoenix) lib/phoenix/transports/websocket.ex:99: Phoenix.Transports.WebSocket.ws_init/1
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:59: Phoenix.Endpoint.CowboyWebSocket.websocket_init/3
            (cowboy) src/cowboy_websocket.erl:131: :cowboy_websocket.handler_init/3
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:36: Phoenix.Endpoint.CowboyWebSocket.resume/3
            (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by stavro** [comment]
Hmmm.... It looks like I had to manually `rm -rf _build` and it works now.  Odd... but nevermind!
