### ISSUE TITLE
mix test fails with "argument error"

### ISSUE THREAD

**Issue by slashmili** [phoenixframework/phoenix#1299]
I'm getting `argument error` when I run `mix test` on newly created phoenix app
 
Versions that I'm using:

* phoenix: 1.0.3
* Elixir:  1.0.5
* Erlang/OTP 18
* Ecto 1.0.5
```
$ mix phoenix.new foobar
...
$ cd foobar
$ mix ecto.create
==> fs (compile)
Compiled src/sys/inotifywait_win32.erl
....
==> foobar
Compiled web/web.ex
Compiled lib/foobar.ex
Compiled web/channels/user_socket.ex
Compiled lib/foobar/repo.ex
Compiled web/views/error_view.ex
Compiled web/views/page_view.ex
Compiled web/router.ex
Compiled web/controllers/page_controller.ex
Compiled web/views/layout_view.ex
Compiled lib/foobar/endpoint.ex
Generated foobar app
The database for Foobar.Repo has been created.
```

When I run `mix test`

```
mix test
==> ranch (compile)
==> poolboy (compile)
==> decimal
Compiled lib/decimal.ex
...
==> foobar
Compiled lib/foobar.ex
Compiled web/channels/user_socket.ex
Compiled test/support/model_case.ex
Compiled test/support/conn_case.ex
Compiled test/support/channel_case.ex
Compiled web/web.ex
Compiled lib/foobar/repo.ex
Compiled web/views/error_view.ex
Compiled web/views/page_view.ex
Compiled web/controllers/page_controller.ex
Compiled web/router.ex
Compiled web/views/layout_view.ex
Compiled lib/foobar/endpoint.ex
Generated foobar app
** (ArgumentError) argument error
    :erlang.exit(nil, :normal)
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.stop/2
    (ecto) lib/mix/ecto.ex:75: Mix.Ecto.ensure_stopped/2
    test/test_helper.exs:4: (file)
    (elixir) lib/code.ex:307: Code.require_file/2
```

I checked the `test_helper.exs` and line 3 and 4 are 
```
3: Mix.Task.run "ecto.create", ["--quiet"]
4: Mix.Task.run "ecto.migrate", ["--quiet"]
```

FYI I tried running it in iex and I got the same error(which is not a surprise). However if I run the `mix ecto.migrate` it works:
```
bash-3.2$ dropdb foobar_test
bash-3.2$ MIX_ENV=test mix ecto.create
The database for Foobar.Repo has been created.
bash-3.2$ MIX_ENV=test mix ecto.migrate

18:56:47.485 [info]  Already up
```

I know that's kinda Ecto related but just to let you know all people that get the latest version of phoenix can not run the test.

**Comment by josevalim** [comment]
A bug in Ecto, I have fixed it and I will make a new release. :)
