### ISSUE TITLE
Assets not loading in new project

### ISSUE THREAD

**Issue by merongivian** [phoenixframework/phoenix#1306]
I seems that some css are not loading when creating a new phoenix project, i got this error in the console
```bash
[info] Running AppMachine.Endpoint with Cowboy on http://localhost:4000
module.js:338
    throw err;
          ^
Error: Cannot find module 'cp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Jose/projects/elixir/apps/app-machine/node_modules/brunch/node_modules/read-components/node_modules/component-builder/lib/builder.js:6:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by chrismccord** [comment]
This appears to be a node issue. As a sanity check, can you:

    $ rm -rf node_modules/
    $ npm install
    $ mix phoenix.server


and report back?

**Comment by merongivian** [comment]
@chrismccord yea that might be it, downloading packages from node is somehow blocked in the place i work, closing this, thanks for the help anyway

**Comment by bryansray** [comment]
@merongivian you might try disabling SSL. Sometimes that helps when you're at an office that has firewalls in place.

    nom config set strict-ssl false

**Comment by merongivian** [comment]
@bryansray thanks for the tip!, let me try that
