### ISSUE TITLE
Running `mix test` causes erlang error :timeout_value

### ISSUE THREAD

**Issue by green-arrow** [phoenixframework/phoenix#1321]
After generating a new phoenix application (1.0.3), running `mix test` with a valid DB configuration in `test.exs` fails with the following message:

```
** (stop) :timeout_value
    (elixir) lib/task.ex:270: Task.await/2
    (ecto) lib/ecto/adapters/connection.ex:40: Ecto.Adapters.Connection.after_connect/2
    (ecto) lib/ecto/adapters/sql/sandbox.ex:95: Ecto.Adapters.SQL.Sandbox.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
** (exit) exited in: GenServer.call(NavigatorElixir.Repo.Pool, {:query, :begin, &NavigatorElixir.Repo.log/1, [timeout: 5000]}, 5000)
    ** (EXIT) an exception was raised:
        ** (ErlangError) erlang error: :timeout_value
            (elixir) lib/task.ex:270: Task.await/2
            (ecto) lib/ecto/adapters/connection.ex:40: Ecto.Adapters.Connection.after_connect/2
            (ecto) lib/ecto/adapters/sql/sandbox.ex:95: Ecto.Adapters.SQL.Sandbox.handle_call/3
            (stdlib) gen_server.erl:629%
```

Manually setting the `timeout` option in `test.exs` resolves the issue.

**Comment by josevalim** [comment]
Can you include your mix.lock file?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
> Manually setting the timeout option in test.exs resolves the issue.

Also, which value have you set to timeout?

**Comment by josevalim** [comment]
FWIW, I just created a new app and everything worked fine™.

**Comment by green-arrow** [comment]
Sorry for the delay.

`mix.lock`
```
%{"base64url": {:hex, :base64url, "0.0.1"},
  "combine": {:hex, :combine, "0.5.3"},
  "cowboy": {:hex, :cowboy, "1.0.3"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "1.0.6"},
  "fs": {:hex, :fs, "0.9.2"},
  "guardian": {:hex, :guardian, "0.6.3"},
  "hackney": {:hex, :hackney, "1.3.2"},
  "idna": {:hex, :idna, "1.0.2"},
  "inflex": {:hex, :inflex, "1.5.0"},
  "ja_serializer": {:hex, :ja_serializer, "0.4.0"},
  "joken": {:hex, :joken, "0.15.0"},
  "jose": {:hex, :jose, "1.3.0"},
  "mix_test_watch": {:hex, :mix_test_watch, "0.2.4"},
  "phoenix": {:hex, :phoenix, "1.0.3"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "1.2.0"},
  "plug": {:hex, :plug, "1.0.2"},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.9.1"},
  "ranch": {:hex, :ranch, "1.1.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"},
  "timex": {:hex, :timex, "0.19.5"},
  "timex_ecto": {:hex, :timex_ecto, "0.5.0"},
  "tzdata": {:hex, :tzdata, "0.5.4"},
  "uuid": {:hex, :uuid, "1.0.1"}}
```

I have the timeout set manually to `5000`.

**Comment by josevalim** [comment]
Ok, so it is not a blank project but rather something happening in your code. You need to increase the timeout value on your code on whatever you are doing inside your repository after_connect callback.
