### ISSUE TITLE
Generating a JSON model errors

### ISSUE THREAD

**Issue by Lazarus404** [phoenixframework/phoenix#1445]
Running mix phoenix.gen.json generates an error:

```
== Compilation error on file web/controllers/my_controller.ex ==
** (CompileError) web/controllers/my_controller.ex:20: function my_path/3 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by chrismccord** [comment]
Please incle the exact command you tab and your router. Did you follow the output instructions to add a new route?

**Comment by josevalim** [comment]
Yes, it looks like you forgot to execute a instruction after running a generator.

**Comment by Lazarus404** [comment]
Sorry, yes, thats exactly what happened.
