### ISSUE TITLE
Generated Controller tests fail using ``mix phoenix.gen.json``

### ISSUE THREAD

**Issue by seenickcode** [phoenixframework/phoenix#1446]
Hello, I seem to be having trouble running the generated tests via:

````
mix phoenix.new testapp --database mysql
cd testapp
mix ecto.create
mix ecto.migrate
mix phoenix.gen.json User users name:string email:string
````

I then added the following to ``web/router.ex``

``resources "/users", UserController``

I then ran ``mix test`` and got this output:

````
  1) test does not show resource and instead throw error when id is nonexistent (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:26
     expected error to be sent as 404 status, but response sent 406 without error
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:531: Phoenix.ConnTest.assert_error_sent/2
       test/controllers/user_controller_test.exs:27



  2) test updates and renders chosen resource when data is valid (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:43
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:46



  3) test creates and renders resource when data is valid (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:32
     ** (RuntimeError) expected response with status 201, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:34



  4) test deletes chosen resource (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:56
     ** (RuntimeError) expected response with status 204, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       test/controllers/user_controller_test.exs:59



  5) test does not create resource and renders errors when data is invalid (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:38
     ** (RuntimeError) expected response with status 422, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:40



  6) test shows chosen resource (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:17
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:20



  7) test lists all entries on index (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:12
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:14



  8) test does not update chosen resource and renders errors when data is invalid (Testapp.UserControllerTest)
     test/controllers/user_controller_test.exs:50
     ** (RuntimeError) expected response with status 422, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:53


````

On the other hand, it seems that ``mix phoenix.gen.model`` works fine so maybe it's something with ``mix phoenix.gen.json``?

**Comment by josevalim** [comment]
Did you add it to your API pipeline as the generator instructions ask?

**Comment by seenickcode** [comment]
Turned out it I mistakenly put it in the default generated scope with ``pipe_through :browser`` rather than the default commented out ``pipe_through :api``.  Sorry for the false alarm!
