### ISSUE TITLE
phoenix.gen.json controller test failure

### ISSUE THREAD

**Issue by walkr** [phoenixframework/phoenix#1461]
Platform: OS X
Elixir: 1.2
Phoenix: 1.1

I've generated a new app via `mix phoenix.new` then I've created a new model like so:

```shell
$ mix phoenix.gen.json User users username:string age:integer
```

Model tests pass, but controller test for this resource fail. Any thoughts?

Here's the output:

```shell

  1) test does not show resource and instead throw error when id is nonexistent (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:25
     expected error to be sent as 404 status, but response sent 406 without error
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:531: Phoenix.ConnTest.assert_error_sent/2
       test/controllers/user_controller_test.exs:26



  2) test creates and renders resource when data is valid (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:31
     ** (RuntimeError) expected response with status 201, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:33



  3) test does not update chosen resource and renders errors when data is invalid (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:49
     ** (RuntimeError) expected response with status 422, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:52



  4) test shows chosen resource (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:17
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:20



  5) test lists all entries on index (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:12
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:14



  6) test updates and renders chosen resource when data is valid (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:42
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:45



  7) test deletes chosen resource (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:55
     ** (RuntimeError) expected response with status 204, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       test/controllers/user_controller_test.exs:58



  8) test does not create resource and renders errors when data is invalid (Myapp.UserControllerTest)
     test/controllers/user_controller_test.exs:37
     ** (RuntimeError) expected response with status 422, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:39



Finished in 0.4 seconds (0.3s on load, 0.08s on tests)
8 tests, 8 failures
```

**Comment by walkr** [comment]
Found the issue:
I added the `resources "/users", UserController, except: [:new, :edit]` under the wrong scope in routes.
