### ISSUE TITLE
npm issues

### ISSUE THREAD

**Issue by nbolt** [phoenixframework/phoenix#1496]
trying to set up a new phoenix app, get the following when running `npm install` for the first time:

```
npm http GET https://registry.npmjs.org/brunch
npm http GET https://registry.npmjs.org/clean-css-brunch
npm http GET https://registry.npmjs.org/uglify-js-brunch
npm http GET https://registry.npmjs.org/css-brunch
npm http GET https://registry.npmjs.org/javascript-brunch
npm http GET https://registry.npmjs.org/babel-brunch
npm http 304 https://registry.npmjs.org/brunch
npm http 304 https://registry.npmjs.org/babel-brunch
npm http 304 https://registry.npmjs.org/css-brunch
npm http 304 https://registry.npmjs.org/uglify-js-brunch
npm http 304 https://registry.npmjs.org/javascript-brunch
npm http 304 https://registry.npmjs.org/clean-css-brunch
npm http GET https://registry.npmjs.org/phoenix_html
npm http 404 https://registry.npmjs.org/phoenix_html
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-71-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/saiko/code/eatsimply-web
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http GET https://registry.npmjs.org/phoenix
npm http 304 https://registry.npmjs.org/phoenix
npm ERR! Error: No compatible version found: phoenix@'file:deps/phoenix'
npm ERR! Valid install targets:
npm ERR! ["0.1.1-dev"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-71-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/saiko/code/eatsimply-web
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/saiko/code/eatsimply-web/npm-debug.log
npm ERR! not ok code 0
```

**Comment by josevalim** [comment]
You need to update node and npm, those are quite old. :) As a reference, I am on npm v3.5.2 and node v5.3.0.
