### ISSUE TITLE
Answer from Channel with example from docs causes an error in handle_in/3

### ISSUE THREAD

**Issue by spscream** [phoenixframework/phoenix#1517]
I'm experimenting with phoenix channels and pointed bug with code or with documentation.

The following code example exists In documentation for phoenix version 1.1.4:
```elixir
def handle_in("create:post", attrs, socket) do
  changeset = Post.changeset(%Post{}, attrs)

  if changeset.valid? do
    Repo.insert!(changeset)
    {:reply, {:ok, changeset}, socket}
  else
    {:reply, {:error, changeset.errors}, socket}
  end
end
```

this isn't working, because now changeset.errors returns a List with errors, e.g.:
```elixir
[msg_id: "can't be blank"]
```
and causes RuntimeError:
```elixir
[error] GenServer #PID<0.377.0> terminating
** (RuntimeError) Channel replies from `handle_in/3` are expected to be one of:

    status :: atom
    {status :: atom, response :: map}

for example:

    {:reply, :ok, socket}
    {:reply, {:ok, %{}}, socket}
    {:stop, :shutdown, {:error, %{}}, socket}

got {:error, [msg_id: "can't be blank"]}

    (phoenix) lib/phoenix/channel/server.ex:311: Phoenix.Channel.Server.handle_reply/3
    (phoenix) lib/phoenix/channel/server.ex:254: Phoenix.Channel.Server.handle_result/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

but handle_in/3 expects reply in the following form:
```elixir
@type reply :: status :: atom | {status :: atom, response :: map}
```

**Comment by chrismccord** [comment]
Our docs need updated. You need to use your ChangsetView (or create it), then you can render the changeset with translated errors:

https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phoenix.gen.json/changeset_view.ex
