### ISSUE TITLE
undefined function Connection.start_link

### ISSUE THREAD

**Issue by slashmili** [phoenixframework/phoenix#1536]
I'm using Elixir 1.2 and phoenix 1.1.2. When I build release with exrm and use `Repo` I get `undefined function Connection.start_link/2` error. Adding `:connection` to application list solves the problem

The full stack trace:
```
iex(elide@127.0.0.1)2> Ecto.Migrator.run(Elide.Repo, mig_dir, :up, [all: true])
02:30:26.349 [error] GenServer #PID<0.254.0> terminating
** (UndefinedFunctionError) undefined function Connection.start_link/2 (module Connection is not available)
    Connection.start_link(Postgrex.Connection, [timeout: 5000, otp_app: :elide, repo: Elide.Repo, adapter: Ecto.Adapters.Postgres, username: "postgres", password: "postgres", database: "elide_prod", hostname: "postgresql.local", extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432])
    (ecto) lib/ecto/adapters/connection.ex:27: Ecto.Adapters.Connection.connect/2
    (ecto) lib/ecto/pools/poolboy/worker.ex:58: Ecto.Pools.Poolboy.Worker.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
It is a bug that was fixed in Postgrex. YOu have two options: update postgrex (and ecto) or add `:connection` to the list of applications in def application in your mix.exs file.

**Comment by slashmili** [comment]
Thanks!
