### ISSUE TITLE
Form select input fails with certain text values

### ISSUE THREAD

**Issue by amarsahinovic** [phoenixframework/phoenix#1569]
I'm trying to use select (also fails with multiple_select) to display a list of users but an exception is raised for values like "Šahinović".

Simple test case:
<%= select f, :test, ["Šahinović": 1] %>

### Environment

* Elixir version (elixir -v): 1.2.2
* Erlang version: 18.2.1
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): 5.6.0
* NPM version (npm -v): 3.7.3
* Operating system: Arch Linux 64bit

### Expected behavior

 Select box with correct text

### Actual behavior

**Hard-coded example from above:**
~~~
== Compilation error on file web/views/subscription_view.ex ==
** (ArgumentError) argument error
    :erlang.binary_to_atom("Å ahinoviÄ", :utf8)
    (elixir) src/elixir_parser.yrl:511: :elixir_parser.yeccpars2_91/7
    (elixir) /usr/lib/erlang/lib/parsetools-2.1.1/include/yeccpre.hrl:57: :elixir_parser.yeccpars0/5
    (eex) lib/eex/compiler.ex:34: EEx.Compiler.generate_buffer/4
    (eex) lib/eex/compiler.ex:41: EEx.Compiler.generate_buffer/4
    (phoenix) lib/phoenix/template.ex:321: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:154: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    web/views/subscription_view.ex:1: Multiverse.SubscriptionView (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
~~~

**When fetching data from the database and transforming it in the view I get this:**
~~~
[error] #PID<0.439.0> running Multiverse.Endpoint terminated
Server: 127.0.0.1:4000 (http)
Request: GET /subscriptions/1/edit
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.binary_to_atom("Šahinović", :utf8)
        (multiverse) web/views/subscription_view.ex:6: anonymous fn/1 in Multiverse.SubscriptionView.users_for_select/1
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (multiverse) web/views/subscription_view.ex:6: Multiverse.SubscriptionView.users_for_select/1
        (multiverse) web/templates/subscription/form.html.eex:10: anonymous fn/2 in Multiverse.SubscriptionView.form.html/1
        (phoenix_html) lib/phoenix_html/form.ex:235: Phoenix.HTML.Form.form_for/4
        (multiverse) web/templates/subscription/form.html.eex:1: Multiverse.SubscriptionView."form.html"/1
        (multiverse) web/templates/subscription/edit.html.eex:3: Multiverse.SubscriptionView."edit.html"/1
        (multiverse) web/templates/layout/app.html.eex:39: Multiverse.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (multiverse) web/controllers/subscription_controller.ex:1: Multiverse.SubscriptionController.action/2
        (multiverse) web/controllers/subscription_controller.ex:1: Multiverse.SubscriptionController.phoenix_controller_pipeline/2
        (multiverse) lib/phoenix/router.ex:261: Multiverse.Router.dispatch/2
        (multiverse) web/router.ex:1: Multiverse.Router.do_call/2
        (multiverse) lib/multiverse/endpoint.ex:1: Multiverse.Endpoint.phoenix_pipeline/1
        (multiverse) lib/plug/debugger.ex:93: Multiverse.Endpoint."call (overridable 3)"/2
        (multiverse) lib/phoenix/endpoint/render_errors.ex:34: Multiverse.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

~~~

**Function used in the view**
~~~
  def users_for_select(users) do
    users
    |> Enum.map(&["#{&1.last_name}": &1.id])
    |> List.flatten
  end
~~~

**Part of template displaying users**
~~~
  <div class="form-group">
    <%= label f, :user_id, "User", class: "control-label" %>
    <%= select f, :user_id, users_for_select(@users), class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>
~~~

**Comment by chrismccord** [comment]
the enumerable you are providing is using an atom key `["Šahinović": 1]` is equivalent to try to do `[{:"Šahinović", 1}]`, which is an invalid atom. Instead you can either do:

    [{"Šahinović", 1}]

or provide a map with string keys:

    %{"Šahinović" => 1}
