### ISSUE TITLE
Upgrading to phoenix_ecto 3.0-beta causes model controller tests to fail

### ISSUE THREAD

**Issue by walkr** [phoenixframework/phoenix#1582]
Hello,

I've upgraded to ` {:phoenix_ecto, "~> 3.0-beta.2"}`  and upon creating a new model with ` mix phoenix.gen.json User users name:string create:datetime username:string password:string` my tests fail

Could anyone provide some guidance regarding this?
### Environment

* Elixir version (elixir -v):
   Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
  Elixir 1.2.3

* Phoenix version (mix deps):

* postgrex 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (postgrex)
  ok
* ecto 2.0.0-beta.2 (Hex package) (mix)
  locked at 2.0.0-beta.2 (ecto)
  ok
* phoenix_ecto 3.0.0-beta.2 (Hex package) (mix)
  locked at 3.0.0-beta.2 (phoenix_ecto)
  ok

* Operating system: 
   OS X El Capitan 10.11.3

### Expected behavior
Test should pass.

### Actual behavior

Test fail

```shell
......

  1) test lists all entries on index (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:12
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:14



  2) test creates and renders resource when data is valid (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:33
     ** (RuntimeError) expected response with status 201, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:35



  3) test does not create resource and renders errors when data is invalid (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:39
     ** (RuntimeError) expected response with status 422, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:41



  4) test shows chosen resource (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:17
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:20



  5) test updates and renders chosen resource when data is valid (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:44
     ** (RuntimeError) expected response with status 200, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:47



  6) test deletes chosen resource (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:57
     ** (RuntimeError) expected response with status 204, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       test/controllers/user_controller_test.exs:60



  7) test does not update chosen resource and renders errors when data is invalid (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:51
     ** (RuntimeError) expected response with status 422, got: 406
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:328: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:374: Phoenix.ConnTest.json_response/2
       test/controllers/user_controller_test.exs:54



  8) test does not show resource and instead throw error when id is nonexistent (Tezt.UserControllerTest)
     test/controllers/user_controller_test.exs:27
     expected error to be sent as 404 status, but response sent 406 without error
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:531: Phoenix.ConnTest.assert_error_sent/2
       test/controllers/user_controller_test.exs:28



Finished in 0.5 seconds (0.3s on load, 0.1s on tests)
14 tests, 8 failures

Randomized with seed 523483
```

**Comment by josevalim** [comment]
It seems the errors are because you put the route in the wrong place. Did you put it under the API scope i n your router?

**Comment by walkr** [comment]
Yes. 😁 That was it. Thank you! 👍🏽
