### ISSUE TITLE
mix test error - (Protocol.UndefinedError) protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by reneklacan** [phoenixframework/phoenix#1593]
### Environment

* Elixir version (elixir -v): 1.2.3
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): v5.8.0
* NPM version (npm -v): 3.7.3
* Operating system: OS X 10.11.3

### Problem

I created new project with

```
mix phoenix.new hovno  --database mysql --no-brunch
cd hovno
mix ecto.create
```

I can see DB being created, server is working just fine too.

But when I run `mix test` I get

```
** (exit) exited in: GenServer.call(Hovno.Repo.Pool, {:query, :begin, &Hovno.Repo.log/1, [timeout: 15000]}, 5000)
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
            (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir) lib/enum.ex:116: Enumerable.reduce/3
            (elixir) lib/enum.ex:1486: Enum.reduce/3
            (mariaex) lib/mariaex/query.ex:135: DBConnection.Query.Mariaex.Query.decode/3
            (db_connection) lib/db_connection.ex:423: DBConnection.query/4
            (mariaex) lib/mariaex.ex:138: Mariaex.query/4
            (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
            (stdlib) timer.erl:197: :timer.tc/3
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (ecto) lib/ecto/adapters/sql.ex:407: Ecto.Adapters.SQL.test_transaction/5
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2

13:28:54.983 [error] GenServer Hovno.Repo.Pool terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1486: Enum.reduce/3
    (mariaex) lib/mariaex/query.ex:135: DBConnection.Query.Mariaex.Query.decode/3
    (db_connection) lib/db_connection.ex:423: DBConnection.query/4
    (mariaex) lib/mariaex.ex:138: Mariaex.query/4
    (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
    (stdlib) timer.erl:197: :timer.tc/3
```

**Comment by reneklacan** [comment]
Downgrading to mariaex 0.6.5 from 0.7.0 solved this issue.

I'm closing this issue and I will create one in mariaex repo.

Thanks :laughing:

**Comment by reneklacan** [comment]
https://github.com/xerions/mariaex/issues/99

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by qurben** [comment]
This just got fixed. mariaex version 0.7.2. is now available.
