### ISSUE TITLE
Compilation error on file lib/phoenix/socket.ex

### ISSUE THREAD

**Issue by HamzaLJ** [phoenixframework/phoenix#1601]
Hello,
I followed the installation as per the steps of the website; however, I am getting this error:

```
# mix phoenix.server
lib/mix/tasks/compile.phoenix.ex:30: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)

Compiled lib/mix/tasks/compile.phoenix.ex
Compiled lib/mix/phoenix.ex
lib/mix/tasks/phoenix.new.ex:1: warning: redefining module Mix.Tasks.Phoenix.New
Compiled lib/mix/tasks/phoenix.gen.resource.ex
Compiled lib/mix/tasks/phoenix.new.ex
Compiled lib/mix/tasks/phoenix.routes.ex
Compiled lib/mix/tasks/phoenix.server.ex
Compiled lib/phoenix.ex
Compiled lib/phoenix/code_reloader/change_detector.ex
Compiled lib/phoenix/code_reloader/proxy.ex
Compiled lib/phoenix/code_reloader.ex
Compiled lib/phoenix/code_reloader/server.ex
Compiled lib/phoenix/config.ex
Compiled lib/phoenix/controller/pipeline.ex
Compiled lib/phoenix/endpoint.ex
Compiled lib/phoenix/endpoint/adapter.ex
Compiled lib/phoenix/endpoint/cowboy_handler.ex
Compiled lib/phoenix/endpoint/cowboy_websocket.ex
Compiled lib/phoenix/controller.ex
Compiled lib/phoenix/controller/logger.ex
Compiled lib/phoenix/endpoint/watcher.ex
Compiled lib/phoenix/endpoint/server.ex
Compiled lib/phoenix/exceptions.ex
Compiled lib/phoenix/html/controller.ex
Compiled lib/phoenix/html.ex
Compiled lib/phoenix/html/engine.ex
Compiled lib/phoenix/html/tag.ex
Compiled lib/phoenix/html/link.ex
Compiled lib/phoenix/html/safe.ex
Compiled lib/phoenix/html/form_data.ex
Compiled lib/phoenix/html/form.ex
Compiled lib/phoenix/naming.ex
Compiled lib/phoenix/pubsub.ex
Compiled lib/phoenix/pubsub/local.ex
Compiled lib/phoenix/pubsub/pg2.ex
Compiled lib/phoenix/pubsub/pg2_server.ex
Compiled lib/phoenix/param.ex
Compiled lib/phoenix/pubsub/redis.ex
Compiled lib/phoenix/pubsub/redis_conn.ex
Compiled lib/phoenix/pubsub/redis_server.ex
Compiled lib/phoenix/endpoint/error_handler.ex
Compiled lib/phoenix/router.ex
Compiled lib/phoenix/router/resource.ex
Compiled lib/phoenix/router/route.ex
Compiled lib/phoenix/router/helpers.ex
Compiled lib/phoenix/router/console_formatter.ex
Compiled lib/phoenix/router/scope.ex

== Compilation error on file lib/phoenix/socket.ex ==
** (ArgumentError) Access is not a protocol, cannot derive Access for Phoenix.Socket
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:583: Protocol.derive/5
    (stdlib) lists.erl:1337: :lists.foreach/2
    (elixir) lib/protocol.ex:571: Protocol.__derive__/3
    lib/phoenix/socket.ex:24: (module)

```

Any ideas on how can I solve it?

I am running under Ubuntu Server.

**Comment by josevalim** [comment]
It seems you are using an old Phoenix version. What is your Phoenix version?

**Please, please** obey the "Issue Template" GitHub shows when opening an issue. Otherwise we need to ask exactly the questions the template was supposed to help with.

**Comment by josevalim** [comment]
In fact, can you please resubmit the issue properly filling the template? Thank you.

**Comment by HamzaLJ** [comment]
@josevalim I've just installed Phoenix, so I assume that it is the latest version.
Can you please send me the template to re-open the issue?

**Comment by Gazler** [comment]
@HamzaLJ When you open an issue on GitHub, the text of the issue should be pre-populated with the contents of https://github.com/phoenixframework/phoenix/blob/master/ISSUE_TEMPLATE.md

**Comment by josevalim** [comment]
Thanks for the help @Gazler!

@HamzaLJ that would be curious, you should have the latest then. Please keep us posted :)

If you want to try to re-install , just run this:

    $  mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez

And then let us know `elixir -v` and `mix phoenix.new -v`.

**Comment by jskinne3** [comment]
A note for future developers who google onto this page: the "Getting Started with Phoenix" guide that was my first hit for learning this technology is very out of date, causing me to encounter this error. A more up-to-date guide is: https://hexdocs.pm/phoenix/up_and_running.html
