### ISSUE TITLE
curl post Content-type: multipart/form-data parse error

### ISSUE THREAD

**Issue by AndwareSsj** [phoenixframework/phoenix#1623]
### Environment

* Elixir version (elixir 1.2.2):
* Phoenix version (1.1.4):
* NodeJS version (5.9.0):
* NPM version (3.7.3):
* Operating system: mac os x 10.11.4

in curl:

```
curl -X POST -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 104245a4-6486-3aad-b1c8-71f24f450b57" -F "name=test" -F "email=4429108@11.xc" "http://localhost:4000/api/v1/admin/users"
```

error:

```
[warn] ** (Plug.Parsers.ParseError) malformed request, got MatchError with message no match of right hand side value: false
    (plug) lib/plug/parsers/multipart.ex:14: Plug.Parsers.MULTIPART.parse/5
    (plug) lib/plug/parsers.ex:186: Plug.Parsers.reduce/6
    (china_phoneix) lib/china_phoneix/endpoint.ex:1: ChinaPhoneix.Endpoint.phoenix_pipeline/1
    (china_phoneix) lib/plug/debugger.ex:93: ChinaPhoneix.Endpoint."call (overridable 3)"/2
    (china_phoneix) lib/phoenix/endpoint/render_errors.ex:34: ChinaPhoneix.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by chrismccord** [comment]
Are you only seeing this with curl or can you recreate elsewhere? Are you positive your curl multipart payload is valid?

**Comment by AndwareSsj** [comment]
I always test in android client and curl post ,get same error and make sure this curl post code valid

**Comment by chrismccord** [comment]
Since you passed a boundary in the header, you need to frame your body properly, for example this will work:

```
$ curl -X POST \
-H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" \
-H "Accept: application/json" \
-H "Cache-Control: no-cache" \
-H "Postman-Token: 104245a4-6486-3aad-b1c8-71f24f450b57" \
-d $'------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name="name"\r\n\r\ntest\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name="email"\r\n\r\nfoo@bar\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--\r\n' \
"http://localhost:4000/api/v1/admin/users"

[info] POST /api/v1/admin/users
[debug] Processing by PresenceChat.PageController.test/2
  Parameters: %{"email" => "foo@bar", "name" => "test"}
  Pipelines: [:browser]
[info] Sent 200 in 347µs
```

**Comment by AndwareSsj** [comment]
thanks it works
