### ISSUE TITLE
Windows 8, Just starting a new phoenix project and could not start the server.

### ISSUE THREAD

**Issue by dwahyudi** [phoenixframework/phoenix#1628]
elixir version: 
```
Eshell V7.1  (abort with ^G)
IEx 1.3.0-dev
```

deps:
```
[{:phoenix, "~> 1.1.4"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_ecto, "~> 2.0"},
     {:phoenix_html, "~> 2.4"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"}]
```

node version: v5.1.1
npm version: 3.3.12
Operating system: windows 8

=========================

I just started a new project:

```
mix phoenix.new volcano --no-brunch
```

didn't change anything at all

when I run
```
mix phoenix.server
```

**Expected behaviour:**

it should just run the server

**Actual behaviour:**

```
D:\PROJECTS\volcano>mix phoenix.server
==> connection
Compiled lib/connection.ex
Generated connection app
** (FunctionClauseError) no function clause matching in String.to_char_list/1
    (elixir) lib/string.ex:1611: String.to_char_list('escript.exe "xxxxxxxx/.mix/rebar" compile skip_deps=true deps_dir="d:/PROJECTS/volcano/_build/dev/lib"')
    (mix) lib/mix/shell.ex:119: Mix.Shell.shell_command/1
    (mix) lib/mix/shell.ex:91: Mix.Shell.cmd/3
    (mix) lib/mix/tasks/deps.compile.ex:192: anonymous fn/6 in Mix.Tasks.Deps.Compile.do_command/5
    (mix) lib/mix/project.ex:211: Mix.Project.in_project/4
    (elixir) lib/file.ex:1139: File.cd!/2
    (mix) lib/mix/dep.ex:167: Mix.Dep.in_dependency/3
    (mix) lib/mix/tasks/deps.compile.ex:190: Mix.Tasks.Deps.Compile.do_command/5
```

"xxxxxxxx/.mix/rebar" just points to the rebar

the exact same thing happens when i run

```
mix ecto.create
```

or

```
mix compile
```

**Comment by josevalim** [comment]
@dwahyudi it was a bug in Elixir master. I have just pushed a commit to master. If you install it again, it should work as expected! Thank you for the report  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
Alternatively, rollback to Elixir 1.2.4 which should also work as expected.

**Comment by dwahyudi** [comment]
just pulled the new commit from elixir master. it now works :+1: 

```
D:\PROJECTS\volcano>mix phoenix.server
[info] Running Volcano.Endpoint with Cowboy using http on port 4000
```

many many thanks.
