### ISSUE TITLE
Generated @valid_attrs causes an error on dates in tests

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#1660]
Generating an application with the following:

```
mix phoenix.new datetest
cd datetest
mix ecto.create
mix phoenix.gen.html Item items name:string start_date:date
```

Then adding a validation to the `Item`

```elixir
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_length(:name, min: 70)
  end
```

Results in an error with the following test:

```elixir
defmodule Date.ItemControllerTest do
  use Date.ConnCase

  alias Date.Item
  @valid_attrs %{name: "some content", start_date: "2011-01-01"}
  @invalid_attrs %{}

  test "can't create an item with a short name", %{conn: conn} do
    conn = post conn, item_path(conn, :create), item: @valid_attrs
    assert html_response(conn, 200) =~ "New item"
  end
end
```

Error:

```
  2) test can't create an item with a short name (Date.ItemControllerTest)
     test/controllers/item_controller_test.exs:18
     ** (ArgumentError) unrecognized date "2011-01-01"
     stacktrace:
       (phoenix_html) lib/phoenix_html/form.ex:926: Phoenix.HTML.Form.date_value/1
       (phoenix_html) lib/phoenix_html/form.ex:906: Phoenix.HTML.Form.date_select/3
       (date) web/templates/item/form.html.eex:16: anonymous fn/2 in Date.ItemView.form.html/1
       (phoenix_html) lib/phoenix_html/form.ex:235: Phoenix.HTML.Form.form_for/4
       (date) web/templates/item/form.html.eex:1: Date.ItemView."form.html"/1
       (date) web/templates/item/new.html.eex:3: Date.ItemView."new.html"/1
       (date) web/templates/layout/app.html.eex:29: Date.LayoutView."app.html"/1
       (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
       (date) web/controllers/item_controller.ex:1: Date.ItemController.action/2
       (date) web/controllers/item_controller.ex:1: Date.ItemController.phoenix_controller_pipeline/2
       (date) lib/phoenix/router.ex:261: Date.Router.dispatch/2
       (date) web/router.ex:1: Date.Router.do_call/2
       (date) lib/date/endpoint.ex:1: Date.Endpoint.phoenix_pipeline/1
       (date) lib/phoenix/endpoint/render_errors.ex:34: Date.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:194: Phoenix.ConnTest.dispatch/5
       test/controllers/item_controller_test.exs:19
```

Adding the following to the controller:

```elixir
        IO.inspect changeset.model
        IO.inspect changeset.params
```

Results in the following output:

```
Test:

%Date.Item{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil,
 name: nil, start_date: nil, updated_at: nil}
%{"name" => "some content", "start_date" => "2011-01-01"}

Browser:

%Date.Item{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil,
 name: nil, start_date: nil, updated_at: nil}
%{"name" => nil,
  "start_date" => %{"day" => "1", "month" => "1", "year" => "2011"}}
```

This can be fixed by modifying `@valid_params`

```
  @valid_attrs %{name: "some content", `start_date: %Ecto.Date{day: 1, month: 1, year: 2011}`}
```

This can be fixed by modifying the generator. However I am raising this to see if that is the solution we want to go with.

**Comment by josevalim** [comment]
Let's use `%{day: 1, month: 1, year: 2011}` for now.
