### ISSUE TITLE
"mix ecto.create" fails due to 'Compilation error on file lib/gettext/backend.ex' 

### ISSUE THREAD

**Issue by polycopter** [phoenixframework/phoenix#1712]
note: a search here for "gettext" reported nothing that looked like this:

```
user@novo:~/src/elixir/phoenix/hi_phx$ mix ecto.create
==> connection
Compiled lib/connection.ex
Generated connection app
==> hi_phx
Could not find rebar, which is needed to build dependency :fs
I can install a local copy which is just used by mix
Shall I install rebar? [Yn] y
* creating /home/user/.mix/rebar
==> fs (compile)
Compiled src/sys/fsevents.erl
Compiled src/sys/inotifywait.erl
Compiled src/sys/inotifywait_win32.erl
Compiled src/fs_app.erl
Compiled src/fs_event_bridge.erl
Compiled src/fs_sup.erl
Compiled src/fs.erl
Compiled src/fs_server.erl
==> gettext
Compiled src/gettext_po_parser.yrl
Compiled src/gettext_po_parser.erl

== Compilation error on file lib/gettext/backend.ex ==
** (CompileError) lib/gettext/backend.ex:16: undefined function ::/2
    (elixir) expanding macro: Kernel.@/1
    lib/gettext/backend.ex:16: Gettext.Backend (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

could not compile dependency gettext, mix compile failed. You can recompile this dependency with `mix deps.compile gettext` or update it with `mix deps.update gettext`
user@novo:~/src/elixir/phoenix/hi_phx$ mix deps.compile gettext

== Compilation error on file lib/gettext/backend.ex ==
** (CompileError) lib/gettext/backend.ex:16: undefined function ::/2
    (elixir) expanding macro: Kernel.@/1
    lib/gettext/backend.ex:16: Gettext.Backend (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

==> gettext
could not compile dependency gettext, mix compile failed. You can recompile this dependency with `mix deps.compile gettext` or update it with `mix deps.update gettext`
user@novo:~/src/elixir/phoenix/hi_phx$ mix deps.update gettext
Hex was built against Elixir 1.0.5 and you are running 1.1.0-dev, please run `mix local.hex` to update to a matching version
Running dependency resolution
Dependency resolution completed
  gettext: 0.11.0
user@novo:~/src/elixir/phoenix/hi_phx$ mix local.hex
Found existing archive(s): hex.ez.
Are you sure you want to replace them? [Yn] y
* creating /home/user/.mix/archives/hex.ez
user@novo:~/src/elixir/phoenix/hi_phx$ mix deps.update gettext
Hex was built against Elixir 1.0.5 and you are running 1.1.0-dev, please run `mix local.hex` to update to a matching version
Running dependency resolution
Dependency resolution completed
  gettext: 0.11.0
user@novo:~/src/elixir/phoenix/hi_phx$ mix phoenix.server

== Compilation error on file lib/gettext/backend.ex ==
** (CompileError) lib/gettext/backend.ex:16: undefined function ::/2
    (elixir) expanding macro: Kernel.@/1
    lib/gettext/backend.ex:16: Gettext.Backend (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

==> gettext
could not compile dependency gettext, mix compile failed. You can recompile this dependency with `mix deps.compile gettext` or update it with `mix deps.update gettext`
user@novo:~/src/elixir/phoenix/hi_phx$
```

**Comment by wojtekmach** [comment]
> Hex was built against Elixir 1.0.5 and you are running 1.1.0-dev, please run mix local.hex to update to a matching version

not sure if it will solve it, but perhaps try again with latest stable version of Elixir.

**Comment by ericmj** [comment]
Something seems to be wrong with your elixir installation. Try to reinstall a more recent and stable version.

**Comment by chrismccord** [comment]
Please try Eric's suggestion by jumping to the latest Elixir version (1.2.x). Also, please please please in the future follow the issue template so we know what Elixir and Phoenix versions you are running on. Please upgrade to a stable, recent Elixir version and if that does not solve your issue, reply with the proper issue template details. Thanks!

**Comment by josevalim** [comment]
Closing this because without filling the issue template, the best we can do is guess. Please fill in the full report if the issue persists.

**Comment by polycopter** [comment]
some information, fwiw: Phoenix was installed on my Ubuntu 15.[10?] on the day this issue was filed; presumably the latest/current version... elixir was installed using Ubuntu's infrastructure (either apt-get or the Ubuntu GUI), and is presumably 1.1.0-dev as the error message I posted indicates. Hex was installed using "mix local.hex" (I think). I followed along with the documentation the Phoenix project provided, as best I could. Maybe you should add a caveat that only the 1.2.x elixir versions will work, or something to that effect, since Ubuntu users are (or were until recently) likely to get a 1.1 version if they use the easiest method to install it.
