### ISSUE TITLE
Poison parsing error and Server.Endpoint.HTTP terminated

### ISSUE THREAD

**Issue by bvjebin** [phoenixframework/phoenix#1713]
I am seeing these logs printed in my production app. There are two issues.

**One:**

```
def handle_info({:EXIT, pid, reason}, state) do
    Logger.info "Handle info with :EXIT called #{inspect reason}"
end
```
Above logger is printing the below statements and then Server.Endpoint.HTTP terminated. I am not explicitly killing the process by sending a reason. It is a usual termination of the process. But sill parsing is failing. Moreover I don't find a reason for parsing the reason.

```
[2016-05-17] [22:29:20.351] [info] Handle info with :EXIT called {{%Poison.SyntaxError{message: "Unexpected end of input", token: nil}, [{Poison.Parser, :parse!, 2, [file: 'lib/poison/parser.ex', line: 54]}, {Poison, :decode!, 2, [file: 'lib/poison.ex', line: 83]}, {Phoenix.Transports.WebSocketSerializer, :decode!, 2, [file: 'lib/phoenix/transports/websocket_serializer.ex', line: 41]}, {Phoenix.Transports.WebSocket, :ws_handle, 3, [file: 'lib/phoenix/transports/websocket.ex', line: 107]}, {Phoenix.Endpoint.CowboyWebSocket, :websocket_handle, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 77]}, {:cowboy_websocket, :handler_call, 7, [file: 'src/cowboy_websocket.erl', line: 588]}, {Phoenix.Endpoint.CowboyWebSocket, :resume, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 49]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}]}, {Phoenix.Endpoint.CowboyWebSocket, :resume, []}}

[2016-05-17] [22:29:20.351] [info] Handle info with :EXIT called {{%Poison.SyntaxError{message: "Unexpected end of input", token: nil}, [{Poison.Parser, :parse!, 2, [file: 'lib/poison/parser.ex', line: 54]}, {Poison, :decode!, 2, [file: 'lib/poison.ex', line: 83]}, {Phoenix.Transports.WebSocketSerializer, :decode!, 2, [file: 'lib/phoenix/transports/websocket_serializer.ex', line: 41]}, {Phoenix.Transports.WebSocket, :ws_handle, 3, [file: 'lib/phoenix/transports/websocket.ex', line: 107]}, {Phoenix.Endpoint.CowboyWebSocket, :websocket_handle, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 77]}, {:cowboy_websocket, :handler_call, 7, [file: 'src/cowboy_websocket.erl', line: 588]}, {Phoenix.Endpoint.CowboyWebSocket, :resume, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 49]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}]}, {Phoenix.Endpoint.CowboyWebSocket, :resume, []}}

[2016-05-17] [22:29:20.355] [error]  Ranch protocol #PID<0.26096.0> (:cowboy_protocol) of listener Server.Endpoint.HTTP terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (Poison.SyntaxError) Unexpected end of input
            (poison) lib/poison/parser.ex:54: Poison.Parser.parse!/2
--
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:77: Phoenix.Endpoint.CowboyWebSocket.websocket_handle/3
            (cowboy) src/cowboy_websocket.erl:588: :cowboy_websocket.handler_call/7
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:49: Phoenix.Endpoint.CowboyWebSocket.resume/3
            (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

[2016-05-17] [22:29:20.355] [error]  Ranch protocol #PID<0.26096.0> (:cowboy_protocol) of listener Server.Endpoint.HTTP terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (Poison.SyntaxError) Unexpected end of input
            (poison) lib/poison/parser.ex:54: Poison.Parser.parse!/2
```

**Second:**

I see the below error often in the logs randomly. What could be the reason for this? How to debug this? I have no clear clue what could be causing this error to happen. 

`Ranch protocol #PID<0.26096.0> (:cowboy_protocol) of listener Server.Endpoint.HTTP terminated`

Any help would be appreciated.

### Environment

* Elixir version (elixir -v): 1.2.3
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v):  5.8.0
* NPM version (npm -v): 3.7.3
* Operating system: Ubuntu 14

**Comment by chrismccord** [comment]
It appears the client is sending bad json and the logging is showing that accordingly. The terminate message is cowboy logging the websocket handler terminated. We need to know more information to help any further. For example, I'm assuming this is happening inside a channel? Inside a normal server? Are you using the standard channels client? What messages are you sending from the client that result in this kind of error?

**Comment by bvjebin** [comment]
I am using JavaScript client from phoenix for browser, https://github.com/eoinsha/JavaPhoenixChannels for android and https://github.com/davidstump/SwiftPhoenixClient for ios. 

I couldn't figure out which message is doing it. Is it possible to print the message that broke the parsing along with the stack trace? I don't print the messages in logs as this issue happens very randomly and the log files are increasing in size very fast which my server cannot hold.

One more thing I wanted to clarify: when a process exits, the reason would be something valid that can be parsed using Poison. Why is that also producing parse error? If you see my code above, you can clearly see the logger is printing the reason of exit and that has parse error while in the log file. Isn't that a different issue?

**Comment by josevalim** [comment]
>  I don't print the messages in logs as this issue happens very randomly and the log files are increasing in size very fast which my server cannot hold.

Then don't log those particular messages. What is likely happening is that the client is getting disconnected or losing connection before it sends the full message. Then Poison fails to decode an incomplete message.

> One more thing I wanted to clarify: when a process exits, the reason would be something valid that can be parsed using Poison. Why is that also producing parse error? 

I did not understand the question.

**Comment by bvjebin** [comment]
@josevalim Thanks. There is a possibility of losing connecting which might be causing the issue.

> One more thing I wanted to clarify: when a process exits, the reason would be something valid that can be parsed using Poison. Why is that also producing parse error?


My second question: I am running a watcher process where I monitor process exits with the given piece of code:
```
def handle_info({:EXIT, pid, reason}, state) do
    Logger.info "Handle info with :EXIT called #{inspect reason}"
end
```
In the log, I can see the below line which my log line having the parse error while parsing reason. I am not quite sure why reason variable' content is parsed. 

If parsing has to happen, it shouldn't fail as this reason is something generated by the system itself (something like {:shutdown, :closed}) and not a custom content. Why should it fail? Isn't that another issue?

[2016-05-17] [22:29:20.351] [info] Handle info with :EXIT called {{%Poison.SyntaxError{message: "Unexpected end of input", token: nil}, [{Poison.Parser, :parse!, 2, [file: 'lib/poison/parser.ex', line: 54]}, {Poison, :decode!, 2, [file: 'lib/poison.ex', line: 83]}, {Phoenix.Transports.WebSocketSerializer, :decode!, 2, [file: 'lib/phoenix/transports/websocket_serializer.ex', line: 41]}, {Phoenix.Transports.WebSocket, :ws_handle, 3, [file: 'lib/phoenix/transports/websocket.ex', line: 107]}, {Phoenix.Endpoint.CowboyWebSocket, :websocket_handle, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 77]}, {:cowboy_websocket, :handler_call, 7, [file: 'src/cowboy_websocket.erl', line: 588]}, {Phoenix.Endpoint.CowboyWebSocket, :resume, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 49]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}]}, {Phoenix.Endpoint.CowboyWebSocket, :resume, []}}

**Comment by josevalim** [comment]
The process you are monitoring is trying to parse something which then errors out. Because the exception is not handled, it makes the process you are monitoring crash, which then becomes an exit signal to any linked process with the EXIT message you are receiving above.

**Comment by bvjebin** [comment]
That makes sense. It is all connected then. 

Is there a way I can print and confirm which content is making the Endpoint to terminate because of parsing issue? Or should I really be worrying about it?

**Comment by josevalim** [comment]
Check how the Phoenix.Transports.WebSockets serializer is implemented. You can copy its implementation and implement your own serializer that will log or act differently for the errors above.

**Comment by bvjebin** [comment]
Thank you @chrismccord  and @josevalim 

I will do my homework now.
