### ISSUE TITLE
** (RuntimeError) could not find executable `mysql` in path, please guarantee it is available before running ecto commands

### ISSUE THREAD

**Issue by xymerz1** [phoenixframework/phoenix#1747]
Hi everyone, so I created a new app with the pheonix framework, i did the `mix pheonix.new [appName] --database mysql`

After creating the app I can't seem to create the db, when I run the command `mix ecto.create` , i get and error

I am using ubuntu 16.04 LTS
```
mix ecto.create

** (RuntimeError) could not find executable `mysql` in path, please guarantee it is available before running ecto commands
    lib/ecto/adapters/mysql.ex:139: Ecto.Adapters.MySQL.run_with_mysql/2
    lib/ecto/adapters/mysql.ex:116: Ecto.Adapters.MySQL.storage_up/1
    lib/mix/tasks/ecto.create.ex:34: anonymous fn/2 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```
here is my mix.exs

```
defmodule AppName.Mixfile do
  use Mix.Project

  def project do
    [app: :AppName,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {AppName, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :mariaex]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.1.5"},
     {:mariaex, "~> 0.6"},
     {:phoenix_ecto, "~> 2.0"},
     {:phoenix_html, "~> 2.4"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end
```

**Comment by Gazler** [comment]
You need the `mysql` executable in your path for `ecto.create` to work. https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/mysql.ex#L160

http://askubuntu.com/questions/762384/install-mysql-5-6-on-ubuntu-16-04

In uture please direct questions to the mailing list or IRC. We reserve the issue tracker for issues, as is mentioned in the issue template
