### ISSUE TITLE
get "/profiles/profile-:id", UserController, :show # test missing

### ISSUE THREAD

**Issue by gialib** [phoenixframework/phoenix#1915]
[routing_test.exs](https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/router/routing_test.exs#L25)

```elixir
get "/profiles/profile-:id", UserController, :show     # will 404  oh no
```

**Comment by josevalim** [comment]
Can you please give us more information? When opening an issue, there is a template that you should fill with all the information that you can about the issue at hand. Thank you!

**Comment by gialib** [comment]
@josevalim  Sorry， I didn't describe it clearly.

I want write routes like this

```
    get "/forum-:fid-:page", DirectsController, :topic
    get "/thread-:tid-:page-:xid", DirectsController, :post
    get "/viewthread", DirectsController, :post
```
split with more "-"，but routed failed.

```
== Compilation error on file web/router.ex ==
** (Plug.Router.InvalidSpecError) :identifier in routes must be made of letters, numbers and underscores
    (plug) lib/plug/router/utils.ex:176: Plug.Router.Utils.binary_to_identifier/2
    (plug) lib/plug/router/utils.ex:139: Plug.Router.Utils.segment_match/3
    (plug) lib/plug/router/utils.ex:103: Plug.Router.Utils.build_path_match/4
    (phoenix) lib/phoenix/router/route.ex:65: Phoenix.Router.Route.build_path_and_binding/1
    (phoenix) lib/phoenix/router/route.ex:50: Phoenix.Router.Route.exprs/1
    (phoenix) lib/phoenix/router.ex:281: Phoenix.Router."-MACRO-__before_compile__/2-fun-0-"/1
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (phoenix) expanding macro: Phoenix.Router.__before_compile__/1
    web/router.ex:1: Giabbs.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
These routes are migrated from ROR.
Even I want to  get "/forum-:fid-:page.:format", DirectsController, :topic
eg. http://example.com/forum-2-1.html 
Thanks :)

**Comment by josevalim** [comment]
You cannot use multiple formats in the same route. So this is not allowed: "/forum-:fid-:page". You will need to do something such as `:fid_page` and split them apart in the controller.

**Comment by gialib** [comment]
Ok! Thank～
