### ISSUE TITLE
Errors when repeatedly reloading the "default" application

### ISSUE THREAD

**Issue by Rukenshia** [phoenixframework/phoenix#1992]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 19 [erts-8.0] [64-bit] [smp:12:12] [async-threads:10]

Elixir 1.3.4`
```

* Phoenix version (mix deps):
```
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs) ed17036c
  ok
* gettext 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (gettext) c0624f52
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch) a6fb992c
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (decimal) 462960fd
  ok
* poison 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (poison) 4763b69a
  ok
* db_connection 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (db_connection) 63c03e52
  ok
* phoenix_pubsub 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (phoenix_pubsub) c10ddf62
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy) a324a8df
  ok
* mime 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (mime) 05c39385
  ok
* plug 1.2.2 (Hex package) (mix)
  locked at 1.2.2 (plug) cfbda521
  ok
* phoenix_html 2.7.0 (Hex package) (mix)
  locked at 2.7.0 (phoenix_html) 19e12e20
  ok
* phoenix 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix) 6dc59224
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
  ok
* postgrex 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (postgrex) 2f8b46cb
  ok
* ecto 2.0.5 (Hex package) (mix)
  locked at 2.0.5 (ecto) 7f4c79ac
  ok
* phoenix_ecto 3.0.1 (Hex package) (mix)
  locked at 3.0.1 (phoenix_ecto) 42eb486e
  ok
```

* NodeJS version (node -v): `v6.6.0`
* NPM version (npm -v): `v3.10.3`
* Operating system: Windows 10 Pro x64

### Expected behavior
no errors when reloading the default phoenix page.

### Actual behavior
```
[info] Running Meinjugendchor.Endpoint with Cowboy using http://localhost:4000
[info] GET /
[debug] Processing by Meinjugendchor.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 47ms
04 Nov 18:32:46 - info: compiled 6 files into 2 files, copied 3 in 1.4 sec
[info] GET /
[debug] Processing by Meinjugendchor.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 0┬╡s
[info] GET /
[debug] Processing by Meinjugendchor.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 0┬╡s
[info] GET /
[debug] Processing by Meinjugendchor.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 0┬╡s
[info] GET /js/app.js
[info] GET /css/app.css
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /js/app.js (Meinjugendchor.Router)
    (meinjugendchor) web/router.ex:1: Meinjugendchor.Router.match_route/4
    (meinjugendchor) web/router.ex:1: Meinjugendchor.Router.do_call/2
    (meinjugendchor) lib/meinjugendchor/endpoint.ex:1: Meinjugendchor.Endpoint.phoenix_pipeline/1
    (meinjugendchor) lib/plug/debugger.ex:123: Meinjugendchor.Endpoint."call (overridable 3)"/2
    (meinjugendchor) lib/meinjugendchor/endpoint.ex:1: Meinjugendchor.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /css/app.css (Meinjugendchor.Router)
    (meinjugendchor) web/router.ex:1: Meinjugendchor.Router.match_route/4
    (meinjugendchor) web/router.ex:1: Meinjugendchor.Router.do_call/2
    (meinjugendchor) lib/meinjugendchor/endpoint.ex:1: Meinjugendchor.Endpoint.phoenix_pipeline/1
    (meinjugendchor) lib/plug/debugger.ex:123: Meinjugendchor.Endpoint."call (overridable 3)"/2
    (meinjugendchor) lib/meinjugendchor/endpoint.ex:1: Meinjugendchor.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

This happens quite often. All I did was follow the installation guide and manually reload the localhost page.

**Comment by josevalim** [comment]
It is an issue about Elixir on Windows. Every time we compile the code, we copy everything in the the priv directory to your application. This has been improved on Elixir master so we only copy assets that have actually changed. So Elixir v1.4 solves this (and it should be out by the end of December). Please hold on a little bit longer (or give master a try). :) Thank you!
