### ISSUE TITLE
Default installation, non-deterministic page asset loading

### ISSUE THREAD

**Issue by jameskraus** [phoenixframework/phoenix#2040]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 19 [erts-8.0] [64-bit] [smp:4:4] [async-threads:10]

Elixir 1.3.4
```
* Phoenix version (mix deps): `1.2.1 (phoenix) 6dc59224`
* NodeJS version (node -v): `v6.9.1`
* NPM version (npm -v): `3.10.8`
* Operating system: Windows 10 x64

### Expected behavior

Loads the default start page at http://localhost:4000/

### Actual behavior

Loads the start page most of the time, but sometimes the page assets fail to load. I get this error in the debug window.

```
** (File.Error) could not remove files and directories recursively from "c:/dev/scratchpad/pheonix-test/first_app/_build/dev/lib/first_app/priv": file already exists
    (elixir) lib/file.ex:919: File.rm_rf!/1
    (mix) lib/mix/utils.ex:317: Mix.Utils.symlink_or_copy/2
    (mix) lib/mix/project.ex:414: Mix.Project.build_structure/2
    (phoenix) lib/phoenix/code_reloader/server.ex:131: Phoenix.CodeReloader.Server.mix_compile/1
    (phoenix) lib/phoenix/code_reloader/server.ex:103: Phoenix.CodeReloader.Server.mix_compile/3
    (phoenix) lib/phoenix/code_reloader/server.ex:41: anonymous fn/2 in Phoenix.CodeReloader.Server.handle_call/3
    (phoenix) lib/phoenix/code_reloader/server.ex:152: Phoenix.CodeReloader.Server.proxy_io/1
    (phoenix) lib/phoenix/code_reloader/server.ex:39: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

[info] GET /images/phoenix.png
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /images/phoenix.png (FirstApp.Router)
    (first_app) web/router.ex:1: FirstApp.Router.match_route/4
    (first_app) web/router.ex:1: FirstApp.Router.do_call/2
    (first_app) lib/first_app/endpoint.ex:1: FirstApp.Endpoint.phoenix_pipeline/1
    (first_app) lib/plug/debugger.ex:123: FirstApp.Endpoint."call (overridable 3)"/2
    (first_app) lib/first_app/endpoint.ex:1: FirstApp.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by josevalim** [comment]
This has been fixed in Elixir v1.4.0. There is a release candidate out that you could try. We have also slightly improved it in Phoenix master.

This only happens in development btw, so if you can't upgrade Elixir right now, you should still be fine. :)
