### ISSUE TITLE
Context isn't handled properly when re-running generators

### ISSUE THREAD

**Issue by smadeja** [phoenixframework/phoenix#2150]
I'm on the latest development version (074a584ae324f78fa89f7ca097c38f8805d3021e).

### Steps to reproduce

1. Run `$ mix phx.gen.html Accounts User users name:string`
2. (Update the router)
3. Run `$ mix phx.gen.html Accounts User users name:string` again

### Expected behavior

I'm asked if I want to overwrite the context, and the context gets overwritten if I say yes.

### Actual behavior

I'm asked if I want to overwrite each file except the context. Inside the `DevApp.Accounts` module, duplicate method definitions are added. Subsequent runs of the task will continue duplicating code in said module.

```
* creating lib/dev_app/web/controllers/user_controller.ex
lib/dev_app/web/controllers/user_controller.ex already exists, overwrite? [Yn] y
* creating lib/dev_app/web/templates/user/edit.html.eex
lib/dev_app/web/templates/user/edit.html.eex already exists, overwrite? [Yn] y
* creating lib/dev_app/web/templates/user/form.html.eex
lib/dev_app/web/templates/user/form.html.eex already exists, overwrite? [Yn] y
* creating lib/dev_app/web/templates/user/index.html.eex
lib/dev_app/web/templates/user/index.html.eex already exists, overwrite? [Yn] y
* creating lib/dev_app/web/templates/user/new.html.eex
lib/dev_app/web/templates/user/new.html.eex already exists, overwrite? [Yn] y
* creating lib/dev_app/web/templates/user/show.html.eex
lib/dev_app/web/templates/user/show.html.eex already exists, overwrite? [Yn] y
* creating lib/dev_app/web/views/user_view.ex
lib/dev_app/web/views/user_view.ex already exists, overwrite? [Yn] y
* creating test/web/controllers/user_controller_test.exs
test/web/controllers/user_controller_test.exs already exists, overwrite? [Yn] y
* creating lib/dev_app/accounts/user.ex
lib/dev_app/accounts/user.ex already exists, overwrite? [Yn] y
* creating priv/repo/migrations/20170304100806_create_accounts_user.exs
```

### `accounts.ex` before
```elixir
defmodule DevApp.Accounts do
  @moduledoc """
  The boundary for the Accounts system.
  """

  import Ecto.{Query, Changeset}, warn: false
  alias DevApp.Repo

  alias DevApp.Accounts.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(user, %{field: value})
      {:ok, %User{}}

      iex> create_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> user_changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> user_changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    user_changeset(user, %{})
  end

  defp user_changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end
```

### `accounts.ex` after

```elixir
defmodule DevApp.Accounts do
  @moduledoc """
  The boundary for the Accounts system.
  """

  import Ecto.{Query, Changeset}, warn: false
  alias DevApp.Repo

  alias DevApp.Accounts.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(user, %{field: value})
      {:ok, %User{}}

      iex> create_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> user_changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> user_changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    user_changeset(user, %{})
  end

  defp user_changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end

  alias DevApp.Accounts.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(user, %{field: value})
      {:ok, %User{}}

      iex> create_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> user_changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> user_changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    user_changeset(user, %{})
  end

  defp user_changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end
```

**Comment by josevalim** [comment]
This is by design as you can have multiple resources wrapped by the same
context. But we need to do something in case the resource already exists in
the context.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by smadeja** [comment]
Oh, that's right. So I guess the issue is valid, but the expected behaviour is different? The resulting compilation error can be pretty confusing for someone who's just starting out with Phoenix.

```
== Compilation error on file lib/dev_app/accounts/accounts.ex ==
** (CompileError) lib/dev_app/accounts/accounts.ex:154: definitions with multiple clauses and default values require a header. Instead of:

    def foo(:first_clause, b \\ :default) do ... end
    def foo(:second_clause, b) do ... end

one should write:

    def foo(a, b \\ :default)
    def foo(:first_clause, b) do ... end
    def foo(:second_clause, b) do ... end

def create_user/1 has multiple clauses and defines defaults in one or more clauses
    lib/dev_app/accounts/accounts.ex:154: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by josevalim** [comment]
> Oh, that's right. So I guess the issue is valid, but the expected behaviour is different?

Yes, precisely! :D

**Comment by dustinfarris** [comment]
Concern also for generated test, e.g.:

You get:

```elixir
def fixture(:post, attrs \\ @create_attrs) do
  {:ok, post} = Blog.create_post(attrs)
  post
end
```

so i think, ok, this is how i do fixtures, so i add comment fixture:

```elixir
def fixture(:post, attrs \\ @create_attrs) do
  {:ok, post} = Blog.create_post(attrs)
  post
end
def fixture(:comment, attrs \\ @create_comment_attrs) do
  {:ok, comment} = Blog.create_comment(attrs)
  comment
end
```

then i get the same "multiple clauses" error

**Comment by lizvdk** [comment]
@dustinfarris what is the correct way to have multiple fixtures in the same file? As @smadeja pointed out, the error is difficult to understand for people new to Elixir/Phoenix.

**Comment by chrismccord** [comment]
Master and upcoming 1.3.0 final generate fixture functions with unique names, such as `user_fixture`, `comment_fixture`, etc, to avoid this confusion and compiler warnings
https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.context/test_cases.exs#L9-L16

**Comment by lizvdk** [comment]
@chrismccord Excellent, thank you!
