### ISSUE TITLE
Using cyrillic symbols in select

### ISSUE THREAD

**Issue by etroynov** [phoenixframework/phoenix#2199]
### Environment

* Elixir version: 1.4.2
* Phoenix version (mix deps): 1.2.3
* Operating system: arch linux

### Expected behavior
![expect](https://cloud.githubusercontent.com/assets/4591518/24083317/97dc1954-0cf6-11e7-8d06-b3bddc3e798c.png)
### Actual behavior

```
Compiling 1 file (.ex)

== Compilation error on file web/views/user_view.ex ==
** (ArgumentError) argument error
    :erlang.binary_to_atom("Неактивный", :utf8)
    (elixir) src/elixir_parser.yrl:512: :elixir_parser.yeccpars2_93/7
    (elixir) /usr/lib/erlang/lib/parsetools-2.1.4/include/yeccpre.hrl:57: :elixir_parser.yeccpars0/5
    (eex) lib/eex/compiler.ex:36: EEx.Compiler.generate_buffer/4
    (eex) lib/eex/compiler.ex:43: EEx.Compiler.generate_buffer/4
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    web/views/user_view.ex:1: ExPress.UserView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

------------------------------------------------------------------------------------------------

Hi,

I use

```
<div class="form-group">
    <%= label f, :status, class: "control-label" %>
    <%= select f, :status,  ["Неактивный": "0", "User": "user"], class: "form-control" %>
    <%= error_tag f, :status %>
  </div>
```

I think that problem is with transform cyrillic symbols.

At this time, i just use pure html.

**Comment by josevalim** [comment]
Erlang 19 does not support UTF-8 atoms but it is coming on Erlang 20. You will have to write it like this for now: `[{"Неактивный", "0"}, {"User", "user"}]`
