### ISSUE TITLE
Test can not pass after generate a json resource.

### ISSUE THREAD

**Issue by developerworks** [phoenixframework/phoenix#2243]
### Environment

* Elixir version (1.4.2):
* Phoenix version (mix deps):
```
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (gettext) 5e0daf4e
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (decimal) 157b3ced
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* db_connection 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (db_connection) 2865c2a4
  ok
* phoenix_pubsub 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (phoenix_pubsub) c10ddf62
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (mime) 01c1d6f4
  ok
* plug 1.3.4 (Hex package) (mix)
  locked at 1.3.4 (plug) b4ef3a38
  ok
* phoenix 1.3.0-rc.1 (Hex package) (mix)
  locked at 1.3.0-rc.1 (phoenix) 0d04948a
  ok
* postgrex 0.13.2 (Hex package) (mix)
  locked at 0.13.2 (postgrex) 2b88168f
  ok
* ecto 2.1.4 (Hex package) (mix)
  locked at 2.1.4 (ecto) d1ba9328
  ok
* phoenix_ecto 3.2.3 (Hex package) (mix)
  locked at 3.2.3 (phoenix_ecto) 450c7498
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (gettext) 5e0daf4e
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (decimal) 157b3ced
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* db_connection 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (db_connection) 2865c2a4
  ok
* phoenix_pubsub 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (phoenix_pubsub) c10ddf62
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (mime) 01c1d6f4
  ok
* plug 1.3.4 (Hex package) (mix)
  locked at 1.3.4 (plug) b4ef3a38
  ok
* phoenix 1.3.0-rc.1 (Hex package) (mix)
  locked at 1.3.0-rc.1 (phoenix) 0d04948a
  ok
* postgrex 0.13.2 (Hex package) (mix)
  locked at 0.13.2 (postgrex) 2b88168f
  ok
* ecto 2.1.4 (Hex package) (mix)
  locked at 2.1.4 (ecto) d1ba9328
  ok
* phoenix_ecto 3.2.3 (Hex package) (mix)
  locked at 3.2.3 (phoenix_ecto) 450c7498
  ok
```
* NodeJS version (v6.9.1):
* NPM version (4.1.2):
* Operating system: Mac OSX

When i generate a json resource with `mix phx.gen.json Accounts User users name` and the `mix ecto.setup` to create database repo and run test with `mix test`, raise the following errors.

```
  1) test creates user and renders user when data is valid (Ad.Web.UserControllerTest)
     test/web/controllers/user_controller_test.exs:25
     ** (UndefinedFunctionError) function UserController.init/1 is undefined (module UserController is not available)
     stacktrace:
       UserController.init(:create)
       (ad) lib/ad/web/router.ex:1: anonymous fn/1 in Ad.Web.Router.__match_route__/4
       (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.plug_builder_call/2
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/web/controllers/user_controller_test.exs:26: (test)



  2) test deletes chosen user (Ad.Web.UserControllerTest)
     test/web/controllers/user_controller_test.exs:57
     ** (UndefinedFunctionError) function UserController.init/1 is undefined (module UserController is not available)
     stacktrace:
       UserController.init(:delete)
       (ad) lib/ad/web/router.ex:1: anonymous fn/1 in Ad.Web.Router.__match_route__/4
       (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.plug_builder_call/2
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/web/controllers/user_controller_test.exs:59: (test)



  3) test does not create user and renders errors when data is invalid (Ad.Web.UserControllerTest)
     test/web/controllers/user_controller_test.exs:35
     ** (UndefinedFunctionError) function UserController.init/1 is undefined (module UserController is not available)
     stacktrace:
       UserController.init(:create)
       (ad) lib/ad/web/router.ex:1: anonymous fn/1 in Ad.Web.Router.__match_route__/4
       (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.plug_builder_call/2
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/web/controllers/user_controller_test.exs:36: (test)



  4) test does not update chosen user and renders errors when data is invalid (Ad.Web.UserControllerTest)
     test/web/controllers/user_controller_test.exs:51
     ** (UndefinedFunctionError) function UserController.init/1 is undefined (module UserController is not available)
     stacktrace:
       UserController.init(:update)
       (ad) lib/ad/web/router.ex:1: anonymous fn/1 in Ad.Web.Router.__match_route__/4
       (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.plug_builder_call/2
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/web/controllers/user_controller_test.exs:53: (test)



  5) test updates chosen user and renders user when data is valid (Ad.Web.UserControllerTest)
     test/web/controllers/user_controller_test.exs:40
     ** (UndefinedFunctionError) function UserController.init/1 is undefined (module UserController is not available)
     stacktrace:
       UserController.init(:update)
       (ad) lib/ad/web/router.ex:1: anonymous fn/1 in Ad.Web.Router.__match_route__/4
       (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.plug_builder_call/2
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/web/controllers/user_controller_test.exs:42: (test)



  6) test lists all entries on index (Ad.Web.UserControllerTest)
     test/web/controllers/user_controller_test.exs:20
     ** (UndefinedFunctionError) function UserController.init/1 is undefined (module UserController is not available)
     stacktrace:
       UserController.init(:index)
       (ad) lib/ad/web/router.ex:1: anonymous fn/1 in Ad.Web.Router.__match_route__/4
       (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.plug_builder_call/2
       (ad) lib/ad/web/endpoint.ex:1: Ad.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/web/controllers/user_controller_test.exs:21: (test)
```

**Comment by developerworks** [comment]
Fixed with move the resources definitions into `scope "/api"` in router like this:

```
defmodule Ad.Web.Router do
  use Ad.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", Ad.Web do
    pipe_through :api
    resources "/users", UserController
    resources "/roles", RoleController
  end

end

```
