### ISSUE TITLE
get join crashed when join a channel in production mode

### ISSUE THREAD

**Issue by Casear** [phoenixframework/phoenix#2329]
I test join channel successfully in development mode
but  join channel in production mode and get join crash message.
Here is my device_channel.ex
```
defmodule APP.DeviceChannel do
  use Phoenix.Channel
  def join("devices:"<>id, _message ,socket) do
    {:ok, socket}
  end


  def handle_in("new_msg", %{"body" => body}, socket) do
    {:reply, :ok, socket}
  end
end
```

Any idea about what happen?

### Environment

* Elixir version (elixir -v): 1.4
* Phoenix version (mix deps): 1.2
* Operating system: ubuntu

### Actual behavior
```
08:38:26.733 [info] JOIN devices:1234 to APP.DeviceChannel
  Transport:  Phoenix.Transports.WebSocket
  Parameters: %{}

=CRASH REPORT==== 30-May-2017::08:38:26 ===
  crasher:
    initial call: Elixir.Phoenix.Channel.Server:init/1
    pid: <0.1826.0>
    registered_name: []
    exception exit: {badarg,
                        [{ets,lookup,[nil,subscribe],[]},
                         {'Elixir.Phoenix.PubSub',call,3,
                             [{file,"lib/phoenix/pubsub.ex"},{line,288}]},
                         {'Elixir.Phoenix.Channel.Server',join,4,
                             [{file,"lib/phoenix/channel/server.ex"},
                              {line,197}]},
                         {gen_server,init_it,6,
                             [{file,"gen_server.erl"},{line,328}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:init_it/6 (gen_server.erl, line 352)
    ancestors: [<0.1825.0>]
    messages: []
    links: [<0.1825.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 166
  neighbours:
08:38:26.733 [error] an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(nil, :subscribe)
        (phoenix_pubsub) lib/phoenix/pubsub.ex:288: Phoenix.PubSub.call/3
        (phoenix) lib/phoenix/channel/server.ex:197: Phoenix.Channel.Server.join/4
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
Can you provide a sample application that reproduces the error? If I have to guess, one of your dependencies were not started.

**Comment by Casear** [comment]
fianlly found the reason on prod.exs setting.
```
pubsub: [name: APP.PubSub, adapter: Phoenix.PubSub.PG2]
```
Even I add the setting , it still join failed. 
Because I deploy it using distillery.
It seems affected join to channel.

**Comment by Casear** [comment]
fianlly found the reason on prod.exs setting.
```
pubsub: [name: APP.PubSub, adapter: Phoenix.PubSub.PG2]
```
Even I add the setting , it still join failed. 
Because I deploy it using distillery.
It seems affected join to channel.
