### ISSUE TITLE
mix phx.digest failed

### ISSUE THREAD

**Issue by bossyang** [phoenixframework/phoenix#2401]
```bash
mix phx.digest
# or MIX_ENV=prod mix.digest
```

### Environment

* Elixir version (elixir -v): 1.4.5
* Phoenix version (mix deps): 1.3.0-rc3
* NodeJS version (node -v): 6.11.0
* NPM version (npm -v): 3.10.10
* Operating system: macOS 10.12.5

### Expected behavior
```
Check your digested files at "priv/static".
```

### Actual behavior
```
** (MatchError) no match of right hand side value: {:error, {:plug, {'no such file or directory', 'plug.app'}}}
    (phoenix) lib/mix/tasks/phx.digest.ex:43: Mix.Tasks.Phx.Digest.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

**Comment by josevalim** [comment]
Can you please run `mix do deps.loadpaths, phx.digest` and let us know if it works?

**Comment by bossyang** [comment]
Oh yeah, it works!

**Comment by josevalim** [comment]
Fixed in master!
