### ISSUE TITLE
phx.gen.json Compiling Error

### ISSUE THREAD

**Issue by billxinli** [phoenixframework/phoenix#2454]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

* Phoenix version (mix deps):
```
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (gettext) 5e0daf4e
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar3)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (decimal) fac965ce
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* db_connection 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (db_connection) 2865c2a4
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (mime) 01c1d6f4
  ok
* plug 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (plug) 236d77ce
  ok
* phoenix 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (phoenix) 1c01124c
  ok
* mariaex 0.8.3 (Hex package) (mix)
  locked at 0.8.3 (mariaex) bf51ff4d
  ok
* ecto 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (ecto) 87e98576
  ok
* phoenix_ecto 3.2.3 (Hex package) (mix)
  locked at 3.2.3 (phoenix_ecto) 450c7498
  ok

```
* NodeJS version (node -v): 8.4.0
* NPM version (npm -v): 5.3.0
* Operating system: Ubuntu 16.04LTS

### Expected behavior

Step 1: Generate a simple JSON end point:
```
$> mix phx.gen.json API ContentAsset content_assets content_id:integer
* creating lib/my_app_web/controllers/content_asset_controller.ex
* creating lib/my_app_web/views/content_asset_view.ex
* creating test/my_app_web/controllers/content_asset_controller_test.exs
* creating lib/my_app_web/views/changeset_view.ex
* creating lib/my_appi_web/controllers/fallback_controller.ex
* creating lib/my_app/api/content_asset.ex
* creating priv/repo/migrations/20170823191342_create_content_assets.exs
* creating lib/my_app/api/api.ex
* injecting lib/my_app/api/api.ex
* creating test/my_app/api/api_test.exs
* injecting test/my_app/api/api_test.exs

Add the resource to your :api scope in lib/my_app_web/router.ex:

    resources "/content_assets", ContentAssetController, except: [:new, :edit]


Remember to update your repository by running migrations:

    $ mix ecto.migrate
```

Step 2: Migrate the database and add the resources block to the api scope.

Step 3: Be able to hit the end point at http://localhost:4000/api/content_assets

### Actual behavior

$> mix phx.server
Compiling 12 files (.ex)
```
== Compilation error in file lib/my_app_web/views/content_asset_view.ex ==
** (CompileError) lib/my_app_web/views/content_asset_view.ex:2: module MyAppWeb is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/my_app_web/views/content_asset_view.ex:2: MyAppWeb.ContentAssetView (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by josevalim** [comment]
How did you create the app? Any chance you created it with `mix phoenix.new` instead of `mix phx.new`? Or is it an old app?

**Comment by billxinli** [comment]
I generated the app with `mix pheonix.new` but I just tried with `mix phx.new` and the `mix phx.gen.json` worked properly. Out of curiosity, (I am new to phoenix) what is the difference between the two prefixes? `mix phoenix` vs `mix phx`

**Comment by PhillippOhlandt** [comment]
`mix phoenix` is Phoenix 1.2 and below and `mix phx` is Phoenix 1.3 (current) and above.

**Comment by billxinli** [comment]
@PhillippOhlandt Understood. I will close the issue and update the SO question to reflect the findings.
