### ISSUE TITLE
java.sql.SQLException: ERROR 201 (22000): Illegal data. Expected length of at least 54 bytes, but had 16         at 

### ISSUE THREAD

**Issue by starbow727** [phoenixframework/phoenix#2526]
0: jdbc:phoenix:192.168.200.100:2181/hbase,19> select id,link_name from ZYB_ORDER_INFO limit 10;
Error: ERROR 201 (22000): Illegal data. Expected length of at least 54 bytes, but had 16 (state=22000,code=201)
java.sql.SQLException: ERROR 201 (22000): Illegal data. Expected length of at least 54 bytes, but had 16
        at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:454)
        at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:145)
        at org.apache.phoenix.schema.KeyValueSchema.next(KeyValueSchema.java:211)
        at org.apache.phoenix.expression.ProjectedColumnExpression.evaluate(ProjectedColumnExpression.java:115)
        at org.apache.phoenix.compile.ExpressionProjector.getValue(ExpressionProjector.java:69)
        at org.apache.phoenix.jdbc.PhoenixResultSet.getString(PhoenixResultSet.java:608)
        at sqlline.Rows$Row.<init>(Rows.java:183)
        at sqlline.BufferedRows.<init>(BufferedRows.java:38)
        at sqlline.SqlLine.print(SqlLine.java:1649)
        at sqlline.Commands.execute(Commands.java:833)
        at sqlline.Commands.sql(Commands.java:732)
        at sqlline.SqlLine.dispatch(SqlLine.java:807)
        at sqlline.SqlLine.begin(SqlLine.java:681)
        at sqlline.SqlLine.start(SqlLine.java:398)
        at sqlline.SqlLine.main(SqlLine.java:292)

**Comment by Gazler** [comment]
I think you may have the wrong Phoenix. I believe you want https://phoenix.apache.org/issues.html
