### ISSUE TITLE
Confusing error when 'forward'ed plug doesn't return a valid Conn

### ISSUE THREAD

**Issue by jjl** [phoenixframework/phoenix#2528]
When a plug you `Phoenix.Controller.forward` to doesn't return a valid connection, you get a confusing error:

```
api_1    | [error] #PID<0.520.0> running Carpathia.Endpoint terminated
api_1    | Server: localhost:4000 (http)
api_1    | Request: GET /admin/
api_1    | ** (exit) an exception was raised:
api_1    |     ** (KeyError) key :path_info not found
api_1    |         (phoenix) lib/phoenix/router/route.ex:162: Phoenix.Router.Route.forward/4
api_1    |         (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
api_1    |         (carpathia) lib/endpoint.ex:1: Carpathia.Endpoint.plug_builder_call/2
api_1    |         (carpathia) lib/plug/debugger.ex:99: Carpathia.Endpoint."call (overridable 3)"/2
api_1    |         (carpathia) lib/endpoint.ex:1: Carpathia.Endpoint.call/2
api_1    |         (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
api_1    |         (cowboy) /app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

### Environment

Elixir 1.5.1, Erlang R20

### Expected behavior

We should have a nicer error message

### Actual behavior

Confused me and Jose.

**Comment by chrismccord** [comment]
Fixed on master. Thanks for the report!
