### ISSUE TITLE
Unable to install module semver in OSX Tutorial

### ISSUE THREAD

**Issue by quantumproducer** [phoenixframework/phoenix#2617]
### Environment

* Elixir version (elixir -v): Erlang/OTP 20 [erts-9.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
* Phoenix version (mix deps): installed today
* NodeJS version (node -v): 8.6.0
* NPM version (npm -v):
I force uninstalled node & npm with node, then did
brew install npm
brew install node

I still get this error:

```
~/hello/assets/npm install
module.js:538
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

How do I install semver on OSX and get my hello world project up and running?

**Comment by chrismccord** [comment]
I haven't seen this error before. Looks like node is up to 8.9 LTS / 9.0 stable. Can you try jumping on latest node and seeing if the issue persists? Thanks!
