### ISSUE TITLE
Official Phoenix Framework contexts tutorial introduces lib/haaksploits_web/controllers/session_controller.ex:21: undefined function session_path/2 error into my application

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2636]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2

* Phoenix version (mix deps):

phoenix 1.3.0 (Hex package) (mix)
locked at 1.3.0 (phoenix) 1c01124c

* NodeJS version (node -v):

v8.7.0

* NPM version (npm -v):

5.4.2

* Operating system:

MacOS High Sierra Version 10.13.1

### Expected behavior

Expected to work as described in tutorial:

> Now if you visit the sign-in page at http://localhost:4000/sessions/new and enter a bad email address, you should be greeted with your flash message. Entering a valid email address will redirect to the home page with a success flash notice.

Source: [https://hexdocs.pm/phoenix/contexts.html](https://hexdocs.pm/phoenix/contexts.html)

### Actual behavior

System gives following error in browser:

```
Compiling 24 files (.ex)

== Compilation error in file lib/haaksploits_web/controllers/session_controller.ex ==
** (CompileError) lib/haaksploits_web/controllers/session_controller.ex:21: undefined function session_path/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I am following the exact process listed in the tutorial, and have followed it through three times, being careful to copy and paste directly to prevent typos, and changing all Hello and HelloWeb app references to those appropriate for my application and nothing else.

Hence it logically appears there is either a problem with the Phoenix Framework, or with the documentation as the application was working fine before I began the step beginning with

> To begin extending our Accounts context with real features, let’s address an obvious issue of our application – we can create users with credentials in our system, but they have no way of signing in with those credentials

**Comment by pedep** [comment]
You probably forgot to add the `resources "/session", SessionController, except: [:new, :edit]` to your router

**Comment by chrismccord** [comment]
Can you include the contents of your router? Did you forget to add a route definition for the session?

**Comment by PeterDavidCarter** [comment]
```
defmodule HaaksploitsWeb.Router do
  use HaaksploitsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, "Login required")
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      user_id ->
        assign(conn, :current_user, Haaksploits.Accounts.get_user!(user_id))
    end
  end

  scope "/", HaaksploitsWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/tutorials", TutorialsController, :index
    get "/haaksploits", HaaksploitsController, :index
    get "/security", SecurityController, :index
    get "/unclassified", UnclassifiedController, :index

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true

    # Tutorials intro pages
    scope "/tutorials" do
      get "/linux", TutorialsController, :linux
      get "/devtools", TutorialsController, :devtools
      get "/databases", TutorialsController, :databases
      get "/rawcode", TutorialsController, :rawcode
      scope "/linux_s1" do
        get "/1-2.html", TutorialsController, :tls1p2
        get "/1-3.html", TutorialsController, :tls1p3
        get "/1-4.html", TutorialsController, :tls1p4
        get "/1-5.html", TutorialsController, :tls1p5
      end
      scope "/devtools_s1" do
        get "/1-2.html", TutorialsController, :tdevs1p2
        get "/1-3.html", TutorialsController, :tdevs1p3
        get "/1-4.html", TutorialsController, :tdevs1p4
        get "/1-5.html", TutorialsController, :tdevs1p5
      end
      scope "/databases_s1" do
        get "/1-2.html", TutorialsController, :tdats1p2
        get "/1-3.html", TutorialsController, :tdats1p3
        get "/1-4.html", TutorialsController, :tdats1p4
        get "/1-5.html", TutorialsController, :tdevs1p5
      end
      scope "/rawcode_s1" do
        get "/1-2.html", TutorialsController, :trs1p2
        get "/1-3.html", TutorialsController, :trs1p3
        get "/1-4.html", TutorialsController, :trs1p4
        get "/1-5.html", TutorialsController, :trs1p5
        scope "/elixir_s1" do
          get "/elixirs1p1.html", TutorialsController, :elixirs1p1
        end
      end
    end

    # Haaksploits intro pages
    scope "/haaksploits" do
      get "/xss", HaaksploitsController, :xss
      get "/scanning", HaaksploitsController, :scanning
      get "/sqlinjection", HaaksploitsController, :sqli
      get "/bruteforce", HaaksploitsController, :bruteforce
      scope "/xxs_s1" do
        get "/1-2.html", HaaksploitsController, :hxs1p2
        get "/1-3.html", HaaksploitsController, :hxs1p3
        get "/1-4.html", HaaksploitsController, :hxs1p4
        get "/1-5.html", HaaksploitsController, :hxs1p5
      end
      scope "/scanning_s1" do
        get "/1-2.html", HaaksploitsController, :hscans1p2
        get "/1-3.html", HaaksploitsController, :hscans1p3
        get "/1-4.html", HaaksploitsController, :hscans1p4
        get "/1-5.html", HaaksploitsController, :hscans1p5
      end
      scope "/sqlinjection_s1" do
        get "/1-2.html", HaaksploitsController, :hsqlis1p2
        get "/1-3.html", HaaksploitsController, :hsqlis1p3
        get "/1-4.html", HaaksploitsController, :hsqlis1p4
        get "/1-5.html", HaaksploitsController, :hsqlis1p5
      end
      scope "/bruteforce_s1" do
        get "/1-2.html", HaaksploitsController, :hbs1p2
        get "/1-3.html", HaaksploitsController, :hbs1p3
        get "/1-4.html", HaaksploitsController, :hbs1p4
        get "/1-5.html", HaaksploitsController, :hbs1p5
      end
      scope "/rawcode_s1" do
        get "/1-2.html", HaaksploitsController, :hrs1p2
        get "/1-3.html", HaaksploitsController, :hrs1p3
        get "/1-4.html", HaaksploitsController, :hrs1p4
        get "/1-5.html", HaaksploitsController, :hrs1p5
      end
    end

    # Security intro pages
    scope "/security" do
      get "/encryption", SecurityController, :encryption
      get "/servers", SecurityController, :servers
      get "/vpns", SecurityController, :vpns
      get "/securecode", SecurityController, :securecode
      scope "/encryption_s1" do
        get "/1-2.html", SecurityController, :ses1p2
        get "/1-3.html", SecurityController, :ses1p3
        get "/1-4.html", SecurityController, :ses1p4
        get "/1-5.html", SecurityController, :ses1p5
      end
      scope "/servers_s1" do
        get "/1-2.html", SecurityController, :sserves1p2
        get "/1-3.html", SecurityController, :sserves1p3
        get "/1-4.html", SecurityController, :sserves1p4
        get "/1-5.html", SecurityController, :sserves1p5
      end
      scope "/vpn_s1" do
        get "/1-2.html", SecurityController, :svs1p2
        get "/1-3.html", SecurityController, :svs1p3
        get "/1-4.html", SecurityController, :svs1p4
        get "/1-5.html", SecurityController, :svs1p5
      end
      scope "/securecode_s1" do
        get "/1-2.html", SecurityController, :sscs1p2
        get "/1-3.html", SecurityController, :sscs1p3
        get "/1-4.html", SecurityController, :sscs1p4
        get "/1-5.html", SecurityController, :sscs1p5
      end
    end

    # Unclassified intro pages
    scope "/unclassified" do
      get "/networkmodelling", UnclassifiedController, :networkmodelling
      get "/dataanalysis", UnclassifiedController, :dataanalysis
      get "/webspiders", UnclassifiedController, :webspiders
      get "/scraping", UnclassifiedController, :scraping
      scope "/networkmodelling_s1" do
        get "/1-2.html", UnclassifiedController, :unets1p2
        get "/1-3.html", UnclassifiedController, :unets1p3
        get "/1-4.html", UnclassifiedController, :unets1p4
        get "/1-5.html", UnclassifiedController, :unets1p5
      end
      scope "/dataanalysis_s1" do
        get "/1-2.html", UnclassifiedController, :udatas1p2
        get "/1-3.html", UnclassifiedController, :udatas1p3
        get "/1-4.html", UnclassifiedController, :udatas1p4
        get "/1-5.html", UnclassifiedController, :udatas1p5
      end
      scope "/webspiders_s1" do
        get "/1-2.html", UnclassifiedController, :uws1p2
        get "/1-3.html", UnclassifiedController, :uws1p3
        get "/1-4.html", UnclassifiedController, :uws1p4
        get "/1-5.html", UnclassifiedController, :uws1p5
      end
      scope "/scraping_s1" do
        get "/1-2.html", UnclassifiedController, :uss1p2
        get "/1-3.html", UnclassifiedController, :uss1p3
        get "/1-4.html", UnclassifiedController, :uss1p4
        get "/1-5.html", UnclassifiedController, :uss1p5
      end
    end

    scope "/admin", Admin, as: :admin do
      resources "/tutorials", TutorialsController
    end


  end

  # Other scopes may use custom stacks.
  # scope "/api", HaaksploitsWeb do
  #   pipe_through :api
  # end
end
```

**Comment by PeterDavidCarter** [comment]
@pedep the tutorial I'm looking at says to add `resources "/sessions", SessionController, only: [:new, :create, :delete], singleton: true` but there is no mention of adding `resources "/session", SessionController, except: [:new, :edit]`.

**Comment by chrismccord** [comment]
Your router looks okay,  is there a public location we can look at your code? It's very likely you have a missing import or some other simple issue.

**Comment by PeterDavidCarter** [comment]
Ok. Let me push the new code to my public repo. Just a minute.

**Comment by pedep** [comment]
@PeterDavidCarter Sorry, i was a bit hasty to answer. The command `mix phx.gen.xxx` usually spits out the line i quoted, so i assumed you ran a generator and forgot to copy that line to your router

**Comment by PeterDavidCarter** [comment]
It's here.

`https://github.com/PeterDavidCarter/haaweb`

**Comment by chrismccord** [comment]
I'm unable to produce your issue from the provided code. You checked in a  bad SessionView module, but one I fixed that, the project compiles just fine. I think it's possible you either handn't yet added the route to your router, maybe forgot the `singleton: true` (which you later added), or perhaps you forgot to save the router file before trying to compile the project. Can you double check? I'm confident this is not an issue on our end. Thanks!

**Comment by PeterDavidCarter** [comment]
Hhhhmmmm. Strange -- I've fixed the session_view.ex and restarted the sever process but the same error persists :/.

**Comment by chrismccord** [comment]
as a sanity check can you `mix clean` and retry?

**Comment by PeterDavidCarter** [comment]
Same error. I'm trying to see if I can recreate in my Ubuntu VM...

**Comment by pedep** [comment]
I'm on gentoo and can not recreate the error with your repo

**Comment by PeterDavidCarter** [comment]
Not an error in itself, but I'm interested to note the official Ubuntu repo still holds a beta version of Elixir that's not compatible with Phoenix. Installing current version of Elixir now...

**Comment by PeterDavidCarter** [comment]
Yeah, works fine I the Linux VM. Must be something gone awry with the Mac setup. Do you know why it would give that error message because of a machine issue, and where to begin looking? Don't worry if not as you've helped loads already.

**Comment by chrismccord** [comment]
Closing as we have not been able to reproduce and there has been no progress on the issue. Please follow up if you have more information. Thanks!
