### ISSUE TITLE
Can't run migrations

### ISSUE THREAD

**Issue by pedrocaseiro** [phoenixframework/phoenix#2739]
### Environment

* Elixir version (elixir -v): 1.6.0
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 9.3.0
* NPM version (npm -v): 5.5.1
* Operating system: Ubuntu 14.04

When running `mix ecto.migrate` I'm getting the following error:
```
[error] Could not retrieve migrated versions. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :nourish_api, NourishApi.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (ArgumentError) cannot load `"20171211160116"` as type :integer
    (elixir) lib/keyword.ex:504: Keyword.delete_key/3
    (elixir) lib/keyword.ex:501: Keyword.delete_key/3
    (elixir) lib/keyword.ex:501: Keyword.delete_key/3
    (elixir) lib/keyword.ex:493: Keyword.put/3
    lib/nourish_api/repo.ex:9: NourishApi.Repo.init/2
    (ecto) lib/ecto/repo/supervisor.ex:24: Ecto.Repo.Supervisor.runtime_config/4
    lib/nourish_api/repo.ex:2: NourishApi.Repo.config/0
    (ecto) lib/ecto/migrator.ex:316: Ecto.Migrator.verbose_schema_migration/3
    (ecto) lib/ecto/migrator.ex:157: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:83: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

The database is running inside a docker container through `docker-compose up`. I think I'm properly connected to the DB since I've had an error saying `DB doesn't exist` everytime I ran `iex -S mix` because I had a problem in my `docker-compose.yml`, but it opens fine now.

**Comment by josevalim** [comment]
As the error message says, you are tying to connect to a database that was migrated by another technology. So this database has a schema_migrations table with version as a string but Ecto requires this table to have an integer. You need to follow the steps to address the second issue.
