### ISSUE TITLE
got nil while retrieving Exception.message/1 for %Plug.TimeoutError{message: nil, plug_status: 408}

### ISSUE THREAD

**Issue by atomkirk** [phoenixframework/phoenix#2775]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0 (compiled with OTP 19)
```
* Phoenix version (mix deps):
```
* faker 0.8.0 (Hex package) (mix)
  locked at 0.8.0 (faker) 91880d7a
  ok
* ex2ms 1.5.0 (Hex package) (mix)
  locked at 1.5.0 (ex2ms) 19e27f92
  ok
* logger_file_backend 0.0.10 (Hex package) (mix)
  locked at 0.0.10 (logger_file_backend) 876f9f84
  ok
* mutex 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (mutex) 416d4ef9
  ok
* inflex 1.9.0 (Hex package) (mix)
  locked at 1.9.0 (inflex) 2bef01a8
  ok
* base64url 0.0.1 (Hex package) (rebar)
  locked at 0.0.1 (base64url) 36a90125
  ok
* mimerl 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (mimerl) 993f9b0e
  ok
* file_system 0.2.1 (Hex package) (mix)
  locked at 0.2.1 (file_system) c4bec8f1
  ok
* misc_random 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (misc_random) 95998114
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* redix 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (redix) 20986b0e
  ok
* metrics 1.0.1 (Hex package) (rebar3)
  locked at 1.0.1 (metrics) 25f094de
  ok
* unicode_util_compat 0.2.0 (Hex package) (rebar3)
  locked at 0.2.0 (unicode_util_compat) dbbccf67
  ok
* idna 5.0.2 (Hex package) (rebar3)
  locked at 5.0.2 (idna) ac203208
  ok
* gettext 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (gettext) 5e0daf4e
  ok
* logger_papertrail_backend 0.2.1 (Hex package) (mix)
  locked at 0.2.1 (logger_papertrail_backend) 12b814e3
  ok
* jose 1.8.4 (Hex package) (mix)
  locked at 1.8.4 (jose) 7946d1e5
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* geolix 0.14.0 (Hex package) (mix)
  locked at 0.14.0 (geolix) d66bafd7
  ok
* decimal 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (decimal) ad9e501e
  ok
* parallel_stream 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (parallel_stream) 4c78d3e6
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* json_web_token 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (json_web_token) 61041d56
  ok
* ssl_verify_fun 1.1.1 (Hex package) (rebar)
  locked at 1.1.1 (ssl_verify_fun) 28a4d65b
  ok
* porcelain 2.0.3 (Hex package) (mix)
  locked at 2.0.3 (porcelain) 2d77b17d
  ok
* scrivener 2.5.0 (Hex package) (mix)
  locked at 2.5.0 (scrivener) e1f78c62
  ok
* combine 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (combine) eff8224e
  ok
* elixir_make 0.4.0 (Hex package) (mix)
  locked at 0.4.0 (elixir_make) 992f38fa
  ok
* bcrypt_elixir 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (bcrypt_elixir) 7598efbe
  ok
* csv 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (csv) c66fea89
  ok
* certifi 1.2.1 (Hex package) (rebar3)
  locked at 1.2.1 (certifi) c3904f19
  ok
* hackney 1.8.6 (Hex package) (rebar3)
  locked at 1.8.6 (hackney) 21a725db
  ok
* tzdata 0.5.12 (Hex package) (mix)
  locked at 0.5.12 (tzdata) 1c17b686
  ok
* timex 3.1.24 (Hex package) (mix)
  locked at 3.1.24 (timex) d198ae97
  ok
* redix_pool 0.1.0 (Hex package) (mix)
  locked at 0.1.0 (redix_pool) 0a258761
  ok
* sweet_xml 0.6.5 (Hex package) (mix)
  locked at 0.6.5 (sweet_xml) dd9cde44
  ok
* ex_aws 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ex_aws) 8df2f96f
  ok
* ex_aws_s3 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_s3) 404e7951
  ok
* ex_aws_sns 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_sns) c51dda8c
  ok
* db_connection 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (db_connection) 89b30ca1
  ok
* httpoison 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (httpoison) 9e59f17a
  ok
* mixpanel_api_ex 0.8.4 (https://github.com/ZipBooks/mixpanel_api_ex.git) (mix)
  locked at 4270ed6
  ok
* stripity_stripe 1.6.0 (Hex package) (mix)
  locked at 1.6.0 (stripity_stripe) 9aa05206
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* pdf_generator 0.3.6 (Hex package) (mix)
  locked at 0.3.6 (pdf_generator) 3a69ddf9
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* ex_rated 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (ex_rated) a835463a
  ok
* uuid 1.1.8 (Hex package) (mix)
  locked at 1.1.8 (uuid) e22fc044
  ok
* exq 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (exq) 3feeb085
  ok
* mime 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (mime) 78adaa84
  ok
* tesla 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (tesla) e588c7e7
  ok
* google_api_storage 0.0.1 (Hex package) (mix)
  locked at 0.0.1 (google_api_storage) 061e5146
  ok
* plug 1.4.5 (Hex package) (mix)
  locked at 1.4.5 (plug) 7b138692
  ok
* bamboo 1.0.0-rc.2 (https://github.com/thoughtbot/bamboo.git) (mix)
  locked at 9783c19 (ref)
  ok
* cors_plug 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (cors_plug) c1c4fb68
  ok
* ja_serializer 0.12.0 (Hex package) (mix)
  locked at 0.12.0 (ja_serializer) ba4ec5fc
  ok
* phoenix_html 2.10.4 (Hex package) (mix)
  locked at 2.10.4 (phoenix_html) d4f99c32
  ok
* sentry 5.0.1 (Hex package) (mix)
  locked at 5.0.1 (sentry) 05b8e933
  ok
* gcp_auth 0.1.0 (https://github.com/ZipBooks/gcp_auth.git) (mix)
  locked at f6b8bb8
  ok
* phoenix 1.3.0 (https://github.com/phoenixframework/phoenix.git) (mix)
  locked at c7a6569 (ref)
  ok
* guardian 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (guardian) 21bae2a8
  ok
* phoenix_live_reload 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_live_reload) dfd31cc1
  ok
* mariaex 0.8.3 (Hex package) (mix)
  locked at 0.8.3 (mariaex) bf51ff4d
  ok
* ecto 2.1.6 (Hex package) (mix)
  locked at 2.1.6 (ecto) 29b45f39
  ok
* ja_resource 0.3.1 (Hex package) (mix)
  locked at 0.3.1 (ja_resource) d848b103
  ok
* distillery 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (distillery) eec18b2d
  ok
* exq_ui 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (exq_ui) e97e9fa9
  ok
* scrivener_ecto 1.2.2 (Hex package) (mix)
  locked at 1.2.2 (scrivener_ecto) 811e4016
  ok
* phoenix_ecto 3.2.3 (Hex package) (mix)
  locked at 3.2.3 (phoenix_ecto) 450c7498
  ok
```
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: macOS 10.12.6 Sierra

### Expected behavior

Makes it to my controller action

### Actual behavior

When I send a test Stripe webhook for `customer.subscription.deleted` it times out every time with this error:

```
** (Plug.TimeoutError) got nil while retrieving Exception.message/1 for %Plug.TimeoutError{message: nil, plug_status: 408} (expected a string)
    (plug) lib/plug/parsers/json.ex:54: Plug.Parsers.JSON.decode/2
    (plug) lib/plug/parsers.ex:242: Plug.Parsers.reduce/7
    (zipbooks) lib/zipbooks_web/endpoint.ex:1: ZB.Endpoint.plug_builder_call/2
    (zipbooks) lib/plug/debugger.ex:99: ZB.Endpoint."call (overridable 3)"/2
    (zipbooks) lib/zipbooks_web/endpoint.ex:1: ZB.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/adamkirk/Work/zb/zipbooks/phoenix-api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Here's the request:

```
POST /v2/subscriptions/stripe-webhook HTTP/1.1
Host: app.zipbooks.test
User-Agent: Stripe/1.0 (+https://stripe.com/docs/webhooks)
Content-Length: 2288
Accept: */*; q=0.5, application/xml
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Stripe-Signature: t=1519401393,v1=bfe24e6c6a4f88caab042ec2a4309c0c107c61153571836be9895c38164251bd,v0=d7c334721bec25cd6810ad0bd8dd65c7991c802d5192813453a417c1ea7b8363
X-Forwarded-For: [redacted]
X-Forwarded-Proto: https
X-Original-Host: [redacted].ngrok.io

{
  "created": 1326853478,
  "livemode": false,
  "id": "evt_00000000000000",
  "type": "customer.subscription.deleted",
  "object": "event",
  "request": null,
  "pending_webhooks": 1,
  "api_version": "2018-02-06",
  "data": {
    "object": {
      "id": "sub_00000000000000",
      "object": "subscription",
      "application_fee_percent": null,
      "billing": "charge_automatically",
      "billing_cycle_anchor": 1521992028,
      "cancel_at_period_end": false,
      "canceled_at": null,
      "created": 1519400028,
      "current_period_end": 1521992028,
      "current_period_start": 1519400028,
      "customer": "cus_00000000000000",
      "days_until_due": null,
      "discount": null,
      "ended_at": 1519398826,
      "items": {
        "object": "list",
        "data": [
          {
            "id": "si_CNTVYf0OQsnV1d",
            "object": "subscription_item",
            "created": 1519400028,
            "metadata": {
            },
            "plan": {
              "id": "smarter",
              "object": "plan",
              "amount": 1500,
              "created": 1499887558,
              "currency": "usd",
              "interval": "month",
              "interval_count": 1,
              "livemode": false,
              "metadata": {
              },
              "nickname": null,
              "product": "prod_BUfgxQ3EjfmgxY",
              "trial_period_days": null
            },
            "quantity": 1,
            "subscription": "sub_CNTVSo9PMhob2w"
          }
        ],
        "has_more": false,
        "total_count": 1,
        "url": "/v1/subscription_items?subscription=sub_CNTVSo9PMhob2w"
      },
      "livemode": false,
      "metadata": {
      },
      "plan": {
        "id": "smarter_00000000000000",
        "object": "plan",
        "amount": 1500,
        "created": 1499887558,
        "currency": "usd",
        "interval": "month",
        "interval_count": 1,
        "livemode": false,
        "metadata": {
        },
        "nickname": null,
        "product": "prod_00000000000000",
        "trial_period_days": null
      },
      "quantity": 1,
      "start": 1519400028,
      "status": "canceled",
      "tax_percent": null,
      "trial_end": 1521992028,
      "trial_start": 1519400028
    }
  }
}
```

The weird part is, it works if I try to replicate the problem with a test. So I guess this could be related to how ngrok tunnels the request, but I've been using ngrok for a long time and haven't ever seen problems.

Another weird thing is that this request works just fine every time, using the same ngrok, same endpoint, same everything, just a different request body:

```
POST /v2/subscriptions/stripe-webhook HTTP/1.1
Host: app.zipbooks.test
User-Agent: Stripe/1.0 (+https://stripe.com/docs/webhooks)
Content-Length: 727
Accept: */*; q=0.5, application/xml
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Stripe-Signature: t=1519400298,v1=3e57a7b97eebd20a9fea0fdd9dc867cce1cd7beb7b948d491cf1fdf652d7216b,v0=fc76c7e61cbf0403fd0b2bf47c2d6e7c85d2f0646a0c048f87e7e107a448b4a0
X-Forwarded-For: [redacted]
X-Forwarded-Proto: https
X-Original-Host: [redacted].ngrok.io

{
  "created": 1326853478,
  "livemode": false,
  "id": "evt_00000000000000",
  "type": "account.external_account.created",
  "object": "event",
  "request": null,
  "pending_webhooks": 1,
  "api_version": "2018-02-06",
  "data": {
    "object": {
      "id": "ba_00000000000000",
      "object": "bank_account",
      "account": "acct_00000000000000",
      "account_holder_name": "Jane Austen",
      "account_holder_type": "individual",
      "bank_name": "STRIPE TEST BANK",
      "country": "US",
      "currency": "usd",
      "default_for_currency": false,
      "fingerprint": "gnvihgsBTAJzhpDN",
      "last4": "6789",
      "metadata": {
      },
      "routing_number": "110000000",
      "status": "new"
    }
  }
}
```

I apologize if this is not a phoenix bug, but it seems like it could be so I thought I'd submit it for review.

**Comment by atomkirk** [comment]
Looks like this is actually a problem in Plug because it doesn't make it passed `12` here:

```
  plug ZB.Plug.Inspect, label: "-----------------------------------------------------12"
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison
  plug ZB.Plug.Inspect, label: "-----------------------------------------------------13"
```

Should I file this in the plug repo?

**Comment by josevalim** [comment]
Yes please!

**Comment by atomkirk** [comment]
https://github.com/elixir-plug/plug/issues/668
