### ISSUE TITLE
Phoenix v1.3.1 umbrella have no apps

### ISSUE THREAD

**Issue by Vorzious** [phoenixframework/phoenix#2790]
Phoenix v1.3.1 seems to have some undocumented changes or errors when working with umbrella. When building using docker an error is being shown.

```** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app```

The same code works well in Phoenix v1.3.0.

### Environment
* Elixir version (elixir -v):
1.6.2

* Phoenix version (mix deps):
1.3.1

* NodeJS version (node -v):
6.11.3

* NPM version (npm -v):
3.10.10

* Operating system:
OSX

### Expected behavior
A docker running a phoenix application with umbrella.

### Actual behavior
Posting the full error down here.

```
[error] GenServer Phoenix.CodeReloader.Server terminating
some_project_name_dev         | ** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app
some_project_name_dev         |     (mix) lib/mix/project.ex:486: Mix.Project.app_path/1
some_project_name_dev         |     (phoenix) lib/phoenix/code_reloader/server.ex:28: Phoenix.CodeReloader.Server.handle_call/3
some_project_name_dev         |     (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
some_project_name_dev         |     (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
some_project_name_dev         |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
some_project_name_dev         | Last message (from SomeProjectNameEndpoint.Endpoint): :check_symlinks
some_project_name_dev         | State: false
some_project_name_dev         | Client SomeProjectNameEndpoint.Endpoint is alive
some_project_name_dev         |     (stdlib) gen.erl:169: :gen.do_call/4
some_project_name_dev         |     (elixir) lib/gen_server.ex:831: GenServer.call/3
some_project_name_dev         |     (phoenix) lib/phoenix/endpoint/supervisor.ex:62: Phoenix.Endpoint.Supervisor.init/1
some_project_name_dev         |     (stdlib) supervisor.erl:294: :supervisor.init/1
some_project_name_dev         |     (stdlib) gen_server.erl:365: :gen_server.init_it/2
some_project_name_dev         |     (stdlib) gen_server.erl:333: :gen_server.init_it/6
some_project_name_dev         |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
some_project_name_dev         |
some_project_name_dev         | [info] Application some_project_name_endpoint exited: SomeProjectNameEndpoint.Application.start(:normal, []) returned an error: shutdown: failed to start child: SomeProjectNameEndpoint.Endpoint
some_project_name_dev         |     ** (EXIT) exited in: GenServer.call(Phoenix.CodeReloader.Server, :check_symlinks, :infinity)
some_project_name_dev         |         ** (EXIT) an exception was raised:
some_project_name_dev         |             ** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app
some_project_name_dev         |                 (mix) lib/mix/project.ex:486: Mix.Project.app_path/1
some_project_name_dev         |                 (phoenix) lib/phoenix/code_reloader/server.ex:28: Phoenix.CodeReloader.Server.handle_call/3
some_project_name_dev         |                 (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
some_project_name_dev         |                 (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
some_project_name_dev         |                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
some_project_name_dev         | ** (Mix) Could not start application some_project_name_endpoint: SomeProjectNameEndpoint.Application.start(:normal, []) returned an error: shutdown: failed to start child: SomeProjectNameEndpoint.Endpoint
some_project_name_dev         |     ** (EXIT) exited in: GenServer.call(Phoenix.CodeReloader.Server, :check_symlinks, :infinity)
some_project_name_dev         |         ** (EXIT) an exception was raised:
some_project_name_dev         |             ** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app
some_project_name_dev         |                 (mix) lib/mix/project.ex:486: Mix.Project.app_path/1
some_project_name_dev         |                 (phoenix) lib/phoenix/code_reloader/server.ex:28: Phoenix.CodeReloader.Server.handle_call/3
some_project_name_dev         |                 (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
some_project_name_dev         |                 (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
some_project_name_dev         |                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
some_project_name_dev exited with code 1
```

**Comment by josevalim** [comment]
Thanks. It has already been fixed, just pending a new release.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
The release should come shortly, thank you.
