### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Sjoerrdd** [phoenixframework/phoenix#2821]
* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

Elixir: Latest
Phoenix latest
NodeJS & NPM: latest
Operating System: Windows 10 x64

Hello,
I want to use MySQL instead of PostgreSQL, but I'm getting the following error when I run `mix ecto.create`

```
12:26:24.340 [error] Task #PID<0.176.0> started from #PID<0.72.0> terminating
** (UndefinedFunctionError) function Mariaex.start_link/1 is undefined (module Mariaex is not available)
    Mariaex.start_link([backoff_type: :stop, pool: DBConnection.Connection, skip_database: true, otp_app: :poll, repo: Poll.Repo, timeout: 15000, pool_timeout: 5000, adapter: Ecto.Adapters.MySQL, username: "root", password: "root", database: "poll_dev", hostname: "localhost", pool_size: 10])
    lib/ecto/adapters/mysql.ex:295: anonymous fn/2 in Ecto.Adapters.MySQL.run_query/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<9.18238389/0 in Ecto.Adapters.MySQL.run_query/2>
    Args: []
** (Mix) The database for Poll.Repo couldn't be created: an exception was raised:
    ** (UndefinedFunctionError) function Mariaex.start_link/1 is undefined (module Mariaex is not available)
        Mariaex.start_link([backoff_type: :stop, pool: DBConnection.Connection, skip_database: true, otp_app: :poll, repo: Poll.Repo, timeout: 15000, pool_timeout: 5000, adapter: Ecto.Adapters.MySQL, username: "root", password: "root", database: "poll_dev", hostname: "localhost", pool_size: 10])
        lib/ecto/adapters/mysql.ex:295: anonymous fn/2 in Ecto.Adapters.MySQL.run_query/2
        (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
You need to use :mariaex as a dependency in mix deps.get instead of :postgrex. 

Btw, please use the ElixirForum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you! :)
