### ISSUE TITLE
Test Failures on Upgrade (1.3.0 -> 1.3.2) - `Plug.Parsers`

### ISSUE THREAD

**Issue by brandonparsons** [phoenixframework/phoenix#2907]
I'm trying to upgrade from `1.3.0` to `1.3.2`, and my test suite blows up after upgrading `phoenix`, `phoenix_html` and `phoenix_livereload` packages.

I have included an example test failure below. They all look basically the same, and the nature of the failure is such that I have no idea how to bugfix!!

These tests all pass on `1.3.0`.

```
1010) test CREATE works (Frontend.Kidgenius.BulkChildCheckInControllerTest)
     test/frontend/kidgenius/controllers/bulk_child_check_in_controller_test.exs:45
     ** (FunctionClauseError) no function clause matching in Plug.Parsers.call/2

     The following arguments were given to Plug.Parsers.call/2:

         # 1
         %Plug.Conn{adapter: {Plug.Adapters.Test.Conn, :...}, assigns: %{}, before_send: [#Function<1.126528656/1 in Plug.Logger.call/2>], body_params: %{"bulk_child_check_in" => %{"checked_in_by" => nil, "child_ids" => ["02741478-d4b8-4544-8926-c237b23c1085", "bbfbe6d6-3703-42af-83ee-da5b5053a1dd"], "program_id" => "bca1866e-aebb-44ad-a686-3992472716bc"}}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "kidgenius.daycareiq.localhost", method: "POST", owner: #PID<0.13131.0>, params: %{"bulk_child_check_in" => %{"checked_in_by" => nil, "child_ids" => ["02741478-d4b8-4544-8926-c237b23c1085", "bbfbe6d6-3703-42af-83ee-da5b5053a1dd"], "program_id" => "bca1866e-aebb-44ad-a686-3992472716bc"}}, path_info: ["bulk_child_check_in"], path_params: %{}, peer: {{127, 0, 0, 1}, 111317}, port: 80, private: %{phoenix_endpoint: Frontend.Endpoint, phoenix_recycled: true, plug_skip_csrf_protection: true, start_time: -576460642888942506}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"cookie", "remember_me=SFMyNTY.g3QAAAACZAAEZGF0YXQAAAAFZAARYXV0aF90b2tlbl9leHBpcnl0AAAADWQACl9fc3RydWN0X19kAA9FbGl4aXIuRGF0ZVRpbWVkAAhjYWxlbmRhcmQAE0VsaXhpci5DYWxlbmRhci5JU09kAANkYXlhDWQABGhvdXJhAmQAC21pY3Jvc2Vjb25kaAJiAAbJLWEGZAAGbWludXRlYRVkAAVtb250aGEGZAAGc2Vjb25kYRZkAApzdGRfb2Zmc2V0YQBkAAl0aW1lX3pvbmVtAAAAB0V0Yy9VVENkAAp1dGNfb2Zmc2V0YQBkAAR5ZWFyYgAAB-JkAAl6b25lX2FiYnJtAAAAA1VUQ2QAC29wZXJhdG9yX2lkbQAAACQ4MmFhYWI2MC01NjNhLTRiNjUtYTY1ZS0yMGFkOWRlMDc2NzVkAAtzY2hlbWFfbmFtZW0AAAASdGVuYW50X2dyZWVuLWFjcmVzZAAIc3RhZmZfaWRtAAAAJDQ5ZmY0OGYzLTI2NWQtNDIwZS04NWQ3LWFjYmVhMDNhZDlhMWQAB3VzZXJfaWRtAAAAJGQ1ZTE5MTJjLTY3ZmUtNGM2ZS05NWU4LTJhMjQ2MTZhMGNjY2QABnNpZ25lZG4GAIw2zPFjAQ.qZomxwikeLuVjiFdMLrd2gJ7RQVJx2kAF878GfUxCO8"}, {"x-requested-with", "XMLHttpRequest"}, {"content-type", "multipart/mixed; boundary=plug_conn_test"}], request_path: "/bulk_child_check_in", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "2krkgiibcejdsireqo00imf3"}], scheme: :http, script_name: [], secret_key_base: "xyz", state: :unset, status: nil}

         # 2
         [length: 8000000, parsers: [Plug.Parsers.URLENCODED, Plug.Parsers.MULTIPART, Plug.Parsers.JSON], pass: ["*/*"], json_decoder: Poison]

     Attempted function clauses (showing 2 out of 2):

         def call(%{method: method, body_params: %Plug.Conn.Unfetched{}} = conn, options) when method === "PUT" or (method === "PATCH" or (method === "DELETE" or method === "POST"))
         def call(%{body_params: body_params} = conn, {_, _, query_string_length})

     code: post(conn, bulk_child_check_in_path(@endpoint, :create), %{
     stacktrace:
       (plug) lib/plug/parsers.ex:252: Plug.Parsers.call/2
       (frontend) lib/frontend/endpoint.ex:1: Frontend.Endpoint.plug_builder_call/2
       (frontend) lib/frontend/endpoint.ex:1: Frontend.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/frontend/kidgenius/controllers/bulk_child_check_in_controller_test.exs:49: (test)
```

### Environment

* Elixir version (elixir -v): 1.6.5
* Phoenix version (mix deps): 1.3.2
* NodeJS version (node -v): 9.3.0
* NPM version (npm -v): 5.6.0
* Operating system: Mac OS X

**Comment by josevalim** [comment]
Hi! This is very weird. It looks like the dependencies where updated but
the code was not recompiled. Can you try removing the _build directory and
trying again?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by brandonparsons** [comment]
* `rm -rf /_build`
* `mix deps.get`
* `mix deps.compile`

Works!!

I'm getting other failures, but they seem unrelated (and very few).

🎆
