### ISSUE TITLE
compiling phoenix from src and building docs - documentation is missing.

### ISSUE THREAD

**Issue by smorin** [phoenixframework/phoenix#2928]
In trying to work on #2925 I noticed that instructions for compiling phoenix from scratch or command for building docs are missing from the main docs [1].  The commands are probably very simple and taken for granted by folks that know better but would be good to have them in a guide for people new to the project.

There is a documentation on building the installer [2].

I'll gladly submit a pr and document them if someone can send them over.

```
$mix deps.get
$mix compile

# Install ex_doc instructions here: https://github.com/elixir-lang/ex_doc
# mix escript.install hex ex_doc

$ ex_doc "PROJECT_NAME" "PROJECT_VERSION" path/to/project/ebin -m "PROJECT_MODULE" -u "https://github.com/GITHUB_USER/GITHUB_REPO" -l path/to/logo.png
```

- [1] https://hexdocs.pm/phoenix/overview.html
- [2] https://github.com/phoenixframework/phoenix/blob/master/installer/README.md

**Comment by smorin** [comment]
Build using what's in the readme.  (next need to see if that is an actual error)
$ mix deps.get 
$ mix compile
$ MIX_ENV=docs mix docs



smorin$ MIX_ENV=docs mix docs
===> Compiling ranch
==> jason
Compiling 7 files (.ex)
Generated jason app
warning: String.strip/1 is deprecated, use String.trim/1
  /Users/smorin/code/elixirscratch/phoenix/deps/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
  lib/poison/encoder.ex:173

Generated poison app
==> earmark
Compiling 3 files (.erl)
Compiling 24 files (.ex)
warning: Enum.partition/2 is deprecated, use Enum.split_with/2
  lib/earmark/parser.ex:23

Generated earmark app
==> ex_doc
Compiling 15 files (.ex)
Generated ex_doc app
==> phoenix_pubsub
Compiling 12 files (.ex)
Generated phoenix_pubsub app
===> Compiling cowlib
===> Compiling cowboy
==> mime
Compiling 2 files (.ex)
Generated mime app
==> plug
Compiling 1 file (.erl)
Compiling 48 files (.ex)
Generated plug app
==> inch_ex
Compiling 15 files (.ex)
warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1
  lib/inch_ex/reporter/local.ex:33

warning: String.strip/1 is deprecated, use String.trim/1
  lib/inch_ex/git.ex:36

warning: String.strip/1 is deprecated, use String.trim/1
  lib/inch_ex/git.ex:37

warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  lib/inch_ex/reporter/remote.ex:25

warning: Enum.filter_map/3 is deprecated, use Enum.filter/2 + Enum.map/2 or for comprehensions
  lib/inch_ex/docs/retriever.ex:96

warning: Atom.to_char_list/1 is deprecated, use Atom.to_charlist/1
  lib/inch_ex/docs/retriever.ex:133

warning: Enum.filter_map/3 is deprecated, use Enum.filter/2 + Enum.map/2 or for comprehensions
  lib/inch_ex/docs/retriever.ex:202

Generated inch_ex app
==> phoenix
Compiling 66 files (.ex)
Generated phoenix app
Docs successfully generated.
View them at "doc/index.html".
Docs successfully generated.
View them at "doc/Phoenix.epub".
sh: documentation: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! phoenix@1.3.0 docs: `documentation build js/phoenix.js -f html -o ../doc/js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phoenix@1.3.0 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/smorin/.npm/_logs/2018-06-25T22_51_32_319Z-debug.log

**Comment by smorin** [comment]
@chrismccord you might know the answer to this.  I was trying to document how to build Phoenix and I was trying to figure out the commands to also build the installer. Question 1) What is the right series of commands to build a release for Phoenix, it's docs and the installer?

$ cd installer
$ mix deps.get
$ mix compile

But get the following error which appears to reference a file on someone's specific machine setup.

smorin-local:phoenix smorin$ cd installer/
smorin-local:installer smorin$ ls
README.md	lib		mix.exs		templates	test
smorin-local:installer smorin$ mix deps.get 
All dependencies up to date
smorin-local:installer smorin$ mix compile
Compiling 10 files (.ex)
warning: redefining module Mix.Tasks.Local.Phx (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Mix.Tasks.Local.Phx.beam)
  lib/mix/tasks/local.phx.ex:1

warning: redefining module Phx.New.Generator (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Phx.New.Generator.beam)
  lib/phx_new/generator.ex:1

warning: redefining module Mix.Tasks.Phx.New (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Mix.Tasks.Phx.New.beam)
  lib/mix/tasks/phx.new.ex:1

warning: redefining module Phx.New.Single (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Phx.New.Single.beam)
  lib/phx_new/single.ex:1

warning: redefining module Phx.New.Project (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Phx.New.Project.beam)
  lib/phx_new/project.ex:1

warning: redefining module Mix.Tasks.Phx.New.Ecto (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Mix.Tasks.Phx.New.Ecto.beam)
  lib/mix/tasks/phx.new.ecto.ex:1

warning: redefining module Phx.New.Ecto (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Phx.New.Ecto.beam)
  lib/phx_new/ecto.ex:1

warning: redefining module Mix.Tasks.Phx.New.Web (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Mix.Tasks.Phx.New.Web.beam)
  lib/mix/tasks/phx.new.web.ex:1

warning: redefining module Phx.New.Umbrella (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Phx.New.Umbrella.beam)
  lib/phx_new/umbrella.ex:1

warning: redefining module Phx.New.Web (current version loaded from /Users/smorin/.mix/archives/phx_new/phx_new/ebin/Elixir.Phx.New.Web.beam)
  lib/phx_new/web.ex:1


== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory
    (elixir) lib/file.ex:310: File.read!/1
    lib/phx_new/generator.ex:28: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:24: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)

**Comment by smorin** [comment]
Updated in #2934 which should close this issue
