### ISSUE TITLE
Cannot install archive from master clone.

### ISSUE THREAD

**Issue by ijunaid8989** [phoenixframework/phoenix#2938]
* Elixir version (elixir -v): 1.6.6
* Phoenix version (mix deps): Phoenix v1.4.0-dev
* NodeJS version (node -v): v8.11.3
* NPM version (npm -v): 6.1.0
* Operating system:

### Expected behavior
I cloned the repo and cd to `phoenix` and then cd into `installer/` directory, and ran these commands as
```
MIX_ENV=prod mix do archive.build, archive.install
```
It should create and install archive but
### Actual behavior
```
junaid@junaid-Inspiron-N5050:~$ git clone git@github.com:phoenixframework/phoenix.git
Cloning into 'phoenix'...
remote: Counting objects: 37317, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 37317 (delta 32), reused 65 (delta 29), pack-reused 37233
Receiving objects: 100% (37317/37317), 9.32 MiB | 618.00 KiB/s, done.
Resolving deltas: 100% (24089/24089), done.
Checking connectivity... done.
junaid@junaid-Inspiron-N5050:~$ cd phoenix/
junaid@junaid-Inspiron-N5050:~/phoenix$ ls
assets              config           installer          LICENSE.md        mix.exs       priv        test
CHANGELOG.md        CONTRIBUTING.md  ISSUE_TEMPLATE.md  logo.png          mix.lock      README.md
CODE_OF_CONDUCT.md  guides           lib                mix-cowboy1.lock  package.json  RELEASE.md
junaid@junaid-Inspiron-N5050:~/phoenix$ cd installer/
junaid@junaid-Inspiron-N5050:~/phoenix/installer$ MIX_ENV=prod mix do archive.build, archive.install
Compiling 10 files (.ex)
warning: redefining module Mix.Tasks.Phx.New.Web (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Mix.Tasks.Phx.New.Web.beam)
  lib/mix/tasks/phx.new.web.ex:1

warning: redefining module Mix.Tasks.Phx.New (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Mix.Tasks.Phx.New.beam)
  lib/mix/tasks/phx.new.ex:1

warning: redefining module Mix.Tasks.Phx.New.Ecto (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Mix.Tasks.Phx.New.Ecto.beam)
  lib/mix/tasks/phx.new.ecto.ex:1

warning: redefining module Mix.Tasks.Local.Phx (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Mix.Tasks.Local.Phx.beam)
  lib/mix/tasks/local.phx.ex:1

warning: redefining module Phx.New.Ecto (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Phx.New.Ecto.beam)
  lib/phx_new/ecto.ex:1

warning: redefining module Phx.New.Generator (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Phx.New.Generator.beam)
  lib/phx_new/generator.ex:1

warning: redefining module Phx.New.Project (current version loaded from /home/junaid/.asdf/installs/elixir/1.6.5/.mix/archives/phx_new-1.3.3/phx_new-1.3.3/ebin/Elixir.Phx.New.Project.beam)
  lib/phx_new/project.ex:1


== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory
    (elixir) lib/file.ex:310: File.read!/1
    lib/phx_new/generator.ex:28: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:24: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)
```

**Comment by josevalim** [comment]
You need to uninstall your current archive before compiling the new one. We
should probably add a check at the top of the installer mix.exs.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
Also, as discussed on slack, be sure to delete the `phoenix` archive you accidentally installed:

```
$ mix archive.uninstall phoenix
$ mix archive.uninstall phx_new
```

Thanks!

**Comment by ijunaid8989** [comment]
@chrismccord Yes , thanks, I got confused with that error `** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory` :)
