### ISSUE TITLE
Phoenix.js: Wrong message format for heartbeat message 

### ISSUE THREAD

**Issue by gtors** [phoenixframework/phoenix#2947]
[phoenix.js:750](https://github.com/phoenixframework/phoenix/blob/v1.3/assets/js/phoenix.js#L750)
```
 this.push({topic: "phoenix", event: "heartbeat", payload: {}, ref: this.pendingHeartbeatRef})
```

[phoenix.js:716](https://github.com/phoenixframework/phoenix/blob/v1.3/assets/js/phoenix.js#L716)
```
  push(data){
    let {topic, event, payload, ref, join_ref} = data
    let callback = () => {
      this.encode(data, result => {
        this.conn.send(result)
      })
    }
   // ... other code
}
```

[phoenix.js:498](https://github.com/phoenixframework/phoenix/blob/v1.3/assets/js/phoenix.js#L498) JSON.stringify will return serialized array
```
let Serializer = {
  encode(msg, callback){
    let payload = [
      msg.join_ref, msg.ref, msg.topic, msg.event, msg.payload
    ]
     // ---  HERE --->
    return callback(JSON.stringify(payload))
},
```

And this lead to:

```
[error] Ranch protocol #PID<0.376.0> of listener WsWeb.Endpoint.HTTP (cowboy_protocol) terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Phoenix.Socket.Message.from_map!/1
            (phoenix) lib/phoenix/socket/message.ex:22: Phoenix.Socket.Message.from_map!([nil, "51", "phoenix", "heartbeat", %{}])
            (phoenix) lib/phoenix/transports/websocket.ex:121: Phoenix.Transports.WebSocket.ws_handle/3
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:77: Phoenix.Endpoint.CowboyWebSocket.websocket_handle/3
            (cowboy) /home/user/.src/websocket_phoenix_app/ws/deps/cowboy/src/cowboy_websocket.erl:588: :cowboy_websocket.handler_call/7
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:49: Phoenix.Endpoint.CowboyWebSocket.resume/3
            (cowboy) /home/user/.src/websocket_phoenix_app/ws/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 21)
```
* Phoenix version (mix deps): 
```
* file_system 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (file_system) fd4dc3af
  ok
* gettext 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (gettext) 40a2b8ce
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (mime) 5e8d45a3
  ok
* plug 1.6.1 (Hex package) (mix)
  locked at 1.6.1 (plug) c62fe762
  ok
* phoenix_html 2.11.2 (Hex package) (mix)
  locked at 2.11.2 (phoenix_html) 86ebd768
  ok
* phoenix 1.3.3 (Hex package) (mix)
  locked at 1.3.3 (phoenix) bafb5fa4
  ok
* phoenix_live_reload 1.1.5 (Hex package) (mix)
  locked at 1.1.5 (phoenix_live_reload) 8d4c9b1e
  ok
```
* NodeJS version (node -v):
```
v10.5.0
```
* NPM version (npm -v):
```
6.1.0
```
* Operating system:
```
Manjaro Linux
```

### Expected behavior

Serialized message is suitable for  `Phoenix.Socket.Message.from_map!`

### Actual behavior

Serialized message is:  `[null,"7","phoenix","heartbeat",{}]`

**Comment by chrismccord** [comment]
The only place we use `Phoenix.Socket.Message.from_map!` is the v1 serializer, `https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/serializers/v1_json_serializer.ex#L30`, but Phoenix 1.3.3 and the linked source is the V2 client, so I'm not sure how you're triggering this error. Is it possible you have non-js clients connecting?  Is there anything else in your setup that is out of the ordinary? Thanks!

**Comment by gtors** [comment]
Seems the bug was on my side . I recreated the project from scratch and the bug disappeared.

Sorry for wasting your time.

**Comment by chrismccord** [comment]
No worries! Glad you got things sorted out! :)
