### ISSUE TITLE
Phoenix.Router.NoRouteError after generating new project

### ISSUE THREAD

**Issue by benonymus** [phoenixframework/phoenix#2980]
### Environment

* Elixir version (elixir -v): Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.6.6 (compiled with OTP 19)

* Phoenix version (mix deps): connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (gettext) 40a2b8ce
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.5.0 (Hex package) (mix)
  locked at 1.5.0 (decimal) b0433a36
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* db_connection 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (db_connection) 89b30ca1
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (mime) 5e8d45a3
  ok
* plug 1.6.1 (Hex package) (mix)
  locked at 1.6.1 (plug) c62fe762
  ok
* phoenix 1.3.3 (Hex package) (mix)
  locked at 1.3.3 (phoenix) bafb5fa4
  ok
* postgrex 0.13.5 (Hex package) (mix)
  locked at 0.13.5 (postgrex) 3d931aba
  ok
* ecto 2.2.10 (Hex package) (mix)
  locked at 2.2.10 (ecto) e7366dc8
  ok
* phoenix_ecto 3.3.0 (Hex package) (mix)
  locked at 3.3.0 (phoenix_ecto) 702f6e16
  ok

* NodeJS version (node -v): v10.7.0

* NPM version (npm -v): 
* Operating system: Ubuntu

### Expected behavior
server running 

### Actual behavior
error
Running MyApiWeb.Endpoint with Cowboy using http://0.0.0.0:4000
[info] GET /
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET / (MyApiWeb.Router)
    (myApi) lib/myApi_web/router.ex:1: MyApiWeb.Router.__match_route__/4
    (myApi) lib/phoenix/router.ex:307: MyApiWeb.Router.call/2
    (myApi) lib/myApi_web/endpoint.ex:1: MyApiWeb.Endpoint.plug_builder_call/2
    (myApi) lib/plug/debugger.ex:122: MyApiWeb.Endpoint."call (overridable 3)"/2
    (myApi) lib/myApi_web/endpoint.ex:1: MyApiWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /home/bencejanostoth/Projects/myApi/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
What can be done to fix it?

**Comment by benonymus** [comment]
my bad need to add a path to the router
