### ISSUE TITLE
Update ExDoc to 0.19.1 (better syntax highlighting)

### ISSUE THREAD

**Issue by tmbb** [phoenixframework/phoenix#3028]
I'm the author of Makeup (used by ExDoc 0.19.x). Obvious conflict of interest is obvious

**Comment by chrismccord** [comment]
Can you send a PR? Thanks!

**Comment by tmbb** [comment]
I'm getting the weirdest error while compiling Phoenix on windows and it' getting late here. I'll send a PR tomorrow or the day after. For the record, the error is this:

```
== Compilation error in file installer/lib/phx_new/single.ex ==
** (File.Error) could not read file "c:/Users/chris/oss/phoenix/installer/templates/phx_assets/app.css": no such file or directory
    (elixir) lib/file.ex:319: File.read!/1
    lib/phx_new/generator.ex:28: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:24: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    installer/lib/phx_new/single.ex:1: Phx.New.Single (module)
```
