### ISSUE TITLE
Compilation error while installing phx_new 1.4.0-rc.1

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix#3094]
Elixir: 1.7.3 with erlang 21

Trying to install the new rc as posted [here](https://elixirforum.com/t/phoenix-1-4-0-rc-0-released/17182/66?u=tcoopman) fails:

```bash
> mix archive.install hex phx_new 1.4.0-rc.1                                                                                                                     
Resolving Hex dependencies...
Dependency resolution completed:
New:
  phx_new 1.4.0-rc.1
* Getting phx_new (Hex package)
All dependencies up to date
Compiling 10 files (.ex)
warning: redefining module Mix.Tasks.Local.Phx (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Mix.Tasks.Local.Phx.beam)
  lib/mix/tasks/local.phx.ex:1

warning: redefining module Mix.Tasks.Phx.New.Ecto (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Mix.Tasks.Phx.New.Ecto.beam)
  lib/mix/tasks/phx.new.ecto.ex:1

warning: redefining module Mix.Tasks.Phx.New (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Mix.Tasks.Phx.New.beam)
  lib/mix/tasks/phx.new.ex:1

warning: redefining module Mix.Tasks.Phx.New.Web (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Mix.Tasks.Phx.New.Web.beam)
  lib/mix/tasks/phx.new.web.ex:1

warning: redefining module Phx.New.Ecto (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Phx.New.Ecto.beam)
  lib/phx_new/ecto.ex:1

warning: redefining module Phx.New.Generator (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Phx.New.Generator.beam)
  lib/phx_new/generator.ex:1

warning: redefining module Phx.New.Project (current version loaded from /home/thomas/.asdf/installs/elixir/1.7.3-otp-21/.mix/archives/phx_new-1.4.0-rc.0/phx_new-1.4.0-rc.0/ebin/Elixir.Phx.New.Project.beam)
  lib/phx_new/project.ex:1


== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/tmp/mix-local-installer-fetcher-cSS5SQ/deps/phx_new/templates/phx_ecto/repo.ex": no such file or directory
    (elixir) lib/file.ex:319: File.read!/1
    lib/phx_new/generator.ex:30: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:26: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)
```

**Comment by razz-matazz** [comment]
Hello,

I had the same issue because I didn't properly uninstalled RC0 before. There are a lot of references to 1.4.0-rc.0 in your output.

**Comment by chenxsan** [comment]
Run `mix archive.uninstall phx_new-1.4.0-rc.0` first.

**Comment by tcoopman** [comment]
Thanks, that indeed fixed it. Replied on the forum so the information is there as well.
