### ISSUE TITLE
Can't install latest phx_new command

### ISSUE THREAD

**Issue by yordis** [phoenixframework/phoenix#3220]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.2 (compiled with Erlang/OTP 19)
```
* Operating system: MacOS

### Expected behavior

Trying to install the latest Phoenix Hex command.

### Actual behavior

```shell
mix archive.install hex phx_new
```

```text
== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory
    (elixir) lib/file.ex:319: File.read!/1
    lib/phx_new/generator.ex:28: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:24: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)
```

**Comment by yordis** [comment]
cc: @chrismcg it seems that it is pointing to your machine path.

**Comment by yordis** [comment]
I removed everything from my current machine and install it again. Everything is good.
