### ISSUE TITLE
Phoenix & Nuxt.JS

### ISSUE THREAD

**Issue by Sjoerrdd** [phoenixframework/phoenix#3236]
### Environment

* Elixir version (elixir -v): 1.8
* Phoenix version (mix deps): 1.4
* NodeJS version (node -v): 10
* NPM version (npm -v): 6.4.1
* Operating system: Windows 10

### Expected behavior
I'm using Nuxt.JS, with Phoenix as backend. 
When I run `mix phx.server`, I would like to start the Adonis server as well, but that doesn't work.

(When I run `npm start` manually, Nuxt.JS works fine)

My watcher:
``` 
watchers: [npm: ["run", "dev", cd: Path.expand("../", __DIR__)]]
```

### Actual behavior
I got the following error:

```
[warn] Phoenix is unable to create symlinks. Phoenix' code reloader will run considerably faster if symlinks are allowed. On Windows, the lack of symlinks may even cause empty assets to be served. Luckily, you can address this issue by starting your Windows terminal at least once with "Run as Administrator" and then running your Phoenix application.
[info] Running ProjectWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000
[error] Task #PID<0.452.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.453.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.454.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.455.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[info] Running ProjectWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000
[error] Task #PID<0.581.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.582.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.583.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.584.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[info] Running ProjectWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000
[error] Task #PID<0.710.0> started from ReProjectWebtaurantWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.711.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.712.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.713.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[info] Running ProjectWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000
[error] Task #PID<0.839.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.840.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.841.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[error] Task #PID<0.842.0> started from ProjectWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, 'd:/Program Files/nodejs/npm.cmd'}, [{:cd, "d:/Sites/project"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["run", "dev"]}])
    (elixir) lib/system.ex:641: System.cmd/3
    (phoenix) lib/phoenix/endpoint/watcher.ex:15: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "dev"], [cd: "d:/Sites/project"]]
[info] Application project exited: shutdown
```

**Comment by OvermindDL1** [comment]
> ** (stop) :eacces

I.E. the executable you are trying to launch doesn't exist, don't have access, or is not an executable, of which it is referencing `d:/Program Files/nodejs/npm.cmd`.  Do note, npm has issues on windows, you might need to launch it using an executable rather than a cmd file as a cmd file is not an executable format (it gets hoisted into something else, you need to hoist that yourself.

Also this is not a phoenix issue, rather it is an npm issue, you should ask these on the ElixirForums instead (of which I 'think' this question has already been answered on there, though not in relation to nuxt.js but rather npm).  :-)
