### ISSUE TITLE
Presence: the Collectable protocol is deprecated for non-empty lists.

### ISSUE THREAD

**Issue by mRamiroGonzalez** [phoenixframework/phoenix#3268]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): phoenix 1.4.0
* NodeJS version (node -v): v11.6.0
* NPM version (npm -v): 6.5.0-next.0
* Operating system:  Ubuntu 18.04.1 LTS

### Expected behavior
No warning message when using Presence and following the documentation

### Actual behavior
I am  using Presence to track active users and i have encountered a warning message when **more than one user** is connected. 
The warning seems to come from the `Presence.track/3` function. Here is my code:
```
  def join("room:lobby", _, socket) do
    send(self(), :after_join)
    {:ok, socket}
  end

  def handle_info(:after_join, socket) do
    push(socket, "presence_state", Presence.list(socket))
    {:ok, _} = Presence.track(socket, socket.assigns.user, %{online_at: :os.system_time(:milli_seconds)})
    {:noreply, socket}
  end
```
Nothing crashes but the log is filled with this: 

```
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (phoenix_pubsub) lib/phoenix/tracker/state.ex:380: Phoenix.Tracker.State.merge_deltas/2
  (phoenix_pubsub) lib/phoenix/tracker/delta_generation.ex:34: Phoenix.Tracker.DeltaGeneration.do_push/4
  (phoenix_pubsub) lib/phoenix/tracker/shard.ex:519: Phoenix.Tracker.Shard.push_delta_generation/2
  (phoenix_pubsub) lib/phoenix/tracker/shard.ex:169: Phoenix.Tracker.Shard.handle_info/2
  (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
  (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by Gazler** [comment]
Thanks for raising. This is actually an issue on phoenix_pubsub https://github.com/phoenixframework/phoenix_pubsub/issues/120

I Will leave this open until it is merged over there.

**Comment by themondays** [comment]
@mRamiroGonzalez 
`{:phoenix_pubsub, "~> 1.1.2"}`
