### ISSUE TITLE
`errors_on/1` raises when `unsafe_validate_unique/4` fails validation

### ISSUE THREAD

**Issue by amarraja** [phoenixframework/phoenix#3282]
### Environment

* Elixir version (elixir -v): Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): phoenix 1.4.1

### Expected behavior

Given a schema:

```elixir
defmodule User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name, :string
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> unsafe_validate_unique(:name, Repo)
  end
end
```

I can test the behaviour of `unsafe_validate_unique/4` like this:

```elixir
assert %{name: _} = errors_on(changeset)
```

### Actual behavior

An exception is raised from `errors_on/1` in the generated `DataCase` module

```
** (ArgumentError) cannot convert the given list to a string.

     To be converted to a string, a list must contain only:

       * strings
       * integers representing Unicode codepoints
       * or a list containing one of these three elements

     Please check the given list or call inspect/1 to get the list representation, got:

     [:name]

     code: assert %{name: _} = errors_on(changeset)
     stacktrace:
       (elixir) lib/list.ex:826: List.to_string/1
       (ecto_validate) test/support/data_case.ex:55: anonymous fn/2 in EctoValidate.DataCase.errors_on/1
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/changeset.ex:2700: anonymous fn/3 in Ecto.Changeset.merge_error_keys/3
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/changeset.ex:2694: Ecto.Changeset.traverse_errors/2
       test/ecto_validate_web/models/users_index_test.exs:73: (test)
```

I've done some investigation, and can see that `unsafe_validate_unique/4` always wraps fields as a list, so you get something like: 

```
errors: [name: {"message", [validation: :unsafe_unique, fields: [:name]]}]
```

And the `to_string` call blows up when given the `fields` list.

A fix was quite easy, by changing `errors_on/1` to take the head if it sees a list like so:

```elixir
def errors_on(changeset) do
  Ecto.Changeset.traverse_errors(changeset, fn {message, opts} ->
    Enum.reduce(opts, message, fn {key, value}, acc ->
      value =
        case value do
          [value | _] -> value
          _ -> value
        end

      String.replace(acc, "%{#{key}}", to_string(value))
    end)
  end)
end
```

However, I am not sure if this is correct. I.e is the issue with the generated `errors_on` or is Ecto's `unsafe_validate_unique/4` breaking a contract by sending a list?

**Comment by wojtekmach** [comment]
I think this is the same issue as in https://github.com/phoenixframework/phoenix/pull/3204

**Comment by amarraja** [comment]
@wojtekmach exactly the same! I only searched issues, not prs - my bad. Will close this one off.
