### ISSUE TITLE
Error handling when route is called from hackney

### ISSUE THREAD

**Issue by nulian** [phoenixframework/phoenix#3317]
When route is called from curl/browser to an endpoint that doesn't have like a matching function header. You get the normal error like.

```
[debug] ** (Phoenix.ActionClauseError) no function clause matching in NewPhoenixWeb.PageController.index/2

The following arguments were given to NewPhoenixWeb.PageController.index/2:

    # 1
    %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: ...

    # 2
    %{}

    (new_phoenix) lib/new_phoenix_web/controllers/page_controller.ex:4: NewPhoenixWeb.PageController.index(%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: ...
```

But when you use hackney to send through like httpoison to send a request the error returns unreadable. Like the example below.

```
[info] Converted error {:badfun, %Phoenix.ActionClauseError{args: [%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: [...], arity: 2, clauses: nil, function: :index, kind: nil, module: NewPhoenixWeb.PageController}} to 500 response
[error] #PID<0.440.0> running NewPhoenixWeb.Endpoint (connection #PID<0.439.0>, stream id 1) terminated
Server: sandbox-clone-test.betty5.test:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (BadFunctionError) expected a function, got: %Phoenix.ActionClauseError{args: [%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: ...}
        (elixir) lib/exception.ex:1062: anonymous fn/2 in FunctionClauseError.blame/3
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/exception.ex:1061: FunctionClauseError.blame/3
        (phoenix) lib/phoenix/exceptions.ex:59: Phoenix.ActionClauseError.blame/2
        (plug) lib/plug/debugger.ex:197: Plug.Debugger.render/6
        (plug) lib/plug/debugger.ex:147: Plug.Debugger.__catch__/5
```

**Comment by chrismccord** [comment]
@alexgaribay This one is up for grabs if you want to dive into it this week

**Comment by alexgaribay** [comment]
I’ll take a look 👍

**Comment by josevalim** [comment]
Hi @nulian, can you please provide a small app that reproduces the issue? It will make it much easier for us to find out what is going wrong, thank you!

**Comment by nulian** [comment]
https://github.com/nulian/request_bug

go to http://localhost:4000 in the browser for the first error.

iex -S mix phx.server

:hackney.request(:get, "http://localhost:4000/")

For the second error.

**Comment by samu** [comment]
I had the same problem when using [superagent](https://github.com/visionmedia/superagent) to call the api. I have a controller function like this:

```elixir
def create(conn, %{"email" => email, "password" => pass}) do
...
end
```

I call it with superagent. Note how i'm not setting `accept` header and using an invalid payload:

```
    await superagent
      .post(`${baseUrl}/api/sessions`)
      .send({});
```

I get the ugly exception:

```
Request: POST /api/sessions
** (exit) an exception was raised:
    ** (BadFunctionError) expected a function, got: %Phoenix.ActionClauseError
...
```

I get a better error message if i do either of the following:

Setting `accept` header:

```
    await superagent
      .post(`${baseUrl}/api/sessions`)
      .set("accept", "*/*")
      .send({});
```

Setting proper payload:

```
    await superagent
      .post(`${baseUrl}/api/sessions`)
      .send({ email: "email", password: "password" });
```
