### ISSUE TITLE
ThermostatLive: [error] GenServer #PID<0.505.0> terminating: (RuntimeError) boom: 

### ISSUE THREAD

**Issue by loretoparisi** [phoenixframework/phoenix#3355]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

* Phoenix version (mix deps):
```
* parse_trans 3.3.0 (Hex package) (rebar3)
  locked at 3.3.0 (parse_trans) 09765507
  ok
* mimerl 1.2.0 (Hex package) (rebar3)
  locked at 1.2.0 (mimerl) 67e2d3f5
  ok
* file_system 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (file_system) fd4dc3af
  ok
* metrics 1.0.1 (Hex package) (rebar3)
  locked at 1.0.1 (metrics) 25f094de
  ok
* unicode_util_compat 0.4.1 (Hex package) (rebar3)
  locked at 0.4.1 (unicode_util_compat) d869e4c6
  ok
* idna 6.0.0 (Hex package) (rebar3)
  locked at 6.0.0 (idna) 689c46cb
  ok
* gettext 0.16.1 (Hex package) (mix)
  locked at 0.16.1 (gettext) e2130b25
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* ssl_verify_fun 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (ssl_verify_fun) f0eafff8
  ok
* certifi 2.5.1 (Hex package) (rebar3)
  locked at 2.5.1 (certifi) 867ce347
  ok
* hackney 1.15.1 (Hex package) (rebar3)
  locked at 1.15.1 (hackney) 9f8f471c
  ok
* tzdata 0.5.20 (Hex package) (mix)
  locked at 0.5.20 (tzdata) 304b9e98
  ok
* calendar 0.17.5 (Hex package) (mix)
  locked at 0.17.5 (calendar) 0ff5b09a
  ok
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
  ok
* cowlib 2.7.3 (Hex package) (rebar3)
  locked at 2.7.3 (cowlib) a7ffcd09
  ok
* cowboy 2.6.3 (Hex package) (rebar3)
  locked at 2.6.3 (cowboy) 99aa50e9
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* plug_crypto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (plug_crypto) 18e49317
  ok
* plug 1.8.0 (Hex package) (mix)
  locked at 1.8.0 (plug) 9d2685cb
  ok
* phoenix_html 2.13.2 (Hex package) (mix)
  locked at 2.13.2 (phoenix_html) f5d27c9b
  ok
* plug_cowboy 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (plug_cowboy) 6055f168
  ok
* phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (phoenix) 8eed4a64
  ok
* phoenix_live_view 0.1.0 (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
  locked at 96aeb3b
  ok
* phoenix_live_reload 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix_live_reload) 3bb31a9f
  ok
```

* NodeJS version (node -v):
```
v10.1.0
```

* NPM version (npm -v):
```
6.4.1
```

* Operating system:
macOS 10.14.1

### Expected behavior
- 

### Actual behavior
```
[error] GenServer #PID<0.504.0> terminating
** (RuntimeError) boom
    (hello) lib/hello_web/live/thermostat_live.ex:34: HelloWeb.ThermostatLive.handle_event/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:63: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "1", payload: %{"event" => "inc", "type" => "click", "value" => ""}, ref: "9", topic: "lv:phx-pvR5BFFm"}
State: %{children_ids: %{"phx-pvR5BFFmHelloWeb.WeatherLive" => #PID<0.505.0>}, children_pids: %{#PID<0.505.0> => "phx-pvR5BFFmHelloWeb.WeatherLive"}, fingerprints: {168586866744442977888281150962077987754, %{}}, join_ref: "1", serializer: Phoenix.Socket.V2.JSONSerializer, socket: %Phoenix.LiveView.Socket{assigns: %{mode: :heating, time: {{2019, 4, 6}, {21, 8, 37}}, val: 75}, changed: %{}, connected?: true, endpoint: HelloWeb.Endpoint, id: "phx-pvR5BFFm", parent_pid: nil, private: %{assigned_new: {%{}, []}}, root_fingerprint: 168586866744442977888281150962077987754, stopped: nil}, topic: "lv:phx-pvR5BFFm", transport_pid: #PID<0.500.0>, view: HelloWeb.ThermostatLive}
[error] GenServer #PID<0.505.0> terminating
** (RuntimeError) boom
    (hello) lib/hello_web/live/thermostat_live.ex:34: HelloWeb.ThermostatLive.handle_event/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:63: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.2432616708.2096103428.55631>, :process, #PID<0.504.0>, {%RuntimeError{message: "boom"}, [{HelloWeb.ThermostatLive, :handle_event, 3, [file: 'lib/hello_web/live/thermostat_live.ex', line: 34]}, {Phoenix.LiveView.Channel, :handle_info, 2, [file: 'lib/phoenix_live_view/channel.ex', line: 63]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: %{children_ids: %{}, children_pids: %{}, fingerprints: {223920549219078265140812054774812208418, %{}}, join_ref: "2", serializer: Phoenix.Socket.V2.JSONSerializer, socket: %Phoenix.LiveView.Socket{assigns: %{location: "Austin", weather: "🌦 +21°C\n"}, changed: %{}, connected?: true, endpoint: HelloWeb.Endpoint, id: "phx-pvR5BFFmHelloWeb.WeatherLive", parent_pid: #PID<0.504.0>, private: %{assigned_new: {%{}, []}}, root_fingerprint: 223920549219078265140812054774812208418, stopped: nil}, topic: "lv:phx-pvR5BFFmHelloWeb.WeatherLive", transport_pid: #PID<0.500.0>, view: HelloWeb.WeatherLive}
```

**Comment by chrismccord** [comment]
The boom is an intentional error in the examples app to show error recovery after an exceptio
