### ISSUE TITLE
Error when accepting websocket req in release mode after 1.4 -> 1.4.3 upgrade

### ISSUE THREAD

**Issue by ivanovv** [phoenixframework/phoenix#3363]
### Expected behavior
I've updated almost vanila 1.4 app (basically websockets listener for JS errrors that are sent to PaperTrail) to 1.4.3 by changing one line in `mix.exs`
`{:phoenix, "~> 1.4.0"},`  -> `{:phoenix, "~> 1.4.3"}, `
and expect the app to work 

### Actual behavior
`mix phx.server` works fine, but when app started as a release with 
```
bin/webinar start
```
I get this error:
```
14:46:04.322 [error] #PID<0.1356.0> running WebinarWeb.Endpoint (connection #PID<0.1355.0>, stream id 1) terminated
Server: app.example.com:80 (http)
Request: GET /socket/websocket?broadcast=uuid&subs_secret_key=sekret&subs_id=1&vsn=2.0.0
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in WebinarWeb.Endpoint.__handler__/2
        (webinar) lib/webinar_web/endpoint.ex:1: WebinarWeb.Endpoint.__handler__(["socket", "websocket"], [])
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:18: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/vic/code/webinar/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/vic/code/webinar/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/vic/code/webinar/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
* Phoenix version (mix deps):
```
* gettext 0.16.1 (Hex package) (mix)
  locked at 0.16.1 (gettext) e2130b25
  ok
* logger_papertrail_backend 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (logger_papertrail_backend) 06185bda
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
  ok
* cowlib 2.7.3 (Hex package) (rebar3)
  locked at 2.7.3 (cowlib) a7ffcd09
  ok
* cowboy 2.6.3 (Hex package) (rebar3)
  locked at 2.6.3 (cowboy) 99aa50e9
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* artificery 0.4.1 (Hex package) (mix)
  locked at 0.4.1 (artificery) 90b1fced
  ok
* distillery 2.0.12 (Hex package) (mix)
  locked at 2.0.12 (distillery) 6e78fe04
  ok
* plug_crypto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (plug_crypto) 18e49317
  ok
* plug 1.8.0 (Hex package) (mix)
  locked at 1.8.0 (plug) 9d2685cb
  ok
* phoenix_html 2.13.1 (Hex package) (mix)
  locked at 2.13.1 (phoenix_html) fa8f034b
  ok
* plug_cowboy 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (plug_cowboy) 6055f168
  ok
* phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (phoenix) 8eed4a64
  ok
```

* nginx location:
```
location /phoenix/ {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://phoenix/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```
* NodeJS version (node -v):
`not using` 
* NPM version (npm -v):
`not using`
* Operating system:
`macOS 10.10.5`

**Comment by chrismccord** [comment]
How did you build the release? Have you tried rebuilding? Thanks!

**Comment by ivanovv** [comment]
Ugh, sorry for not mentioning that
Build by distillery machinery using this command
```
MIX_ENV=prod mix release --env=prod
```
> Have you tried rebuilding? 

I've tried removing dependencies, wiping the whole _build directory, and all the usual stuff you try to do before you open an issue on GH. I'm almost sure it is some sort of a stupid mistake in config or something, but I can't figure it out.


So let's go through the stack, shall we?
`        (cowboy) /Users/vic/code/webinar/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
`
```erl
%% @todo
%-spec execute(cowboy_req:req(), #state{}, cowboy_middleware:env(), [module()])
%	-> ok.
-spec execute(_, _, _) -> _.
execute(_, _, []) ->
	ok; %% @todo Maybe error reason should differ here and there.
execute(Req, Env, [Middleware|Tail]) ->
	case Middleware:execute(Req, Env) of
		{ok, Req2, Env2} ->
			execute(Req2, Env2, Tail);
		{suspend, Module, Function, Args} ->
			proc_lib:hibernate(?MODULE, resume, [Env, Tail, Module, Function, Args]);
		{stop, _Req2} ->
			ok %% @todo Maybe error reason should differ here and there.
	end.
```
Ok, so line 296 is `	case Middleware:execute(Req, Env) of`

`(cowboy) /Users/vic/code/webinar/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2` is 
```erl
-spec execute(Req, Env) -> {ok, Req, Env}
	when Req::cowboy_req:req(), Env::cowboy_middleware:env().
execute(Req, Env=#{handler := Handler, handler_opts := HandlerOpts}) ->
	try Handler:init(Req, HandlerOpts) of
		{ok, Req2, State} ->
			Result = terminate(normal, Req2, State, Handler),
			{ok, Req2, Env#{result => Result}};
		{Mod, Req2, State} ->
			Mod:upgrade(Req2, Env, Handler, State);
		{Mod, Req2, State, Opts} ->
			Mod:upgrade(Req2, Env, Handler, State, Opts)
	catch Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		terminate({crash, Class, Reason}, Req, HandlerOpts, Handler),
		erlang:raise(Class, Reason, StackTrace)
	end.
```
and line 41 is `try Handler:init(Req, HandlerOpts) of`

So  we arrive at `deps/phoenix/lib/phoenix/endpoint/cowboy2_handler.ex@17`
```elixir
  def init(req, {endpoint, opts}) do
    conn = @connection.conn(req)
    try do
      case endpoint.__handler__(conn, opts) do
        {:websocket, conn, handler, opts} ->
```

```
iex(webinar@127.0.0.1)3> WebinarWeb.Endpoint.__handler__(["socket", "websocket"], [])
** (FunctionClauseError) no function clause matching in WebinarWeb.Endpoint.__handler__/2    
    
    The following arguments were given to WebinarWeb.Endpoint.__handler__/2:
    
        # 1
        ["socket", "websocket"]
    
        # 2
        []
    
    Attempted function clauses (showing 1 out of 1):
    
        def __handler__(-%{path_info: path} = conn-, opts)
    
    (webinar) lib/webinar_web/endpoint.ex:1: WebinarWeb.Endpoint.__handler__/2
```

ugh, I'm lost at this point. I can't understand how `conn, opts` end up being  `["socket", "websocket"], []`

**Comment by ivanovv** [comment]
Ok, guys, I'm really really sorry, it turned out there was a version discrepancy between the build host and the server running the app :-/

As something positive from this issue I can only suggest including that info (build host env/ runtime host env OR just a check if the ERTS is included or not) in the issue template (though I guess for the vast majority of projects out there `include_erts` would be `true`)

Thank you!
