### ISSUE TITLE
`mix phx.server` in app created from master phx_new archive does not start due to Phoenix.PubSub

### ISSUE THREAD

**Issue by richardkmichael** [phoenixframework/phoenix#3523]
I am fairly new to Phoenix and unsure if I should file a problem against the master branch.  Also, from reading the beta9 version of the forthcoming Programming Phoenix book, I am aware Phoenix.PubSub is being re-worked. So apologies if this is an unnecessary report.

I successfully followed the instructions from the README to generate a `phx_new` archive from the git repo, on the master branch.  (Aside, it would be helpful if the `phx_new` archive was named with a SHA1, if not on a release branch/tag because at the moment the version shown by `mix archive`  is still 1.4.0; potentially confusing.)

I generated an application (the app name includes the SHA1 of the tip of master at the time), installed dependencies and created the database without problems.

However, `mix phx.server` fails with an error about `Phoenix.PubSub` not implementing `child_spec/1`.

Here is the `mix phx.server` error, but I have also included all my steps further below:

```shell
 $ mix phx.server
[info] Application hello_4c454a5744c exited: exited in: Hello4c454a5744c.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Phoenix.PubSub was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: Phoenix.PubSub,
      start: {Phoenix.PubSub, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

            (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/supervisor.ex:615: Supervisor.init/2
            (elixir) lib/supervisor.ex:564: Supervisor.start_link/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
** (Mix) Could not start application hello_4c454a5744c: exited in: Hello4c454a5744c.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Phoenix.PubSub was given as a child to a supervisor
but it does not implement child_spec/1.


If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: Phoenix.PubSub,
      start: {Phoenix.PubSub, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

            (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/supervisor.ex:615: Supervisor.init/2
            (elixir) lib/supervisor.ex:564: Supervisor.start_link/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
```

Here are my full steps, from the beginning with `git clone ...`:

```shell
 $ git clone https://github.com/phoenixframework/phoenix
Cloning into 'phoenix'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 42604 (delta 0), reused 0 (delta 0), pack-reused 42603
Receiving objects: 100% (42604/42604), 11.01 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (27866/27866), done.

 $ cd phoenix/installer/
/Users/testuser/phoenix/installer

 master= $ MIX_ENV=prod mix do archive.build, archive.install
Could not find Hex, which is needed to build dependency :ex_doc
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]
* creating /Users/testuser/.mix/archives/hex-0.20.1
Compiling 10 files (.ex)
Generated phx_new app
Generated archive "phx_new-1.4.0.ez" with MIX_ENV=prod
Are you sure you want to install "phx_new-1.4.0.ez"? [Yn]
* creating /Users/testuser/.mix/archives/phx_new-1.4.0

 master %= $ mix archive
* hex-0.20.1
* phx_new-1.4.0
Archives installed at: /Users/testuser/.mix/archives

 master %= $ cd ../..

 $ mix phx.new hello_4c454a5744c
* creating hello_4c454a5744c/config/config.exs
* creating hello_4c454a5744c/config/dev.exs
* creating hello_4c454a5744c/config/prod.exs
* creating hello_4c454a5744c/config/prod.secret.exs
* creating hello_4c454a5744c/config/test.exs
* creating hello_4c454a5744c/lib/hello_4c454a5744c/application.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/channels/user_socket.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/views/error_helpers.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/views/error_view.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/endpoint.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/router.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web.ex
* creating hello_4c454a5744c/mix.exs
* creating hello_4c454a5744c/README.md
* creating hello_4c454a5744c/.formatter.exs
* creating hello_4c454a5744c/.gitignore
* creating hello_4c454a5744c/test/support/channel_case.ex
* creating hello_4c454a5744c/test/support/conn_case.ex
* creating hello_4c454a5744c/test/test_helper.exs
* creating hello_4c454a5744c/test/hello_4c454a5744c_web/views/error_view_test.exs
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/gettext.ex
* creating hello_4c454a5744c/priv/gettext/en/LC_MESSAGES/errors.po
* creating hello_4c454a5744c/priv/gettext/errors.pot
* creating hello_4c454a5744c/lib/hello_4c454a5744c/repo.ex
* creating hello_4c454a5744c/priv/repo/migrations/.formatter.exs
* creating hello_4c454a5744c/priv/repo/seeds.exs
* creating hello_4c454a5744c/test/support/data_case.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/controllers/page_controller.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/templates/layout/app.html.eex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/templates/page/index.html.eex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/views/layout_view.ex
* creating hello_4c454a5744c/lib/hello_4c454a5744c_web/views/page_view.ex
* creating hello_4c454a5744c/test/hello_4c454a5744c_web/controllers/page_controller_test.exs
* creating hello_4c454a5744c/test/hello_4c454a5744c_web/views/layout_view_test.exs
* creating hello_4c454a5744c/test/hello_4c454a5744c_web/views/page_view_test.exs
* creating hello_4c454a5744c/assets/webpack.config.js
* creating hello_4c454a5744c/assets/.babelrc
* creating hello_4c454a5744c/assets/js/app.js
* creating hello_4c454a5744c/assets/js/socket.js
* creating hello_4c454a5744c/assets/package.json
* creating hello_4c454a5744c/assets/css/app.css
* creating hello_4c454a5744c/assets/static/favicon.ico
* creating hello_4c454a5744c/assets/css/phoenix.css
* creating hello_4c454a5744c/assets/static/images/phoenix.png
* creating hello_4c454a5744c/assets/static/robots.txt

Fetch and install dependencies? [Yn] Y
* running mix deps.get
* running mix deps.compile
* running cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development

We are almost there! The following steps are missing:

    $ cd hello_4c454a5744c

Then configure your database in config/dev.exs and run:

    $ mix ecto.create

Start your Phoenix app with:

    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server

 $ cd hello_4c454a5744c/
/Users/testuser/hello_4c454a5744c

 $ mix ecto.create
Compiling 13 files (.ex)
Generated hello_4c454a5744c app
The database for Hello4c454a5744c.Repo has been created

 $ mix phx.server
[info] Application hello_4c454a5744c exited: exited in: Hello4c454a5744c.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Phoenix.PubSub was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: Phoenix.PubSub,
      start: {Phoenix.PubSub, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

            (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/supervisor.ex:615: Supervisor.init/2
            (elixir) lib/supervisor.ex:564: Supervisor.start_link/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
** (Mix) Could not start application hello_4c454a5744c: exited in: Hello4c454a5744c.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Phoenix.PubSub was given as a child to a supervisor
but it does not implement child_spec/1.


If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: Phoenix.PubSub,
      start: {Phoenix.PubSub, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

            (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/supervisor.ex:615: Supervisor.init/2
            (elixir) lib/supervisor.ex:564: Supervisor.start_link/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4

 $
```

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

* Phoenix version (mix deps):

```
* file_system 0.2.7 (Hex package) (mix)
  locked at 0.2.7 (file_system) e6f7f155
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.17.0 (Hex package) (mix)
  locked at 0.17.0 (gettext) abe21542
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (telemetry) 8339bee3
  ok
* decimal 1.8.0 (Hex package) (mix)
  locked at 1.8.0 (decimal) ca462e0d
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* db_connection 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (db_connection) a51e8a2e
  ok
* ecto 3.1.7 (Hex package) (mix)
  locked at 3.1.7 (ecto) fa21d06e
  ok
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
  ok
* cowlib 2.7.3 (Hex package) (rebar3)
  locked at 2.7.3 (cowlib) a7ffcd09
  ok
* cowboy 2.6.3 (Hex package) (rebar3)
  locked at 2.6.3 (cowboy) 99aa50e9
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* postgrex 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (postgrex) dd534916
  ok
* ecto_sql 3.1.6 (Hex package) (mix)
  locked at 3.1.6 (ecto_sql) 1e80e30d
  ok
* plug_crypto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (plug_crypto) 18e49317
  ok
* plug 1.8.3 (Hex package) (mix)
  locked at 1.8.3 (plug) 12d5f979
  ok
* phoenix_html 2.13.3 (Hex package) (mix)
  locked at 2.13.3 (phoenix_html) 850e292f
  ok
* plug_cowboy 2.1.0 (Hex package) (mix)
  locked at 2.1.0 (plug_cowboy) b7576815
  ok
* phoenix 1.4.9 (Hex package) (mix)
  locked at 1.4.9 (phoenix) 746d098e
  ok
* phoenix_live_reload 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix_live_reload) 274a4b07
  ok
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
  ok
```

* NodeJS version (node -v): `v12.8.0`
* NPM version (npm -v): `6.10.3`
* Operating system: `macOS 10.14.6`

### Expected behavior

Phoenix server should start.

### Actual behavior

Phoenix server does not start.

**Comment by TiagoCoelhoB** [comment]
did you find a solution?

**Comment by chrismccord** [comment]
Do you get this error when you install the archive from hex, via `mix archive.install hex phx_new` ?

**Comment by TiagoCoelhoB** [comment]
yes

**Comment by TiagoCoelhoB** [comment]
in fact, every package i install with command mix archive.install 1.4.*, when execute mix ecto.create returns the error reported

**Comment by chrismccord** [comment]
Can you include the exact commands you ran? You can check with `history` on the command line. Thanks!

**Comment by TiagoCoelhoB** [comment]
mix archive.uninstall phx_new-1.4.0 (or phx_new-1.4.*)
mix archive.install hex phx_new 1.4.3 ( or 1.4.*)
mix phx.new myProject
cd myProject
mix ecto.create

**Comment by chrismccord** [comment]
can you try latest? Uninstall again, then `mix archive.install hex phx_new` or `mix archive.install hex phx_new 1.4.9`

**Comment by TiagoCoelhoB** [comment]
nop, still the same. but it's working in you machine right? let me try install a new elixir version and test. Maybe the package manager is "doing stuff"

**Comment by richardkmichael** [comment]
@chrismccord 

I followed the second set of instructions in `installer/README` to build and install locally using `MIX_ENV=prod mix do archive.build, archive.install` -- I did not install the archive using `hex` (as in the first instruction stanza), no.

FWIW, I just tried `cd installer && mix phx.new foo --dev`, then the usual setup (`ecto.create`, etc.) and `mix phx.server` *does* work and start on `:4000` as expected.

I'm on the tip of master and I see no changes since I reported this issue, sorry if I've missed something.

**Comment by TiagoCoelhoB** [comment]
> nop, still the same. but it's working in you machine right? let me try install a new elixir version and test. Maybe the package manager is "doing stuff"

Apparently the problem is on package manager.
if you re-install elixir everything works just fine,
sorry

**Comment by chrismccord** [comment]
@richardkmichael I will double check our current master local build, but if you are wanting to get started with phoenix the hex archive is the way to go. Master is our unstable active dev branch

**Comment by richardkmichael** [comment]
@chrismccord Sure will do; as I mentioned, I wasn't sure if you'd want a report against master. So if not, just close this.  It struck me as a bit odd that the archive built from master doesn't work, while the in-tree app  generated with`--dev` does.

Thanks for the quick response, cheers!
