### ISSUE TITLE
Running `mix` returns warning :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead

### ISSUE THREAD

**Issue by dopatraman** [phoenixframework/phoenix#3578]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.0-dev (553b2b2) (compiled with Erlang/OTP 22)
```
* Phoenix version (mix deps): 1.4.7
* NodeJS version (node -v): 9.5.0
* NPM version (npm -v): 5.6.0
* Operating system: Ubuntu 16.04

### Expected behavior
I want to run mix without any warnings.

### Actual behavior
I ran mix ecto.setup on a machine twice -- the setup worked properly but now everytime I enter the mix command in my terminal, I see this output:
```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0-dev) lib/supervisor.ex:612: Supervisor.init/2
  (elixir 1.10.0-dev) lib/supervisor.ex:564: Supervisor.start_link/2
  (phoenix 1.4.8) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0-dev) lib/supervisor.ex:612: Supervisor.init/2
  (elixir 1.10.0-dev) lib/supervisor.ex:564: Supervisor.start_link/2
  (phoenix 1.4.8) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0-dev) lib/supervisor.ex:612: Supervisor.init/2
  (elixir 1.10.0-dev) lib/supervisor.ex:564: Supervisor.start_link/2
  (phoenix 1.4.8) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
@delameko is correct. :)

**Comment by nicklayb** [comment]
Now that Elixir 1.10 has been released officially, can we expect a fix for this warning in Phoenix 1.4? It's not mendatory of course, and as delameko said it's only a warning but it's pretty noisy when reading tests output

**Comment by wojtekmach** [comment]
I believe the warning is gone in the latest phoenix (v1.4.16), can you check?

**Comment by nicklayb** [comment]
I still see it, even in the latest commit on 1.4 branch, which is 22 days ago, it still uses the :simple_one_for_one strategy at [here](https://github.com/phoenixframework/phoenix/blob/70cb048aa86643967bbae53dd9e93fa5425dfb3e/lib/phoenix/socket/pool_supervisor.ex#L45)

**Comment by josevalim** [comment]
You can use the master branch. V1.5 is coming. Unfortunately we can’t depend on it on V1.4 as we support earlier Elixir versions.
