### ISSUE TITLE
[phx.gen.live] Tests don't pass when generated with utc_datetime field

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix#3819]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.1
* NodeJS version (node -v): 13.9.0
* NPM version (npm -v): 6.13.7
* Operating system: MacOS 10.15.4

### Steps to recreate

1. Run the following in a phoenix app generated with `--live`
    ```
    $ mix phx.gen.live Schedules Appointment appointments title starts_at:utc_datetime
    ```
2. Update the router with the steps printed out in the directions.
3. Run the tests.

### Expected behavior

Tests should pass

### Actual behavior

I get the following test failures.

```
demo_live_app master % mix test

12:23:28.007 [info]  == Running 20200501182152 DemoLiveApp.Repo.Migrations.CreateAppointments.change/0 forward

12:23:28.009 [info]  create table appointments

12:23:28.021 [info]  == Migrated 20200501182152 in 0.0s
...

  1) test Index updates appointment in listing (DemoLiveAppWeb.AppointmentLiveTest)
     test/demo_live_app_web/live/appointment_live_test.exs:54
     ** (ArgumentError) could not find non-disabled input, select or textarea with name "appointment[starts_at]" within:

         <input name="_method" type="hidden" value="put"/>
         <input name="_csrf_token" type="hidden" value="WXFUAWUqLF1EAxkCEgIWLw4NKBQ0UR4870m9TpXk4WTLW2QWzcGgEfPk"/>
         <input id="appointment_title" name="appointment[title]" type="text" value="some title"/>
         <select id="appointment_starts_at_year" name="appointment[starts_at][year]"><option value="2015">2015</option><option value="2016">2016</option><option value="2017">2017</option><option value="2018">2018</option><option value="2019">2019</option><option value="2020">2020</option><option value="2021">2021</option><option value="2022">2022</option><option value="2023">2023</option><option value="2024">2024</option><option value="2025">2025</option></select>
         <select id="appointment_starts_at_month" name="appointment[starts_at][month]"><option value="1">January</option><option value="2">February</option><option value="3">March</option><option value="4" selected="selected">April</option><option value="5">May</option><option value="6">June</option><option value="7">July</option><option value="8">August</option><option value="9">September</option><option value="10">October</option><option value="11">November</option><option value="12">December</option></select>
         <select id="appointment_starts_at_day" name="appointment[starts_at][day]"><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17" selected="selected">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option></select>
         <select id="appointment_starts_at_hour" name="appointment[starts_at][hour]"><option value="0">00</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14" selected="selected">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option></select>
         <select id="appointment_starts_at_minute" name="appointment[starts_at][minute]"><option value="0" selected="selected">00</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option><option value="32">32</option><option value="33">33</option><option value="34">34</option><option value="35">35</option><option value="36">36</option><option value="37">37</option><option value="38">38</option><option value="39">39</option><option value="40">40</option><option value="41">41</option><option value="42">42</option><option value="43">43</option><option value="44">44</option><option value="45">45</option><option value="46">46</option><option value="47">47</option><option value="48">48</option><option value="49">49</option><option value="50">50</option><option value="51">51</option><option value="52">52</option><option value="53">53</option><option value="54">54</option><option value="55">55</option><option value="56">56</option><option value="57">57</option><option value="58">58</option><option value="59">59</option></select>

     code: |> render_change() =~ "can&apos;t be blank"
     stacktrace:
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/test/live_view_test.ex:858: Phoenix.LiveViewTest.call/2
       test/demo_live_app_web/live/appointment_live_test.exs:64: (test)

..

  2) test Index saves new appointment (DemoLiveAppWeb.AppointmentLiveTest)
     test/demo_live_app_web/live/appointment_live_test.exs:32
     ** (ArgumentError) could not find non-disabled input, select or textarea with name "appointment[starts_at]" within:

         <input name="_csrf_token" type="hidden" value="HjNnMDYzHioHWyQ5DSc9ACY7PhcdVQIXsP4oCxxc5juqbCERCRy_w9FZ"/>
         <input id="appointment_title" name="appointment[title]" type="text"/>
         <select id="appointment_starts_at_year" name="appointment[starts_at][year]"><option value="2015">2015</option><option value="2016">2016</option><option value="2017">2017</option><option value="2018">2018</option><option value="2019">2019</option><option value="2020">2020</option><option value="2021">2021</option><option value="2022">2022</option><option value="2023">2023</option><option value="2024">2024</option><option value="2025">2025</option></select>
         <select id="appointment_starts_at_month" name="appointment[starts_at][month]"><option value="1">January</option><option value="2">February</option><option value="3">March</option><option value="4">April</option><option value="5">May</option><option value="6">June</option><option value="7">July</option><option value="8">August</option><option value="9">September</option><option value="10">October</option><option value="11">November</option><option value="12">December</option></select>
         <select id="appointment_starts_at_day" name="appointment[starts_at][day]"><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option></select>
         <select id="appointment_starts_at_hour" name="appointment[starts_at][hour]"><option value="0">00</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option></select>
         <select id="appointment_starts_at_minute" name="appointment[starts_at][minute]"><option value="0">00</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option><option value="32">32</option><option value="33">33</option><option value="34">34</option><option value="35">35</option><option value="36">36</option><option value="37">37</option><option value="38">38</option><option value="39">39</option><option value="40">40</option><option value="41">41</option><option value="42">42</option><option value="43">43</option><option value="44">44</option><option value="45">45</option><option value="46">46</option><option value="47">47</option><option value="48">48</option><option value="49">49</option><option value="50">50</option><option value="51">51</option><option value="52">52</option><option value="53">53</option><option value="54">54</option><option value="55">55</option><option value="56">56</option><option value="57">57</option><option value="58">58</option><option value="59">59</option></select>

     code: |> render_change() =~ "can&apos;t be blank"
     stacktrace:
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/test/live_view_test.ex:858: Phoenix.LiveViewTest.call/2
       test/demo_live_app_web/live/appointment_live_test.exs:42: (test)



  3) test Show updates appointment within modal (DemoLiveAppWeb.AppointmentLiveTest)
     test/demo_live_app_web/live/appointment_live_test.exs:94
     ** (ArgumentError) could not find non-disabled input, select or textarea with name "appointment[starts_at]" within:

         <input name="_method" type="hidden" value="put"/>
         <input name="_csrf_token" type="hidden" value="dwANABUqCAJ5JyM5FwtCHAQVPF9RGRIL5aLpMSXi-COxM20RrfNjekHs"/>
         <input id="appointment_title" name="appointment[title]" type="text" value="some title"/>
         <select id="appointment_starts_at_year" name="appointment[starts_at][year]"><option value="2015">2015</option><option value="2016">2016</option><option value="2017">2017</option><option value="2018">2018</option><option value="2019">2019</option><option value="2020">2020</option><option value="2021">2021</option><option value="2022">2022</option><option value="2023">2023</option><option value="2024">2024</option><option value="2025">2025</option></select>
         <select id="appointment_starts_at_month" name="appointment[starts_at][month]"><option value="1">January</option><option value="2">February</option><option value="3">March</option><option value="4" selected="selected">April</option><option value="5">May</option><option value="6">June</option><option value="7">July</option><option value="8">August</option><option value="9">September</option><option value="10">October</option><option value="11">November</option><option value="12">December</option></select>
         <select id="appointment_starts_at_day" name="appointment[starts_at][day]"><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17" selected="selected">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option></select>
         <select id="appointment_starts_at_hour" name="appointment[starts_at][hour]"><option value="0">00</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14" selected="selected">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option></select>
         <select id="appointment_starts_at_minute" name="appointment[starts_at][minute]"><option value="0" selected="selected">00</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option><option value="32">32</option><option value="33">33</option><option value="34">34</option><option value="35">35</option><option value="36">36</option><option value="37">37</option><option value="38">38</option><option value="39">39</option><option value="40">40</option><option value="41">41</option><option value="42">42</option><option value="43">43</option><option value="44">44</option><option value="45">45</option><option value="46">46</option><option value="47">47</option><option value="48">48</option><option value="49">49</option><option value="50">50</option><option value="51">51</option><option value="52">52</option><option value="53">53</option><option value="54">54</option><option value="55">55</option><option value="56">56</option><option value="57">57</option><option value="58">58</option><option value="59">59</option></select>

     code: |> render_change() =~ "can&apos;t be blank"
     stacktrace:
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/test/live_view_test.ex:858: Phoenix.LiveViewTest.call/2
       test/demo_live_app_web/live/appointment_live_test.exs:104: (test)

.........

Finished in 0.4 seconds
17 tests, 3 failures
```

I'm guessing the LiveViewTest helpers aren't working quite right with the `datetime_select`.

**Comment by josevalim** [comment]
You are correct this is an issue in LiveViewTest. I have pushed some improvements to Phoenix but the rest needs to be done in LV. So I will transfer this issue there.
