### ISSUE TITLE
`phx.new --live --no-ecto --no-dashboard` broken for v1.5.2

### ISSUE THREAD

**Issue by sigwinch28** [phoenixframework/phoenix#3861]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.5.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 22)
```
* Phoenix version (mix deps):
```
* file_system 0.2.8 (Hex package) (mix)
  locked at 0.2.8 (file_system) 97a3b6f8
  ok
* gettext 0.18.0 (Hex package) (mix)
  locked at 0.18.0 (gettext) c3f850be
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 451d8527
  ok
* telemetry 0.4.1 (Hex package) (rebar3)
  locked at 0.4.1 (telemetry) 4738382e
  ok
* telemetry_metrics 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (telemetry_metrics) 31225e6c
  ok
* telemetry_poller 0.5.0 (Hex package) (rebar3)
  locked at 0.5.0 (telemetry_poller) 69e4e8e6
  ok
* jason 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (jason) b659b857
  ok
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) c52d948c
  ok
* cowlib 2.8.0 (Hex package) (rebar3)
  locked at 2.8.0 (cowlib) 79f954a7
  ok
* cowboy 2.7.0 (Hex package) (rebar3)
  locked at 2.7.0 (cowboy) 04fd8c6a
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 6cbe761d
  ok
* plug_crypto 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (plug_crypto) 6b8b608f
  ok
* plug 1.10.1 (Hex package) (mix)
  locked at 1.10.1 (plug) b5cd5225
  ok
* phoenix_html 2.14.2 (Hex package) (mix)
  locked at 2.14.2 (phoenix_html) 58061c8d
  ok
* plug_cowboy 2.2.1 (Hex package) (mix)
  locked at 2.2.1 (plug_cowboy) 3b43de24
  ok
* phoenix 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (phoenix) 30470223
  ok
* phoenix_live_view 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (phoenix_live_view) 585321e9
  ok
* phoenix_live_reload 1.2.2 (Hex package) (mix)
  locked at 1.2.2 (phoenix_live_reload) a3dec3d2
  ok
```
* phx-new version (mix phx.new --version): `Phoenix v1.5.2`
* NodeJS version (node -v): `v10.19.0`
* NPM version (npm -v):  `6.13.4`
* Operating system:
```
Distributor ID: NixOS
Description:    NixOS 20.03 (Markhor)
Release:        20.03.1885.885a6658073
Codename:       markhor
```

### Expected behavior

The default "live dependency" page at http://localhost:4000/ works 

### Actual behavior

The page is broken, reloading every few seconds:

```
[error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.start_link/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/channel.ex:12: Phoenix.LiveView.Channel.start_link({MyappWeb.Endpoint, {#PID<0.535.0>, #Reference<0.3049453891.3911450627.100905>}})
        (elixir 1.10.1) lib/dynamic_supervisor.ex:692: DynamicSupervisor.start_child/3
        (elixir 1.10.1) lib/dynamic_supervisor.ex:678: DynamicSupervisor.handle_start_child/2
        (stdlib 3.10) gen_server.erl:661: :gen_server.try_handle_call/4
        (stdlib 3.10) gen_server.erl:690: :gen_server.handle_msg/6
        (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Steps to reproduce

1. Use `phx-new` v1.5.2
2. Create app with `mix phx.new myapp --live --no-ecto --no-dashboard`
3. Install deps, `cd myapp; mix phx.server`
4. Browse to `http://localhost:4000`

### Workaround

It looks like this has been fixed in a recent version of `phoenix_live_view`: https://github.com/phoenixframework/phoenix_live_view/commit/d0be2818a92d0af906102be7d72001dbe521c340

I managed to get my application working by manually overriding the `phoenix_live_view` dependency in `mix.exs`:
```
{:phoenix_live_view, override: true, github: "phoenixframework/phoenix_live_view", ref: "d0be2818a92d0af906102be7d72001dbe521c340"}
```

### Log

```
joe@ryuko /t/tmp.3ZOz2MwlXW> mix phx.new myapp --no-dashboard --no-ecto --live
* creating myapp/config/config.exs
* creating myapp/config/dev.exs
* creating myapp/config/prod.exs
* creating myapp/config/prod.secret.exs
* creating myapp/config/test.exs
* creating myapp/lib/myapp/application.ex
* creating myapp/lib/myapp.ex
* creating myapp/lib/myapp_web/channels/user_socket.ex
* creating myapp/lib/myapp_web/views/error_helpers.ex
* creating myapp/lib/myapp_web/views/error_view.ex
* creating myapp/lib/myapp_web/endpoint.ex
* creating myapp/lib/myapp_web/router.ex
* creating myapp/lib/myapp_web/telemetry.ex
* creating myapp/lib/myapp_web.ex
* creating myapp/mix.exs
* creating myapp/README.md
* creating myapp/.formatter.exs
* creating myapp/.gitignore
* creating myapp/test/support/channel_case.ex
* creating myapp/test/support/conn_case.ex
* creating myapp/test/test_helper.exs
* creating myapp/test/myapp_web/views/error_view_test.exs
* creating myapp/lib/myapp_web/templates/layout/root.html.leex
* creating myapp/lib/myapp_web/templates/layout/app.html.eex
* creating myapp/lib/myapp_web/templates/layout/live.html.leex
* creating myapp/lib/myapp_web/views/layout_view.ex
* creating myapp/lib/myapp_web/live/page_live.ex
* creating myapp/lib/myapp_web/live/page_live.html.leex
* creating myapp/test/myapp_web/views/layout_view_test.exs
* creating myapp/test/myapp_web/live/page_live_test.exs
* creating myapp/lib/myapp_web/gettext.ex
* creating myapp/priv/gettext/en/LC_MESSAGES/errors.po
* creating myapp/priv/gettext/errors.pot
* creating myapp/assets/webpack.config.js
* creating myapp/assets/.babelrc
* creating myapp/assets/js/app.js
* creating myapp/assets/css/app.scss
* creating myapp/assets/package.json
* creating myapp/assets/static/favicon.ico
* creating myapp/assets/css/phoenix.css
* creating myapp/assets/static/images/phoenix.png
* creating myapp/assets/static/robots.txt

Fetch and install dependencies? [Yn] y
* running mix deps.get
* running mix deps.compile
* running cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development

We are almost there! The following steps are missing:

    $ cd myapp

Start your Phoenix app with:

    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server

joe@ryuko /t/tmp.3ZOz2MwlXW> cd myapp
joe@ryuko /t/t/myapp> mix phx.server
Compiling 12 files (.ex)
Generated myapp app
warning: this clause cannot match because a previous clause at line 1 always matches
  lib/list/chars.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/list/chars.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/list/chars.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/list/chars.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/list/chars.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/collectable.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/enum.ex:1

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 3 always matches
  lib/string/chars.ex:3

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 1 always matches
  lib/iex/info.ex:1

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

warning: this clause cannot match because a previous clause at line 6 always matches
  lib/inspect.ex:6

[info] Running MyappWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
[info] Access MyappWeb.Endpoint at http://localhost:4000

webpack is watching the files…

Hash: 53a25f5464cd86129974
Version: webpack 4.41.5
Time: 1106ms
Built at: 21/05/2020 22:01:33
                Asset       Size  Chunks                   Chunk Names
       ../css/app.css     13 KiB     app  [emitted]        app
   ../css/app.css.map   16.6 KiB     app  [emitted] [dev]  app
       ../favicon.ico   1.23 KiB          [emitted]        
../images/phoenix.png   13.6 KiB          [emitted]        
        ../robots.txt  202 bytes          [emitted]        
               app.js    139 KiB     app  [emitted]        app
           app.js.map    267 KiB     app  [emitted] [dev]  app
Entrypoint app = ../css/app.css app.js ../css/app.css.map app.js.map
[0] multi ./js/app.js 28 bytes {app} [built]
[../deps/phoenix/priv/static/phoenix.js] 35.6 KiB {app} [built]
[../deps/phoenix_html/priv/static/phoenix_html.js] 2.21 KiB {app} [built]
[../deps/phoenix_live_view/priv/static/phoenix_live_view.js] 81.7 KiB {app} [built]
[./css/app.scss] 39 bytes {app} [built]
[./js/app.js] 1.28 KiB {app} [built]
    + 4 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!css/app.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js!./css/phoenix.css] 10.4 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./css/app.scss] 2.06 KiB {mini-css-extract-plugin} [built]
        + 2 hidden modules
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 17ms
[info] CONNECTED TO Phoenix.LiveView.Socket in 134µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "JBQeWAoDVksVPwwUMSQeAmMSXQkHQ3dzhLO0rU93lGHKBpXPVj6gvz07", "vsn" => "2.0.0"}
[error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.start_link/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/channel.ex:12: Phoenix.LiveView.Channel.start_link({MyappWeb.Endpoint, {#PID<0.535.0>, #Reference<0.3049453891.3911450627.100905>}})
        (elixir 1.10.1) lib/dynamic_supervisor.ex:692: DynamicSupervisor.start_child/3
        (elixir 1.10.1) lib/dynamic_supervisor.ex:678: DynamicSupervisor.handle_start_child/2
        (stdlib 3.10) gen_server.erl:661: :gen_server.try_handle_call/4
        (stdlib 3.10) gen_server.erl:690: :gen_server.handle_msg/6
        (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by noorfahmy** [comment]
this error also happens if you generate standard project : mix phx.new <project_name>. Live Dashboard keeps on looping. Your workaround works for me so far.
`[error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.start_link/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/channel.ex:12: Phoenix.LiveView.Channel.start_link({SampleWeb.Endpoint, {#PID<0.634.0>, #Reference<0.1330368881.4203741187.79897>}})
        (elixir 1.10.3) lib/dynamic_supervisor.ex:692: DynamicSupervisor.start_child/3
        (elixir 1.10.3) lib/dynamic_supervisor.ex:678: DynamicSupervisor.handle_start_child/2
        (stdlib 3.12.1) gen_server.erl:661: :gen_server.try_handle_call/4
        (stdlib 3.12.1) gen_server.erl:690: :gen_server.handle_msg/6
        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3`

**Comment by chrismccord** [comment]
Fixed with 1.5.3 release. Adding `{:phoenix_live_view, "~> 0.13.0"}` fixes it. Thanks!

**Comment by sevenseacat** [comment]
I was just filing an issue for this over in the LiveView repo, and then I saw it's already been fixed here 😂 You're all amazing!

**Comment by sigwinch28** [comment]
OT: thanks @chrismccord for the quick fix. I filed this before going to bed and woke up to it fixed!
