### ISSUE TITLE
Invalid alias for inline LiveView in Phoenix Router

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [phoenixframework/phoenix#3872]
### Environment
Ubuntu 18.04.4 LTS
Erlang/OTP 23 [erts-11.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 21)
phoenix_pubsub 2.0.0
phoenix_html 2.14.2
phoenix 1.5.3
phoenix_live_view 0.13.1
phoenix_live_dashboard 0.2.5
phoenix_live_reload 1.2.2

### Expected behavior
A result for: `MyAppWeb.Router.Helpers.live_path/2`
```elixir
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  defmodule Foobar do
    use MyAppWeb, :live_view
    def render(assigns), do: ~L"foobar"
  end

  scope "/", MyAppWeb do
    pipe_through :browser
    live "/foobar",  Foobar
  end

...
```

```elixir
IO.inspect Routes.live_path(socket, MyAppWeb.Router.Foobar)
```

### Actual behavior
```
** (exit) an exception was raised:
    ** (ArgumentError) no action MyAppWeb.Router.Foobar for MyAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:

    live_path(conn_or_endpoint, MyAppWeb.MyAppWeb.Router.Foobar, params \\ [])
        (phoenix 1.5.3) lib/phoenix/router/helpers.ex:374: Phoenix.Router.Helpers.invalid_route_error/3
        (my_app 0.1.0) lib/my_app_web/live/page_live.ex:59: MyAppWeb.PageLive.handle_params/3
        (phoenix_live_view 0.13.1) lib/phoenix_live_view/static.ex:303: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.13.1) lib/phoenix_live_view/static.ex:127: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.13.1) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.5.3) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        ...
        # Routes.live_path/2 called from within handle_params/3 in liveview
        ...
```

Note: MyAppWeb.MyAppWeb.Router.Foobar

```
IO.inspect Routes.live_path(socket, MyAppWeb.MyAppWeb.Router.Foobar)`
"/foobar"
```

**Comment by chrismccord** [comment]
This is expected because `FooBar` is already expanded to `MyAppWeb.Router.FooBar` because it is nested inside the router module. The `scope` argument accepts an alias prefix to add to the aliases, thus we get `MyAppWeb.MyAppWeb.Router.Foobar`. The solution is to simply make your scope: `scope "/" do`. Thanks!

**Comment by i-n-g-m-a-r** [comment]
Actually I never realized that the scope was used to create aliases, thanks!
