### ISSUE TITLE
Phoenix.Router.NoRouteError at POST /sign_in

### ISSUE THREAD

**Issue by siddhant3030** [phoenixframework/phoenix#3963]
Hi,

I'm trying to update my project older version to the latest version. The reason behind that the project is heavily using liveview and the problem is I want to use newer version of the liveview. 

So this is my older version deps

{:phoenix, "~> 1.4.10"},
 {:phoenix_live_view, "~> 0.7.1", override: true}

This is my newer version

{:phoenix, "~> 1.5.4"},
{:phoenix_live_view, "~> 0.14.0"}

I have updated all the versions here according to the latest. I'm not able to sign in and when I do mix phx.routes 

I'm getting this

```

       page_path  GET     /                                                    TuringWeb.PageController :index
       chat_path  GET     /chat/conversations/:conversation_id/users/:user_id  Phoenix.LiveView.Plug TuringWeb.Live.Chat.Conversation
leaderboard_path  GET     /leaderboard                                         Phoenix.LiveView.Plug TuringWeb.Live.Leaderboard
       user_path  GET     /profile/edit                                        Phoenix.LiveView.Plug TuringWeb.Live.Accounts.User
    session_path  DELETE  /sign_in                                             TuringWeb.SessionController :sign_out
    session_path  GET     /sign_in                                             TuringWeb.SessionController :sign_in
       user_path  GET     /sign_up                                             TuringWeb.UserController :sign_up
                  *       /graphiql                                            Absinthe.Plug.GraphiQL [schema: Turing.Graphql.Schema]
                  *       /api                                                 Absinthe.Plug [schema: Turing.Graphql.Schema]
       websocket  WS      /live/websocket                                      Phoenix.LiveView.Socket
        longpoll  GET     /live/longpoll                                       Phoenix.LiveView.Socket
        longpoll  POST    /live/longpoll                                       Phoenix.LiveView.Socket
       websocket  WS      /socket/websocket                                    TuringWeb.UserSocket
```

But there is no post api here. It's working in the older version but not in newer version. I'm not able to find the error what it's related to. Here's the full error

```
[info] POST /sign_in
[debug] ** (Phoenix.Router.NoRouteError) no route found for POST /sign_in (TuringWeb.Router)
    (turing 0.1.0) lib/phoenix/router.ex:402: TuringWeb.Router."call (overridable 2)"/2
    (turing 0.1.0) lib/plug/error_handler.ex:65: TuringWeb.Router.call/2
    (turing 0.1.0) lib/turing_web/endpoint.ex:1: TuringWeb.Endpoint.plug_builder_call/2
    (turing 0.1.0) lib/plug/debugger.ex:132: TuringWeb.Endpoint."call (overridable 3)"/2
    (turing 0.1.0) lib/turing_web/endpoint.ex:1: TuringWeb.Endpoint.call/2
    (phoenix 1.5.4) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.8.0) /Users/siddhant/Documents/turing/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.8.0) /Users/siddhant/Documents/turing/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
    (cowboy 2.8.0) /Users/siddhant/Documents/turing/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

```

**Comment by chrismccord** [comment]
Can you provide the your router.ex?

**Comment by siddhant3030** [comment]
here https://gist.github.com/siddhant3030/18f88d173bbf7f876f675682caae9360 

And I have replaced the  plug :fetch_flash to plug :fetch_live_flash

**Comment by chrismccord** [comment]
Your router indeed has no `post "/signin"`, so you need to check what form in your application is posting to that endpoint. This doesn't appear to be an issue on our side. Thanks!
