### ISSUE TITLE
exception in controller is not being printed in console

### ISSUE THREAD

**Issue by nateless** [phoenixframework/phoenix#3987]
### Environment

* Elixir version (elixir -v): Erlang/OTP 23  / Elixir 1.10.4 
* Phoenix version (mix deps):  1.5.4
* Operating system: Mac / Linux

### Expected behavior
Should always print stacktrace and error in console

### Actual behavior
It either works and prints exception with stacktrace or one needs to press enter or Logger.flush() in the console to make it happen for the next error.

I've created a default phoenix application with explicit error in a controller: https://github.com/nateless/error_test, tested it on Mac and Ubuntu. In one tab phoenix is being run in a second just need to request index page `curl http://localhost:4000/`. After the first request, it didn't render the exception, after pressing enter two times and sending another request, it did render as expected.

```
root@stage ~/error # MIX_ENV=dev iex -S mix phx.server
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

[info] Running ErrorTestWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
[error] Could not start watcher because "node" is not available. Your Phoenix application is still running, however assets won't be compiled. You may fix this by installing "node" and then running "npm install" inside the "assets" directory.
[info] Access ErrorTestWeb.Endpoint at http://localhost:4000
Interactive Elixir (1.10.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [info] GET /
[debug] Processing with ErrorTestWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:api]
[info] Sent 500 in 14ms

nil
iex(2)>
nil
iex(3)> [info] GET /
[debug] Processing with ErrorTestWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:api]
[info] Sent 500 in 241µs
[error] #PID<0.440.0> running ErrorTestWeb.Endpoint (connection #PID<0.439.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in anonymous fn/1 in ErrorTestWeb.PageController.index/2
        (error_test 0.1.0) lib/error_test_web/controllers/page_controller.ex:5: anonymous fn(1) in ErrorTestWeb.PageController.index/2
        (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
        (error_test 0.1.0) lib/error_test_web/controllers/page_controller.ex:5: ErrorTestWeb.PageController.index/2
        (error_test 0.1.0) lib/error_test_web/controllers/page_controller.ex:1: ErrorTestWeb.PageController.action/2
        (error_test 0.1.0) lib/error_test_web/controllers/page_controller.ex:1: ErrorTestWeb.PageController.phoenix_controller_pipeline/2
        (phoenix 1.5.4) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (error_test 0.1.0) lib/plug/error_handler.ex:65: ErrorTestWeb.Router.call/2
        (error_test 0.1.0) lib/error_test_web/endpoint.ex:1: ErrorTestWeb.Endpoint.plug_builder_call/2
        (error_test 0.1.0) lib/plug/debugger.ex:132: ErrorTestWeb.Endpoint."call (overridable 3)"/2
        (error_test 0.1.0) lib/error_test_web/endpoint.ex:1: ErrorTestWeb.Endpoint.call/2
        (phoenix 1.5.4) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /root/error/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /root/error/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /root/error/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

```

**Comment by josevalim** [comment]
Hi @nateless, thanks for the report!

Unfortunately I cannot reproduce this. The error also shows immediately. I also double checked that we don't buffer anything in Logger or elsewhere and that seems to be the case. I am using a Mac with iterm2. Which terminals are you using?

**Comment by nateless** [comment]
Hey @josevalim 

Same. I've tested it locally on my MacBook with iTerm2 and then decided to test it on the ubuntu server and got the same behaviour.

Ive tried to debug it and recompiled with modified `plug/lib/plug/error_handler.ex`:
```elixir
def __catch__(conn, kind, reason, wrapped_reason, stack, handle_errors) do
    IO.inspect(reason)

    receive do
      @already_sent ->
        send(self(), @already_sent)
    after
      0 ->
        normalized_reason = Exception.normalize(kind, wrapped_reason, stack)

        conn
        |> Plug.Conn.put_status(status(kind, normalized_reason))
        |> handle_errors.(%{kind: kind, reason: normalized_reason, stack: stack})
    end

    IO.inspect("before raise")

    :erlang.raise(kind, reason, stack)
  end
```

And there is an exception, but nothing happens after `:erlang.raise/3`

```
[info] GET /
[debug] Processing with ErrorTestWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:api]
%Plug.Conn.WrapperError{
  conn: %Plug.Conn{
    adapter: {Plug.Cowboy.Conn, :...},
    assigns: %{},
    before_send: [#Function<0.60895335/1 in Plug.Telemetry.call/2>,
     #Function<0.33293990/1 in Phoenix.LiveReloader.before_send_inject_reloader/3>],
    body_params: %{},
    cookies: %{},
    halted: false,
    host: "localhost",
    method: "GET",
    owner: #PID<0.461.0>,
    params: %{},
    path_info: [],
    path_params: %{},
    port: 4000,
    private: %{
      ErrorTestWeb.Router => {[], %{}},
      :phoenix_action => :index,
      :phoenix_controller => ErrorTestWeb.PageController,
      :phoenix_endpoint => ErrorTestWeb.Endpoint,
      :phoenix_format => "json",
      :phoenix_layout => {ErrorTestWeb.LayoutView, :app},
      :phoenix_request_logger => {"request_logger", "request_logger"},
      :phoenix_router => ErrorTestWeb.Router,
      :phoenix_view => ErrorTestWeb.PageView,
      :plug_session_fetch => #Function<1.105793137/1 in Plug.Session.fetch_session/1>
    },
    query_params: %{},
    query_string: "",
    remote_ip: {127, 0, 0, 1},
    req_cookies: %{},
    req_headers: [
      {"accept", "*/*"},
      {"host", "localhost:4000"},
      {"user-agent", "curl/7.64.1"}
    ],
    request_path: "/",
    resp_body: nil,
    resp_cookies: %{},
    resp_headers: [
      {"cache-control", "max-age=0, private, must-revalidate"},
      {"x-request-id", "FjVeS37GoMBvwRgAAAAL"}
    ],
    scheme: :http,
    script_name: [],
    secret_key_base: :...,
    state: :unset,
    status: nil
  },
  kind: :error,
  reason: :function_clause,
  stack: [
    {ErrorTestWeb.PageController, :"-index/2-fun-0-", [1],
     [file: 'lib/error_test_web/controllers/page_controller.ex', line: 5]},
    {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1396]},
    {ErrorTestWeb.PageController, :index, 2,
     [file: 'lib/error_test_web/controllers/page_controller.ex', line: 5]},
    {ErrorTestWeb.PageController, :action, 2,
     [file: 'lib/error_test_web/controllers/page_controller.ex', line: 1]},
    {ErrorTestWeb.PageController, :phoenix_controller_pipeline, 2,
     [file: 'lib/error_test_web/controllers/page_controller.ex', line: 1]},
    {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 352]},
    {ErrorTestWeb.Router, :call, 2,
     [file: 'lib/plug/error_handler.ex', line: 66]},
    {ErrorTestWeb.Endpoint, :plug_builder_call, 2,
     [file: 'lib/error_test_web/endpoint.ex', line: 1]},
    {ErrorTestWeb.Endpoint, :"call (overridable 3)", 2,
     [file: 'lib/plug/debugger.ex', line: 132]},
    {ErrorTestWeb.Endpoint, :call, 2,
     [file: 'lib/error_test_web/endpoint.ex', line: 1]},
    {Phoenix.Endpoint.Cowboy2Handler, :init, 4,
     [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 65]},
    {:cowboy_handler, :execute, 2,
     [
       file: '/Users/nate/error_test/deps/cowboy/src/cowboy_handler.erl',
       line: 37
     ]},
    {:cowboy_stream_h, :execute, 3,
     [
       file: '/Users/nate/error_test/deps/cowboy/src/cowboy_stream_h.erl',
       line: 300
     ]},
    {:cowboy_stream_h, :request_process, 3,
     [
       file: '/Users/nate/error_test/deps/cowboy/src/cowboy_stream_h.erl',
       line: 291
     ]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
  ]
}
"before raise"
[info] Sent 500 in 145ms
```

I've tried native mac's terminal - same issue. Actually we've found out about it when we didn't get errors in sentry. So same happens when elixir is detached..

Regards,
N.

**Comment by extg** [comment]
@josevalim I can confirm the same behaviour as @nateless described.

**Comment by nateless** [comment]
Hello @josevalim just checked it with Elixir 11 and it works as expected.

**Comment by josevalim** [comment]
Thank you for following up!
