### ISSUE TITLE
New app from phx.new without `--live` flag crushes on /dashboard

### ISSUE THREAD

**Issue by agalitsyn** [phoenixframework/phoenix#4024]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.0 (compiled with Erlang/OTP 23)
```
* Phoenix version (mix deps):
```
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) 4a0850c9
  ok
* cowboy 2.8.0 (Hex package) (rebar3)
  locked at 2.8.0 (cowboy) 4643e4fb
  ok
* cowboy_telemetry 0.3.0 (Hex package) (rebar3)
  locked at 0.3.0 (cowboy_telemetry) 42868c22
  ok
* cowlib 2.9.1 (Hex package) (rebar3)
  locked at 2.9.1 (cowlib) e4175dc2
  ok
* db_connection 2.2.2 (Hex package) (mix)
  locked at 2.2.2 (db_connection) 642af240
  ok
* decimal 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (decimal) 34666e9c
  ok
* ecto 3.5.2 (Hex package) (mix)
  locked at 3.5.2 (ecto) fd92cfb1
  ok
* ecto_sql 3.5.1 (Hex package) (mix)
  locked at 3.5.1 (ecto_sql) 338150ec
  ok
* file_system 0.2.9 (Hex package) (mix)
  locked at 0.2.9 (file_system) 3cf87a37
  ok
* gettext 0.18.2 (Hex package) (mix)
  locked at 0.18.2 (gettext) f9f537b1
  ok
* jason 1.2.2 (Hex package) (mix)
  locked at 1.2.2 (jason) 18a228f5
  ok
* mime 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (mime) 75fa42c4
  ok
* phoenix 1.5.5 (Hex package) (mix)
  locked at 1.5.5 (phoenix) b10eaf86
  ok
* phoenix_ecto 4.2.1 (Hex package) (mix)
  locked at 4.2.1 (phoenix_ecto) 478a1bae
  ok
* phoenix_html 2.14.2 (Hex package) (mix)
  locked at 2.14.2 (phoenix_html) 58061c8d
  ok
* phoenix_live_dashboard 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (phoenix_live_dashboard) 439628ca
  ok
* phoenix_live_reload 1.2.4 (Hex package) (mix)
  locked at 1.2.4 (phoenix_live_reload) 38f93083
  ok
* phoenix_live_view 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (phoenix_live_view) 585321e9
  ok
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) c52d948c
  ok
* plug 1.10.4 (Hex package) (mix)
  locked at 1.10.4 (plug) ad1e233f
  ok
* plug_cowboy 2.4.0 (Hex package) (mix)
  locked at 2.4.0 (plug_cowboy) e25ddcfc
  ok
* plug_crypto 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (plug_crypto) a48b538a
  ok
* postgrex 0.15.6 (Hex package) (mix)
  locked at 0.15.6 (postgrex) f9926832
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 451d8527
  ok
* telemetry 0.4.2 (Hex package) (rebar3)
  locked at 0.4.2 (telemetry) 2d1419bd
  ok
* telemetry_metrics 0.4.2 (Hex package) (mix)
  locked at 0.4.2 (telemetry_metrics) e56ffed2
  ok
* telemetry_poller 0.5.1 (Hex package) (rebar3)
  locked at 0.5.1 (telemetry_poller) 4cab7206
  ok
```
* NodeJS version (node -v):
```
v14.12.0
```
* NPM version (npm -v):
```
6.14.8
```
* Operating system:
OSX 10.15.7

### Expected behavior
Following the quickstart guide from [docs](https://hexdocs.pm/phoenix/up_and_running.html) should work.
Running `$ mix phx.new hello` installs all needed deps for `/dashboard` to work properly.

### Actual behavior
I tried phoenix 7-8 month ago on the same machine, today I tried again. Running `mix phx.new hello` didn't fetch latest deps, result: when I click on `/dashboard` link, server fails
```
[info] GET /dashboard/nonode%40nohost
[debug] Processing with Phoenix.LiveView.Plug.home/2
  Parameters: %{"node" => "nonode@nohost"}
  Pipelines: [:browser]
[info] Sent 200 in 2ms
[info] CONNECTED TO Phoenix.LiveView.Socket in 80µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "BgdVBlwNNigTLzlJFG4nNR1SKg4LOSgu6_a7ebwxZekymVSGZjpkn_mG", "vsn" => "2.0.0"}
[error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.start_link/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/channel.ex:12: Phoenix.LiveView.Channel.start_link({HelloWeb.Endpoint, {#PID<0.573.0>, #Reference<0.7709625.2124414981.194318>}})
        (elixir 1.11.0) lib/dynamic_supervisor.ex:693: DynamicSupervisor.start_child/3
        (elixir 1.11.0) lib/dynamic_supervisor.ex:679: DynamicSupervisor.handle_start_child/2
        (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
        (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
^C
```

The reason is in `phoenix_live_view` version. When I run `mix phx.new hello --live` it generates `mix.esx` with string `      {:phoenix_live_view, "~> 0.14.6"},`, so it latest, and dashboard works well. But without `--live` flag `mix.esx` don't require specific version of `phoenix_live_view`. In my case `mix.lock` contains 
```
  "phoenix_live_view": {:hex, :phoenix_live_view, "0.12.1", "42f591c781edbf9fab921319076b7ac635d43aa23e6748d2644563326236d7e4", [:mix], [{:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:phoenix, "~> 1.4.16 or ~> 1.5.0", [hex: :phoenix, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.14", [hex: :phoenix_html, repo: "hexpm", optional: false]}], "hexpm", "585321e98df1cd5943e370b9784e950a37ca073744eb534660c9048967c52ab6"},
```
which leads to server fail described above.

So, if I didn't used `--live` flag, new app will have wrong version of `phoenix_live_view. 

Possible solutions:
* Require correct version of `phoenix_live_view`, or fix transitive dependency version in... (where?).
* Maybe remove `--live` flag, because new app generator will fetch `live_view` anyway through transitive dependencies.
* Or do not add `/dashboard` link on main page, and other live view features if `--live` didn't set

**Comment by feliperenan** [comment]
It seems this issue has been solved by this commit: https://github.com/phoenixframework/phoenix/commit/9cee96d597f8462674657f79eb7d7a817c2fa44c

At least I couldn't reproduce using phoenix master 🙌

**Comment by agalitsyn** [comment]
I used [docs](https://hexdocs.pm/phoenix/installation.html) as my step-by-step guide, so I ran `mix archive.install hex phx_new 1.5.5`. Looks like tagged version, not master.

**Comment by chrismccord** [comment]
1.5.6 is out which fixes this. Thanks!
