### ISSUE TITLE
Getting `Failure while translating Erlang's logger event` when task tries to call function from dead node

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix#4046]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Phoenix version (mix deps): phoenix 1.5.6
* NodeJS version (node -v): v12.18.2
* NPM version (npm -v): 6.14.8
* Operating system: Ubuntu 20.10

### Expected behavior
I'm not sure if this is a Phoenix issue exactly, but I only can reproduce it inside a controller, so I'm guessing it have something to do with it.

Basically my controller have some code like this:
```elixir
[result_1, result_2] =
        [
          Task.async(fn ->
            Task.Supervisor.async({Core.Tasks, :"node_1@127.0.0.1"}, Core, :func1, []) |> Task.await()
          end),
          Task.async(fn ->
            Task.Supervisor.async({Core.Tasks, :"node_1@127.0.0.1"}, Core, :func2, []) |> Task.await()
          end)
        ]
        |> Enum.map(&Task.await/1)
```

If my node `node_1@127.0.0.1` is offline, my task will fail with `no connection to node_1@127.0.0.1` and I should receive a status 500 with a body containing the error details as the body.

### Actual behavior

I receive the following error and I get a status 500 without a body as the API http response:
```elixir
21:32:50.537 [error] #PID<0.939.0> 
↳ Task #PID<0.939.0> started from #PID<0.937.0> terminating
** (stop) exited in: GenServer.call({Core.Tasks, :"node_1@127.0.0.1"}, {:start_task, [{:"endpoints@127.0.0.1", #PID<0.939.0>, #PID<0.939.0>}, [#PID<0.939.0>, #PID<0.937.0>], :monitor, {Core, :func1, []}], :temporary, nil}, :infinity)
    ** (EXIT) no connection to node_1@127.0.0.1
    (elixir 1.10.4) lib/gen_server.ex:1023: GenServer.call/3
    (elixir 1.10.4) lib/task/supervisor.ex:456: Task.Supervisor.async/6
    (core 0.1.0) lib/core_web/controllers/v1/chart_controller.ex:46: anonymous fn/0 in CoreWeb.V1.ChartController.get_lasts/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.103318204/0 in CoreWeb.V1.ChartController.get_lasts/2>
    Args: []

21:32:50.537 [error] #PID<0.940.0> 
↳ Task #PID<0.940.0> started from #PID<0.937.0> terminating
** (stop) exited in: GenServer.call({Core.Tasks, :"node_1@127.0.0.1"}, {:start_task, [{:"endpoints@127.0.0.1", #PID<0.940.0>, #PID<0.940.0>}, [#PID<0.940.0>, #PID<0.937.0>], :monitor, {Core, :func2, []}], :temporary, nil}, :infinity)
    ** (EXIT) no connection to node_1@127.0.0.1
    (elixir 1.10.4) lib/gen_server.ex:1023: GenServer.call/3
    (elixir 1.10.4) lib/task/supervisor.ex:456: Task.Supervisor.async/6
    (core 0.1.0) lib/core_web/controllers/v1/chart_controller.ex:49: anonymous fn/0 in CoreWeb.V1.ChartController.get_lasts/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<2.103318204/0 in CoreWeb.V1.ChartController.get_lasts/2>
    Args: []
 
21:32:50.542 [error] #PID<0.934.0> 
↳ Failure while translating Erlang's logger event
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [{Core.Tasks, :"rocket_dbs@127.0.0.1"}, {:start_task, [{:"endpoints@127.0.0.1", #PID<0.941.0>, #PID<0.941.0>}, [#PID<0.941.0>, #PID<0.937.0>], :monitor, {Core, :bla, []}], :temporary, nil}, :infinity]} of type Tuple. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, List, HashDict, HashSet, GenEvent.Stream, Stream, Date.Range, File.Stream, Map, Range, MapSet, Function, IO.Stream
    (elixir 1.10.4) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.4) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.4) lib/enum.ex:3383: Enum.map_intersperse/3
    (elixir 1.10.4) lib/enum.ex:1495: Enum.map_join/3
    (elixir 1.10.4) lib/exception.ex:579: Exception.format_stacktrace/1
    (elixir 1.10.4) lib/exception.ex:145: Exception.format/3
    (plug_cowboy 2.4.0) lib/plug/cowboy/translator.ex:56: Plug.Cowboy.Translator.translate_ranch/6
    (logger 1.10.4) lib/logger/handler.ex:216: Logger.Handler.do_translate/6
    (logger 1.10.4) lib/logger/handler.ex:209: Logger.Handler.translate/6
    (logger 1.10.4) lib/logger/handler.ex:126: Logger.Handler.do_log/4
    (logger 1.10.4) lib/logger/handler.ex:88: Logger.Handler.log/2
    (kernel 7.1) logger_backend.erl:51: :logger_backend.call_handlers/3
    (cowboy 2.8.0) /home/sezdocs/alarms_backend_3/endpoints/deps/cowboy/src/cowboy_http.erl:1209: :cowboy_http.commands/3
    (cowboy 2.8.0) /home/sezdocs/alarms_backend_3/endpoints/deps/cowboy/src/cowboy_http.erl:257: :cowboy_http.loop/1
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
plug_cowboy v2.4.1 has been released with a fix, thanks for the report!

**Comment by sezaru** [comment]
The `plug_cowboy` new version fixed the `Failure while translating Erlang's logger event` error indeed, but I still receive an empty 500 status code empty body and header if I add these `Task.Supervisor.async` calls inside other `Task.async` calls.

So, this works:
```elixir
    [_result_1, _result_2] = [
      Task.Supervisor.async({Core.Tasks, :"node_1@127.0.0.1"}, Core, :func1, []) |> Task.await(),
      Task.Supervisor.async({Core.Tasks, :"node_1@127.0.0.1"}, Core, :func2, []) |> Task.await()
    ]
```
I will receive these headers:
![image](https://user-images.githubusercontent.com/279828/97782889-f1b00b00-1b72-11eb-9f25-41949a896406.png)
And this body:
![image](https://user-images.githubusercontent.com/279828/97782896-feccfa00-1b72-11eb-92ad-07fd47e5f9f1.png)

But if I add the `Task.Supervisor.async` calls inside another `Task.async` like this:
```elixir
    [_result_1, _result_2] =
      [
        Task.async(fn ->
          Task.Supervisor.async({Core.Tasks, :"node_1@127.0.0.1"}, Core, :func1, [])
          |> Task.await()
        end),
        Task.async(fn ->
          Task.Supervisor.async({Core.Tasks, :"node_1@127.0.0.1"}, Core, :func2, [])
          |> Task.await()
        end)
      ]
      |> Enum.map(&Task.await/1)
```

I got an header with content length 0:
![image](https://user-images.githubusercontent.com/279828/97782927-389e0080-1b73-11eb-9ccd-98413ba0a514.png)
And an empty body:
![image](https://user-images.githubusercontent.com/279828/97782934-43f12c00-1b73-11eb-9cf9-8f1e25fae060.png)

I initially thought the `Failure while translating Erlang's logger event` error was the reason for that behaviour, but since this error is already fixed, it doesn't seem like this is the case.

**Comment by sezaru** [comment]
Ok, after some more testing I figured it out, I need to use `Task.Supervisor.async_nolink` instead of `Task.async` so the task is not linked with the current process so it doesn't kill it when the task crash.

I thought it would be possible to catch the error in this case before it would crash the liked parent but it doesn't seem like this is possible.
