### ISSUE TITLE
drainer causes ets.lookup_element error in rancher

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix#4272]
### Environment

* Elixir version (elixir -v): `Elixir 1.11.3 (compiled with Erlang/OTP 23)`
* Phoenix version (mix deps): latest master

### Expected behavior
Not see any errors when the system shuts down.

### Actual behavior
I'm seeing the following error sometimes when the system shuts down:

```
[error] GenServer #PID<0.3791.0> terminating
** (ArgumentError) argument error
    (stdlib 3.14) :ets.lookup_element(:ranch_server, {:listener_sup, VivoWeb.Endpoint.HTTPS}, 2)
    (ranch 1.7.1) /Users/dvic/Development/vivo/deps/ranch/src/ranch_server.erl:101: :ranch_server.get_listener_sup/1
    (ranch 1.7.1) /Users/dvic/Development/vivo/deps/ranch/src/ranch.erl:282: :ranch.get_status/1
    (ranch 1.7.1) /Users/dvic/Development/vivo/deps/ranch/src/ranch.erl:186: :ranch.suspend_listener/1
    (plug_cowboy 2.4.1) lib/plug/cowboy/drainer.ex:100: Plug.Cowboy.Drainer.suspend_listener/1
    (elixir 1.11.3) lib/enum.ex:3381: Enum.filter_list/2
    (elixir 1.11.3) lib/enum.ex:3382: Enum.filter_list/2
    (plug_cowboy 2.4.1) lib/plug/cowboy/drainer.ex:95: Plug.Cowboy.Drainer.drain/2
    (stdlib 3.14) gen_server.erl:727: :gen_server.try_terminate/3
    (stdlib 3.14) gen_server.erl:912: :gen_server.terminate/10
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.3554.0>, :shutdown}
```

I'm not sure if this is the right place to report the issue? Is the issue here that the ets table does not contain the key `{:listener_sup, VivoWeb.Endpoint.HTTPS}`? I'll try to see if I can replicate this is in a separate repo.

**Comment by josevalim** [comment]
Are you seeing this issue in prod or in dev? Are you actually running HTTPS in said environments? In any case, yeah, a way to reproduce the issue would be welcome!

**Comment by josevalim** [comment]
Ping. :) Thanks!

**Comment by dvic** [comment]
Apologies for the late response, forgot to reply on this one :) I tried reproducing it locally but was not able to. It only happened in production. However, I haven't seen the issue anymore since 30th of March. It occurred on multiple projects and none of them shows the error anymore. I think we can go ahead and close this one, unless you want to investigate this one further (if anyones else reported similar issues).

**Comment by josevalim** [comment]
I see, thanks. Glad to reopen if someone has more info or can reproduce it!

**Comment by alpeshjamgade** [comment]
Hi, I'm facing this issue. able to reproduce it in my local dev environment with freshly created project.

**Environment**
Elixir version (elixir -v): Elixir 1.12.0 (compiled with Erlang/OTP 24)
Phoenix version : 1.5.0
```
** (Mix) Could not start application shockwave: Shockwave.Application.start(:normal, []) returned an error: shutdown: failed to start child: ShockwaveWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, ShockwaveWeb.Endpoint.HTTP}
        ** (EXIT) an exception was raised:
            ** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a key that exists in the table

                (stdlib 3.15) :ets.lookup_element(:ranch_server, {:addr, ShockwaveWeb.Endpoint.HTTP}, 2)
                (ranch 1.8.0) /home/necron/codebase/shockwave/deps/ranch/src/ranch_server.erl:113: :ranch_server.get_addr/1
                (phoenix 1.6.8) lib/phoenix/endpoint/cowboy2_adapter.ex:119: Phoenix.Endpoint.Cowboy2Adapter.bound_address/2
                (phoenix 1.6.8) lib/phoenix/endpoint/cowboy2_adapter.ex:115: Phoenix.Endpoint.Cowboy2Adapter.info/3
                (phoenix 1.6.8) lib/phoenix/endpoint/cowboy2_adapter.ex:101: Phoenix.Endpoint.Cowboy2Adapter.start_link/3
                (stdlib 3.15) supervisor.erl:414: :supervisor.do_start_child_i/3
                (stdlib 3.15) supervisor.erl:400: :supervisor.do_start_child/2
                (stdlib 3.15) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
                (stdlib 3.15) supervisor.erl:1234: :supervisor.children_map/4
                (stdlib 3.15) supervisor.erl:350: :supervisor.init_children/2
                (stdlib 3.15) gen_server.erl:423: :gen_server.init_it/2
                (stdlib 3.15) gen_server.erl:390: :gen_server.init_it/6
                (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

```
