### ISSUE TITLE
Phoenix application does not start after being `mix release`-d

### ISSUE THREAD

**Issue by sidkshatriya** [phoenixframework/phoenix#4541]
I get an error after trying to start my brand new Phoenix 1.6.2 application after `mix release`

Steps to repeat
```bash
$ mix phx.new abc123
$ cd abc123
$ mix ecto.create
$ mix release
$ _build/dev/rel/abc123/bin/abc123 start
```

Error after trying to start the release:
```
[info] Application esbuild exited: exited in: Esbuild.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Mix.Project.build_path/0 is undefined (module Mix.Project is not available)
            Mix.Project.build_path()
            (esbuild 0.3.2) lib/esbuild.ex:129: Esbuild.bin_path/0
            (esbuild 0.3.2) lib/esbuild.ex:139: Esbuild.bin_version/0
            (esbuild 0.3.2) lib/esbuild.ex:75: Esbuild.start/2
            (kernel 8.1.1) application_master.erl:293: :application_master.start_it_old/4

{"Kernel pid terminated",application_controller,"{application_start_failure,esbuild,{bad_return,{{'Elixir.Esbuild',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Mix.Project',build_path,[],[]},{'Elixir.Esbuild',bin_path,0,[{file,\"lib/esbuild.ex\"},{line,129}]},{'Elixir.Esbuild',bin_version,0,[{file,\"lib/esbuild.ex\"},{line,139}]},{'Elixir.Esbuild',start,2,[{file,\"lib/esbuild.ex\"},{line,75}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,esbuild,{bad_return,{{'Elixir.Esbuild',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Mix.Project',build_path,[],[]},{'Elixir.Es

Crash dump is being written to: erl_crash.dump...done
```
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 24 [erts-12.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```
* Phoenix version (mix deps):

1.6.2

* Operating system:

Linux, Ubuntu 20.04
### Expected behavior
The phoenix server should start

### Actual behavior
Error -- see above.

**Comment by josevalim** [comment]
This has been fixed in `esbuild` master, thanks for the report. Note that releases should work fine on `prod` though, this is only an issue with the watchers in development.

**Comment by josevalim** [comment]
@sidkshatriya we don't want to copy it to the release because in production you don't actually need esbuild. In any case, I have republished v0.3.3 with a fix, you can remove `deps/esbuild` and try again.
