### ISSUE TITLE
mix phx.gen.embedded with enum generates non-compiling file

### ISSUE THREAD

**Issue by brolund** [phoenixframework/phoenix#4593]
(see below for environment)

Steps to reproduce:
```
mix phx.new embedded --no-assets 
cd embedded 
mix compile 
mix phx.gen.embedded EmbeddedWithEnum an_enum:enum:value_a:value_b
mix compile
```

### Expected behavior
Compile successful

### Actual behavior
```
Compiling 1 file (.ex)

== Compilation error in file lib/embedded/embedded_with_enum.ex ==
** (ArgumentError) invalid or unknown composite {:enum, [values: [:value_a, :value_b]]} for field :an_enum. Did you mean to use array or map as first element of tuple instead?
    (ecto 3.7.1) lib/ecto/schema.ex:2209: Ecto.Schema.composite?/2
    (ecto 3.7.1) lib/ecto/schema.ex:2174: Ecto.Schema.check_field_type!/4
    (ecto 3.7.1) lib/ecto/schema.ex:1881: Ecto.Schema.__field__/4
    lib/embedded/embedded_with_enum.ex:7: (module)
```

The generated file contains
```
embedded_schema do
    field :an_enum, {:enum, [values: [:value_a, :value_b]]}
  end
```
but should probably be something like
```
embedded_schema do
    field :an_enum, Ecto.Enum, values: [:value_a, :value_b]
  end
```
like the result when generating as described in https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Schema.html#module-attributes

```
mix phx.gen.schema Blog.Post blog_posts title status:enum:unpublished:published:deleted
```

### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```
* Phoenix version (mix deps):
```
* connection 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (connection) 722c1eb0
  ok
* cowboy 2.9.0 (Hex package) (rebar3)
  locked at 2.9.0 (cowboy) 2c729f93
  ok
* cowboy_telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (cowboy_telemetry) 7d98bac1
  ok
* cowlib 2.11.0 (Hex package) (rebar3)
  locked at 2.11.0 (cowlib) 2b3e9da0
  ok
* db_connection 2.4.1 (Hex package) (mix)
  locked at 2.4.1 (db_connection) ea36d226
  ok
* decimal 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (decimal) 34666e9c
  ok
* ecto 3.7.1 (Hex package) (mix)
  locked at 3.7.1 (ecto) d36e5b39
  ok
* ecto_sql 3.7.1 (Hex package) (mix)
  locked at 3.7.1 (ecto_sql) 2b42a32e
  ok
* file_system 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (file_system) 41195edb
  ok
* gettext 0.18.2 (Hex package) (mix)
  locked at 0.18.2 (gettext) f9f537b1
  ok
* jason 1.2.2 (Hex package) (mix)
  locked at 1.2.2 (jason) 18a228f5
  ok
* mime 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (mime) e6a3f76b
  ok
* phoenix 1.6.2 (Hex package) (mix)
  locked at 1.6.2 (phoenix) 7bbee475
  ok
* phoenix_ecto 4.4.0 (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  ok
* phoenix_html 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (phoenix_html) 0c0a98a2
  ok
* phoenix_live_dashboard 0.5.3 (Hex package) (mix)
  locked at 0.5.3 (phoenix_live_dashboard) e36e62b1
  ok
* phoenix_live_reload 1.3.3 (Hex package) (mix)
  locked at 1.3.3 (phoenix_live_reload) 76679667
  ok
* phoenix_live_view 0.16.4 (Hex package) (mix)
  locked at 0.16.4 (phoenix_live_view) 754ba49a
  ok
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) c52d948c
  ok
* phoenix_view 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_view) 82be3e25
  ok
* plug 1.12.1 (Hex package) (mix)
  locked at 1.12.1 (plug) d57e799a
  ok
* plug_cowboy 2.5.2 (Hex package) (mix)
  locked at 2.5.2 (plug_cowboy) ea6e87f7
  ok
* plug_crypto 1.2.2 (Hex package) (mix)
  locked at 1.2.2 (plug_crypto) 87631c7a
  ok
* postgrex 0.15.13 (Hex package) (mix)
  locked at 0.15.13 (postgrex) 3ffb76e1
  ok
* ranch 1.8.0 (Hex package) (rebar3)
  locked at 1.8.0 (ranch) 49fbcfd3
  ok
* swoosh 1.5.1 (Hex package) (mix)
  locked at 1.5.1 (swoosh) 867395cb
  ok
* telemetry 1.0.0 (Hex package) (rebar3)
  locked at 1.0.0 (telemetry) 73bc09fa
  ok
* telemetry_metrics 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (telemetry_metrics) 7be9e087
  ok
* telemetry_poller 1.0.0 (Hex package) (rebar3)
  locked at 1.0.0 (telemetry_poller) b3a24eaf
  ok
```

* Operating system: Mac Book Air M1 Big Sur Version 11.6 (20G165)

**Comment by milmazz** [comment]
@brolund You should be able to fix your scenario if you update: `priv/templates/phx.gen.embedded/embedded_schema.ex` to something like:

```diff
diff --git priv/templates/phx.gen.embedded/embedded_schema.ex priv/templates/phx.gen.embedded/embedded_schema.ex
index 03c4b6fd..2597b776 100644
--- priv/templates/phx.gen.embedded/embedded_schema.ex
+++ priv/templates/phx.gen.embedded/embedded_schema.ex
@@ -4,7 +4,7 @@ defmodule <%= inspect schema.module %> do
   alias <%= inspect schema.module %>

   embedded_schema do
-<%= for {k, v} <- schema.types do %>    field <%= inspect k %>, <%= inspect v %><%= schema.defaults[k] %>
+<%= for {k, v} <- schema.types do %>    field <%= inspect k %>, <%= Mix.Phoenix.Schema.type_and_opts_for_schema(v) %><%= schema.defaults[k] %><%= Mix.Phoenix.Schema.maybe_redact_field(k in schema.redacts) %>
 <% end %>  end

   @doc false
```

I can prepare a PR if nobody is already working on this issue.
