### ISSUE TITLE
mix task with Tzdata.TimeZoneDatabase fails with :time_zone_not_found

### ISSUE THREAD

**Issue by paridin** [phoenixframework/phoenix#4633]
### Environment

* Elixir version (elixir -v): 1.13.0
* Phoenix version (mix deps): 1.6.4
* Operating system: MacOS 12.1

### Expected behavior

Successful execution of the `mix` task.

```
mix phx.gen.context Openpay Authz openpay_authz --table pgw_openpay_authz authorization_number:integer:unique local_date:utc_datetime receipt:string:redact metadata:map:redact

* creating lib/koj_pgw/openpay/authz.ex
* creating priv/repo/migrations/20211216005155_create_pgw_openpay_authz.exs
* creating lib/koj_pgw/openpay.ex
* injecting lib/koj_pgw/openpay.ex
* creating test/koj_pgw/openpay_test.exs
* injecting test/koj_pgw/openpay_test.exs
* creating test/support/fixtures/openpay_fixtures.ex
* injecting test/support/fixtures/openpay_fixtures.ex
```

### Actual behavior

```
mix phx.gen.context Openpay Authz openpay_authz --table pgw_openpay_authz authorization_number:integer:unique local_date:utc_datetime receipt:string:redact metadata:map:redact

** (ArgumentError) cannot add -86400 second to ~U[2021-12-16 00:42:00Z] (with time zone database Tzdata.TimeZoneDatabase), reason: :time_zone_not_found
    (elixir 1.13.0) lib/calendar/datetime.ex:1391: DateTime.add/4
    lib/mix/phoenix/schema.ex:199: anonymous fn/2 in Mix.Phoenix.Schema.params/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.0) lib/enum.ex:1496: Enum.into/3
    lib/mix/phoenix/schema.ex:99: Mix.Phoenix.Schema.new/4
    lib/mix/tasks/phx.gen.context.ex:116: Mix.Tasks.Phx.Gen.Context.build/2
    lib/mix/tasks/phx.gen.context.ex:93: Mix.Tasks.Phx.Gen.Context.run/1
```

There is another related conversation on the [forum](https://elixirforum.com/t/phx-gen-live-mix-task-with-tzdata-timezonedatabase-fails-with-time-zone-not-found/42760).

### Posible solution

```elixir
  # lib/mix/phoenix/schema.ex
  
  defp build_utc_datetime_usec do
    ensure_started(Calendar.get_time_zone_database)
    %{DateTime.utc_now() | second: 0, microsecond: {0, 6}}
  end

  defp ensure_started(Tzdata.TimeZoneDatabase) do
    {:ok, _} = Application.ensure_all_started(:tzdata)
    :ok
  end

  defp ensure_started(_), do: :ok
```

I'm open to doing a PR.

**Comment by josevalim** [comment]
@paridin great find!

When we call `DateTime.add/3`, we can pass the database as third argument. We should use Elixir's built-in calendar: `Calendar.UTCOnlyTimeZoneDatabase` instead. We just need to check where we call `DateTime.add` or similar. Can you please send a PR?

**Comment by paridin** [comment]
Sorry for the delayed answer. I applied the suggestions. Also, I reviewed with luck that no other generator uses the functions mentioned.
