### ISSUE TITLE
Can't build Svelte Kit / Vite app with phoenix npm package

### ISSUE THREAD

**Issue by sdoering01** [phoenixframework/phoenix#4662]
### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

  Elixir 1.13.0 (compiled with Erlang/OTP 24)
  ```
* Phoenix version (mix deps):
  ```
  locked at 1.6.6 (phoenix) 807bd646
  ```
* Operating system: Arch Linux (Kernel 5.10.90-1-lts)

### Expected behavior

The npm package `phoenix` can be bundled into a Svelte Kit app using `npm run build` in the svelte-frontend directory of my [example repository](https://github.com/sdoering01/svelte-kit-phoenix-esm-issue).

### Actual behavior

Running `npm run build` in the svelte-frontend directory of my example repository fails with the output below.

To reproduce this behavior:
- Clone my example repository (linked above)
- [Set up the phoenix app as usual and start the server]
- Move into the svelte-frontend directory and run `npm install` to install the dependencies
- [Run `npm run dev -- --open` if you want to verify the overall functionality of the app]
- Try to bundle the app with `npm run build`

A possible fix (that is suggested by the output below) is to change the `.esm.js` suffix to `.mjs` in `node_modules/phoenix/priv/static/`. After I did this and changed the `package.json` of the phoenix package accordingly, `npm run build` worked fine. `npm run preview` can be used to verify the functionality of the previously built app.

I am not sure if there is a reason for naming the esm module files with a `.esm.js` suffix, but it seems to me like the `.mjs` suffix is preferred for esm modules. [This node api reference](https://nodejs.org/api/esm.html) only uses the `.mjs` suffix in its examples. Also when running `find -iname '*.esm.js' | wc -l` and `find -iname '*.mjs' | wc -l` to get the amount of files that end with `.esm.js` and `.mjs` in my projects directory, I get 240 and 3172 files respectively.

Thank you for all your work to create such an awesome framework. It is just a bit frustrating when I want to create a different frontend and end up with an annoying error like this, that costs me many hours.

```
> svelte-frontend@0.0.1 build
> svelte-kit build

vite v2.7.13 building for production...
transforming (15) src/lib/chat-store.ts6:11:51 PM [vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- phoenix
✓ 20 modules transformed.
.svelte-kit/output/client/_app/manifest.json                            1.22 KiB
.svelte-kit/output/client/_app/layout.svelte-ce9e367e.js                0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-9e7fec0e.js                 1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/index.svelte-eb915966.js           2.52 KiB / gzip: 1.27 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-3b5dc1a4.css   0.24 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/start-af74bf45.js                        21.63 KiB / gzip: 7.37 KiB
.svelte-kit/output/client/_app/chunks/vendor-c5086366.js                24.31 KiB / gzip: 8.07 KiB
vite v2.7.13 building SSR bundle for production...
✓ 17 modules transformed.
.svelte-kit/output/server/manifest.json                    0.95 KiB
.svelte-kit/output/server/app.js                           44.92 KiB
.svelte-kit/output/server/entries/pages/layout.svelte.js   0.24 KiB
.svelte-kit/output/server/entries/pages/error.svelte.js    0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js    2.68 KiB
.svelte-kit/output/server/chunks/index-b3dad0a6.js         3.42 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
(node:62521) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/mnt/hdd/code/phoenix_chat/svelte-frontend/node_modules/phoenix/priv/static/phoenix.esm.js:1069
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///mnt/hdd/code/phoenix_chat/svelte-frontend/.svelte-kit/output/server/app.js:982:13)
(node:62521) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token 'export'
(node:62521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 500 /
    at file:///mnt/hdd/code/phoenix_chat/svelte-frontend/node_modules/@sveltejs/kit/dist/chunks/index5.js:314:11
    at visit (file:///mnt/hdd/code/phoenix_chat/svelte-frontend/node_modules/@sveltejs/kit/dist/chunks/index5.js:466:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by chrismccord** [comment]
> Thank you for all your work to create such an awesome framework. It is just a bit frustrating when I want to create a different frontend and end up with an annoying error like this, that costs me many hours.

Thanks! Note that many hours lost to the JS build tool ecosystem is par for the course, especially when using newer or alternative build tools. The phoenix team has spent many many hours wrangly these varying differences :( 

I honestly have no experience with vite.js and if someone can do the heavy lifting of figuring out the tweaks to our build/package.json that are required to make it work *while also not breaking existing esbuild and webpack* setups, then I'd be happy to accept a PR. Historically the issue with this kind of thing is supporting vite has broken webpack, and vice versa, in unexpected ways. Let me know if this is something you'd be interesting in exploring. Thanks!

**Comment by sdoering01** [comment]
Thanks for your fast answer.

To test my 'proposed changes' I forked phoenix and changed the `.esm.js` suffix to `.mjs`. After that I rebuilt the assets and pushed the changes to my fork. Then I installed my forked repo as a npm package using `npm i sdoering01/phoenix#v1.6` and tried to use it with some frontends. In my tests the updated package worked for phoenix itself (esbuild), the above mentioned svelte frontend (vite; wasn't able to build before my changes were made), a create-react-app frontend (webpack) and a vanilla webpack web frontend.

The tests can be reproduced using the following steps:

### Phoenix (mandatory; using esbuild as bundler)

- Clone the `v1.6` branch of [my phoenix fork](https://github.com/sdoering01/phoenix) using: `git clone --single-branch --branch v1.6 git@github.com:sdoering01/phoenix.git`
- Clone my [test repo](https://github.com/sdoering01/svelte-kit-phoenix-esm-issue)
- cd into the test repo
- Set up the phoenix server as usual
- (Check and) run the script in the project root of the test repo (e.g.: `./use_changed_phoenix_assets.sh  "~/Downloads/phoenix"`). The argument has to point to the directory of the cloned phoenix fork. The script will simply link some files from the phoenix fork to the test repo to use the new javascript assets
- Run the phoenix server and see the chat example from the phoenix docs working on http://localhost:4000

### Create-React-App (using webpack as bundler)
- cd into the `react-frontend` directory
- `npm i`
- `npm start` to start the dev server, which can be accessed on http://localhost:3000
- `npm run build` to verify that building works
- `npx serve -s build` to verify that the actual build output works

### Svelte Kit (using vite as bundler)
- cd into the `svelte-frontend` directory
- `npm i`
- `npm run dev` to start the dev server, which can be accessed on http://localhost:3001
- `npm run build` to verify that building works
- `npm run preview` to verify that the actual build output works

### Vanilla webpack
- cd into the `vanilla-webpack-frontend` directory
- `npm i`
- `npm run build`
- `npm run serve` to serve the built assets, which can be accessed on http://localhost:3002

---

I don't have much experience with errors when bundling javascript apps, so I don't know if that's enough to verify that my changes work with all webpack, esbuild and vite configs. Can you (or somebody else) give some feedback on this please?

Note that the tests only test the usage of the es modules since I only changed those.

If you are fine with [the changes](https://github.com/sdoering01/phoenix/commit/14dbf515f9bf0990b3a0a17253a63c3fba80ef0a) I can submit a pull request.

**Comment by mveytsman** [comment]
Hi @sdoering01 - I'm looking into this issue and I can't reproduce the bug -- can you let me know what version of nodejs and npm you're testing with?

Thanks!

**Comment by sdoering01** [comment]
Hey, thanks for your reply.

I am sorry, I completely forgot that my attempt to fix the problem will override the behavior when one clones the repository to reproduce the bug. That's why you probably reproduced that my changes work (see my second comment). My example repository now has a branch called 'issue' (https://github.com/sdoering01/svelte-kit-phoenix-esm-issue/tree/issue) with which you should be able to reproduce the bug as mentioned in my initial comment.

Just in case: My node version is v14.18.2 and my npm version is 8.3.0.
