### ISSUE TITLE
Wrong raise message encoding on recompilation

### ISSUE THREAD

**Issue by Fudoshiki** [phoenixframework/phoenix#4673]
### Environment

* Elixir version (elixir -v):
```zsh
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Elixir 1.13.2 (compiled with Erlang/OTP 24)
```

* Phoenix version (mix deps): `{:phoenix, "~> 1.6"}`

* Operating system: `macOS Monterey 12.2 (21D48)`

### Description

```elixir
defmodule ExampleWeb.Exceptions.CustomCompilerError do
  @moduledoc false

  defexception [:message]

  @impl true
  def exception(_) do
    msg = "абвгд"

    IO.puts(msg)
    IO.inspect(msg)

    %__MODULE__{message: msg}
  end
```

### Start phoenix with initial compile error (Everything is ok, correct message encoding)

```zsh
% mix phx.server
Compiling 4 files (.ex)
абвгд
"абвгд"

== Compilation error in file lib/example_web/views/layout_view.ex ==
** (ExampleWeb.Exceptions.CustomCompilerError) абвгд
    (example_web 0.1.0) lib/example_web/compilers/test.ex:25: ExampleWeb.Compilers.Test.compile/1
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17) erl_eval.erl:893: :erl_eval.expr_list/6
    (stdlib 3.17) erl_eval.erl:237: :erl_eval.expr/5
    (stdlib 3.17) erl_eval.erl:893: :erl_eval.expr_list/6
    (stdlib 3.17) erl_eval.erl:408: :erl_eval.expr/5
    expanding macro: ExampleWeb.LayoutView.test_macro/1
    lib/example_web/templates/layout/root.html.heex:11: ExampleWeb.LayoutView."root.html"/1
```

### Start phoenix and raise custom compile error in runtime (Message encoding is wrong)

```zsh
 % mix phx.server
Compiling 4 files (.ex)
[info] Running ExampleWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Access ExampleWeb.Endpoint at http://localhost:4000
[watch] build finished, watching for changes...
Compiling 4 files (.ex)
Ð°Ð±Ð²Ð³Ð´
"Ð°Ð±Ð²Ð³Ð´"

== Compilation error in file lib/example_web/views/layout_view.ex ==
** (ExampleWeb.Exceptions.CustomCompilerError) Ð°Ð±Ð²Ð³Ð´
    (example_web 0.1.0) lib/example_web/compilers/test.ex:25: ExampleWeb.Compilers.Test.compile/1
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17) erl_eval.erl:893: :erl_eval.expr_list/6
    (stdlib 3.17) erl_eval.erl:237: :erl_eval.expr/5
    (stdlib 3.17) erl_eval.erl:893: :erl_eval.expr_list/6
    (stdlib 3.17) erl_eval.erl:408: :erl_eval.expr/5
    (example_web 0.1.0) expanding macro: ExampleWeb.LayoutView.test_macro/1
    (example_web 0.1.0) lib/example_web/templates/layout/root.html.heex:11: ExampleWeb.LayoutView."root.html"/1
Compiling 4 files (.ex)
Ð°Ð±Ð²Ð³Ð´
"Ð°Ð±Ð²Ð³Ð´"
```

### Expected behavior

Correct message encoding in compile and recompile cycles

### Actual behavior

Wrong message encoding on recompilation

**Comment by chrismccord** [comment]
I don't believe this is anything on our side. Does the same happen if you create a regular mix app and raise that error?
