### ISSUE TITLE
protocol String.Chars not implemented for enum in mix phx.gen.context

### ISSUE THREAD

**Issue by jb3** [phoenixframework/phoenix#4683]
### Environment

* Elixir version (elixir -v): 1.13.0
* Phoenix version (mix deps): 1.6.6
* Operating system: Arch Linux, kernel 5.16.4

### Expected behavior

Similar to `mix phx.gen.schema`, `mix phx.gen.context` should be able to process the command:

```
$ mix phx.gen.context Accounts User users email:text:unique password:text:redact status:enum:verified:unverified:disable
```

### Actual behavior

```elixir
$ mix phx.gen.context Accounts User users email:text:unique password:text:redact status:enum:verified:unverified:disabled
* creating lib/portal/accounts/user.ex
* creating priv/repo/migrations/20220207191418_create_users.exs
* creating lib/portal/accounts.ex
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:enum, :"verified:unverified:disabled"} of type Tuple
    (elixir 1.13.0) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.13.0) lib/string/chars.ex:22: String.Chars.to_string/1
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17) erl_eval.erl:446: :erl_eval.expr/5
    (stdlib 3.17) erl_eval.erl:123: :erl_eval.exprs/5
    (stdlib 3.17) erl_eval.erl:270: :erl_eval.expr/5
    (stdlib 3.17) erl_eval.erl:446: :erl_eval.expr/5
    (stdlib 3.17) erl_eval.erl:123: :erl_eval.exprs/5
```

The `mix phx.gen.schema` of this command works absolutely fine.

**Comment by chrismccord** [comment]
this necessarily involves some arbitrary HTML input decisions for representing and handling the enum, so we don't intend to accept enum types in the HTML generators. Thanks!

**Comment by jb3** [comment]
Thanks for the response! Surely `mix phx.gen.schema` shouldn't be doing any HTML generation? It's just there to generate the context module for use however you want. `mix phx.gen.html` would be doing HTML generation, in which I can understand not supporting enums.

**Comment by chrismccord** [comment]
bah, I read it as the html generator :)

**Comment by milmazz** [comment]
@jb3 I think this is already fixed, I just tried in a new app created with `mix phx.new` and this is working:

```console
$ mix phx.gen.context Accounts User users email:text:unique password:text:redact status:enum:verified:unverified:disable
* creating lib/my_app/accounts/user.ex
* creating priv/repo/migrations/20220305073318_create_users.exs
* creating lib/my_app/accounts.ex
* injecting lib/my_app/accounts.ex
* creating test/my_app/accounts_test.exs
* injecting test/my_app/accounts_test.exs
* creating test/support/fixtures/accounts_fixtures.ex
* injecting test/support/fixtures/accounts_fixtures.ex

Remember to update your repository by running migrations:

    $ mix ecto.migrate
```


I also added the following test locally:

```diff
+  test "generates context with enum", config do
+    in_tmp_project(config.test, fn ->
+      Gen.Context.run(
+        ~w(Accounts User users email:text:unique password:text:redact status:enum:verified:unverified:disabled)
+      )
+
+      assert_file("lib/phoenix/accounts/user.ex", fn file ->
+        assert file =~ "field :status, Ecto.Enum, values: [:verified, :unverified, :disabled]"
+      end)
+
+      assert [path] = Path.wildcard("priv/repo/migrations/*_create_users.exs")
+
+      assert_file(path, fn file ->
+        assert file =~ "create table(:users)"
+        assert file =~ "add :status, :string"
+      end)
+    end)
```

and it works too! I can send a PR with the unit test just in to avoid a regression.
