### ISSUE TITLE
(Phoenix.Router.NoRouteError) no route found for GET /socket/websocket (RumblWeb.Router)

### ISSUE THREAD

**Issue by tedelaney** [phoenixframework/phoenix#4684]
I am working through your book and everything has been working fine until this chapter on Channels.  I followed the instructions in the chapter but when I pull up the View Video page I get the error in the console:

[info] GET /socket/websocket
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /socket/websocket (RumblWeb.Router)
    (rumbl 0.1.0) lib/phoenix/router.ex:406: RumblWeb.Router.call/2
    (rumbl 0.1.0) lib/rumbl_web/endpoint.ex:1: RumblWeb.Endpoint.plug_builder_call/2
    (rumbl 0.1.0) lib/plug/debugger.ex:136: RumblWeb.Endpoint."call (overridable 3)"/2
    (rumbl 0.1.0) lib/rumbl_web/endpoint.ex:1: RumblWeb.Endpoint.call/2
    (phoenix 1.6.6) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.9.0) /Users/tdelaney/Documents/tdelaney/Phoenix/Chapter_03/rumbl/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /Users/tdelaney/Documents/tdelaney/Phoenix/Chapter_03/rumbl/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.9.0) /Users/tdelaney/Documents/tdelaney/Phoenix/Chapter_03/rumbl/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

RumblWeb.Router (router.ex) looks like this:

defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RumblWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/videos", VideoController
    get "watch/:id", WatchController, :show
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: RumblWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

Not sure what to do at this point.  Do you have any suggestions?

Best Regards,

Tom Delaney

**Comment by chrismccord** [comment]
Please send support requests to https://elixirforum.com where folks there will be able to help. Slack is also a great place fo real-time help. Thanks!
