### ISSUE TITLE
[1.7.0-rc.0] Presence crashes on updates

### ISSUE THREAD

**Issue by tmjoen** [phoenixframework/phoenix#5129]
### Environment

* Elixir version (elixir -v): 1.14.1 - Erlang/OTP 25 [erts-13.1.2]
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system: Ubuntu 20.04

### Expected behavior
I'm updating presence with
```elixir
MyApp.Presence.update(socket, socket.assigns.user_id, fn state ->
  %{state | online_at: inspect(System.system_time(:second)), active: active}
end)
```
This works when testing locally

However it fails on prod in a release

### Actual behavior
It fails on our staging setup
```elixir
[mz@myapp:30000] out: 16:35:27.670 [error] GenServer MyApp.Presence_shard0 terminating
[mz@myapp:30000] out: ** (MatchError) no match of right hand side value: nil
[mz@myapp:30000] out:     (phoenix 1.7.0-rc.0) lib/phoenix/presence.ex:507: Phoenix.Presence.handle_info/2
[mz@myapp:30000] out:     (phoenix_pubsub 2.1.1) lib/phoenix/tracker/shard.ex:223: Phoenix.Tracker.Shard.handle_info/2
[mz@myapp:30000] out:     (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
[mz@myapp:30000] out:     (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
[mz@myapp:30000] out:     (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[mz@myapp:30000] out: Last message: {#Reference<0.292686955.1016397826.242480>, {:phoenix, #Reference<0.292686955.1016332290.242477>, [{"lobby", %{joins: %{1 => %{metas: [%{active: true, online_at: "1669307727", phx_ref: "FyqSiLCWEWHfIgSy", phx_ref_prev: "FyqShfUPW1vfIgXh", url: nil}], user: %{avatar: %{}, id: 1, name: "Name"}}}, leaves: %{1 => %{metas: [%{active: true, online_at: "1669307715", phx_ref: "FyqShfUPW1vfIgXh", url: nil}], user: %{avatar: %{}, id: 1, name: "Name"}}}}}]}}
```

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/presence.ex#L507
where it fails is `{:exit, _} = Task.shutdown(task)` — where the right side is nil on my staging server. Which means it failed to shut down the task which means there was no task probably?

**EDIT** I forked Phoenix and added some logging before the `Task.shutdown` call:

```elixir
    Logger.error("== task alive? #{inspect(Process.alive?(task.pid))}")
    {:exit, _} = Task.shutdown(task)
```

On all calls that work fine, "task alive?" returns false while on the calls that crash "task alive?" returns true. 

Is there any way I can help debug this further? Thanks so much for your time

**Comment by tmjoen** [comment]
I manage to reproduce it like this when connected with `remote`
```elixir
iex(my_app@127.0.0.1)2> MyApp.Presence.track(self(), "url:test", 1, %{test: :hello})
{:ok, "FyqfZ_ZLs-UDSSaC"}
iex(my_app@127.0.0.1)3> MyApp.Presence.update(self(), "url:test", 1, fn state -> %{state | test: :world} end)
{:ok, "FyqfaXJYasEDSSaS"}
** (EXIT from #PID<0.5041.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (phoenix 1.7.0-rc.0) lib/phoenix/presence.ex:507: Phoenix.Presence.handle_info/2
        (phoenix_pubsub 2.1.1) lib/phoenix/tracker/shard.ex:223: Phoenix.Tracker.Shard.handle_info/2
        (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
        (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
        (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
But other times it will update fine a couple of times and then fail:
```elixir
iex(my_app@127.0.0.1)1> MyApp.Presence.track(self(), "url:test", 1, %{test: :hello})
{:ok, "Fyqf7OvwMhwNvyrh"}
iex(my_app@127.0.0.1)2> MyApp.Presence.update(self(), "url:test", 1, fn state -> %{state | test: :world} end)
{:ok, "Fyqf7SRXtxYNvyrx"}
iex(my_app@127.0.0.1)3> MyApp.Presence.update(self(), "url:test", 1, fn state -> %{state | test: :world} end)
{:ok, "Fyqf7VxbtzINvysB"}
iex(my_app@127.0.0.1)4> MyApp.Presence.update(self(), "url:test", 1, fn state -> %{state | test: :world} end)
{:ok, "Fyqf7ZnCATsNvysR"}
** (EXIT from #PID<0.5206.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (phoenix 1.7.0-rc.0) lib/phoenix/presence.ex:507: Phoenix.Presence.handle_info/2
        (phoenix_pubsub 2.1.1) lib/phoenix/tracker/shard.ex:223: Phoenix.Tracker.Shard.handle_info/2
        (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
        (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
        (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by simoncocking** [comment]
Thanks for raising this @tmjoen - you saved me the trouble 😅 We're seeing exactly the same crash causing views to reload spontaneously; super disruptive to the UX. I believe we've seen his since #4742.

**Comment by tmjoen** [comment]
@simoncocking does it run fine locally for you as well?

**Comment by simoncocking** [comment]
@tmjoen Yes, the crash is inconsistent - not every call to `update/4` crashes in this way.

**Comment by tmjoen** [comment]
I forked Phoenix and added some logging before the `Task.shutdown` call:

```elixir
Logger.error("== task alive? #{inspect(Process.alive?(task.pid))}")
{:exit, _} = Task.shutdown(task)
```

On all calls that work fine, "task alive?" returns false while on the calls that crash "task alive?" returns true.

**Comment by tmjoen** [comment]
Changing L507 in Phoenix.Presence to forcefully shutting the task down with `{:exit, _} = Task.shutdown(task, :brutal_kill)` seems to solve it in my application. https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/presence.ex#L507

I don't know if this has any other bad implications though, but the code seems to work at least :)
