### ISSUE TITLE
Errors using `phx.gen.auth` without `liveview`

### ISSUE THREAD

**Issue by Grear-0** [phoenixframework/phoenix#5149]
### Environment

* Elixir version (elixir -v): **1.14.1**
* Phoenix version (mix deps): **1.7.0-rc.0**
* Operating system: **macOS Monterey 12.6** 

### Expected behavior
Using the `phx.gen.auth` generator without Liveview, all templates related to authentication should works.

### Actual behavior
`mix test` results:
```
  1) test POST /users/register render errors for invalid data (HubWeb.UserRegistrationControllerTest)
     test/hub_web/controllers/user_registration_controller_test.exs:43
     ** (ArgumentError) no "new" html template defined for HubWeb.UserRegistrationHTML
     code: post(conn, ~p"/users/register", %{
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_registration_controller.ex:1: HubWeb.UserRegistrationController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_registration_controller.ex:1: HubWeb.UserRegistrationController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_registration_controller_test.exs:45: (test)

.....

  2) test GET /users/register renders registration page (HubWeb.UserRegistrationControllerTest)
     test/hub_web/controllers/user_registration_controller_test.exs:7
     ** (ArgumentError) no "new" html template defined for HubWeb.UserRegistrationHTML
     code: conn = get(conn, ~p"/users/register")
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_registration_controller.ex:1: HubWeb.UserRegistrationController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_registration_controller.ex:1: HubWeb.UserRegistrationController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_registration_controller_test.exs:8: (test)

...........................

  3) test GET /users/confirm renders the resend confirmation page (HubWeb.UserConfirmationControllerTest)
     test/hub_web/controllers/user_confirmation_controller_test.exs:13
     ** (ArgumentError) no "new" html template defined for HubWeb.UserConfirmationHTML
     code: conn = get(conn, ~p"/users/confirm")
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_confirmation_controller.ex:1: HubWeb.UserConfirmationController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_confirmation_controller.ex:1: HubWeb.UserConfirmationController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_confirmation_controller_test.exs:14: (test)

..

  4) test POST /users/log_in emits error message with invalid credentials (HubWeb.UserSessionControllerTest)
     test/hub_web/controllers/user_session_controller_test.exs:72
     ** (ArgumentError) no "new" html template defined for HubWeb.UserSessionHTML
     code: post(conn, ~p"/users/log_in", %{
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_session_controller.ex:1: HubWeb.UserSessionController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_session_controller.ex:1: HubWeb.UserSessionController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_session_controller_test.exs:74: (test)

.

  5) test PUT /users/reset_password/:token does not reset password on invalid data (HubWeb.UserResetPasswordControllerTest)
     test/hub_web/controllers/user_reset_password_controller_test.exs:103
     ** (ArgumentError) no "edit" html template defined for HubWeb.UserResetPasswordHTML
     code: put(conn, ~p"/users/reset_password/#{token}", %{
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_reset_password_controller.ex:1: HubWeb.UserResetPasswordController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_reset_password_controller.ex:1: HubWeb.UserResetPasswordController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_reset_password_controller_test.exs:105: (test)



  6) test GET /users/log_in renders log in page (HubWeb.UserSessionControllerTest)
     test/hub_web/controllers/user_session_controller_test.exs:11
     ** (ArgumentError) no "new" html template defined for HubWeb.UserSessionHTML
     code: conn = get(conn, ~p"/users/log_in")
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_session_controller.ex:1: HubWeb.UserSessionController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_session_controller.ex:1: HubWeb.UserSessionController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_session_controller_test.exs:12: (test)

.

  7) test PUT /users/settings (change email form) does not update email on invalid data (HubWeb.UserSettingsControllerTest)
     test/hub_web/controllers/user_settings_controller_test.exs:84
     ** (ArgumentError) no "edit" html template defined for HubWeb.UserSettingsHTML
     code: put(conn, ~p"/users/settings", %{
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_settings_controller.ex:1: HubWeb.UserSettingsController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_settings_controller.ex:1: HubWeb.UserSettingsController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_settings_controller_test.exs:86: (test)

...

  8) test GET /users/reset_password renders the reset password page (HubWeb.UserResetPasswordControllerTest)
     test/hub_web/controllers/user_reset_password_controller_test.exs:13
     ** (ArgumentError) no "new" html template defined for HubWeb.UserResetPasswordHTML
     code: conn = get(conn, ~p"/users/reset_password")
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_reset_password_controller.ex:1: HubWeb.UserResetPasswordController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_reset_password_controller.ex:1: HubWeb.UserResetPasswordController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_reset_password_controller_test.exs:14: (test)

....

  9) test GET /users/reset_password/:token renders reset password (HubWeb.UserResetPasswordControllerTest)
     test/hub_web/controllers/user_reset_password_controller_test.exs:61
     ** (ArgumentError) no "edit" html template defined for HubWeb.UserResetPasswordHTML
     code: conn = get(conn, ~p"/users/reset_password/#{token}")
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_reset_password_controller.ex:1: HubWeb.UserResetPasswordController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_reset_password_controller.ex:1: HubWeb.UserResetPasswordController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_reset_password_controller_test.exs:62: (test)

.

 10) test GET /users/confirm/:token renders the confirmation page (HubWeb.UserConfirmationControllerTest)
     test/hub_web/controllers/user_confirmation_controller_test.exs:68
     ** (ArgumentError) no "edit" html template defined for HubWeb.UserConfirmationHTML
     code: conn = get(conn, token_path)
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_confirmation_controller.ex:1: HubWeb.UserConfirmationController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_confirmation_controller.ex:1: HubWeb.UserConfirmationController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_confirmation_controller_test.exs:70: (test)



 11) test PUT /users/settings (change password form) does not update password on invalid data (HubWeb.UserSettingsControllerTest)
     test/hub_web/controllers/user_settings_controller_test.exs:45
     ** (ArgumentError) no "edit" html template defined for HubWeb.UserSettingsHTML
     code: put(conn, ~p"/users/settings", %{
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_settings_controller.ex:1: HubWeb.UserSettingsController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_settings_controller.ex:1: HubWeb.UserSettingsController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_settings_controller_test.exs:47: (test)



 12) test GET /users/settings renders settings page (HubWeb.UserSettingsControllerTest)
     test/hub_web/controllers/user_settings_controller_test.exs:10
     ** (ArgumentError) no "edit" html template defined for HubWeb.UserSettingsHTML
     code: conn = get(conn, ~p"/users/settings")
     stacktrace:
       (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
       (phoenix_template 1.0.0) lib/phoenix/template.ex:133: Phoenix.Template.render_within_layout/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:883: Phoenix.Controller.render_with_layouts/4
       (phoenix 1.7.0-rc.0) lib/phoenix/controller.ex:870: Phoenix.Controller.render_and_send/4
       (hub 0.1.0) lib/hub_web/controllers/user_settings_controller.ex:1: HubWeb.UserSettingsController.action/2
       (hub 0.1.0) lib/hub_web/controllers/user_settings_controller.ex:1: HubWeb.UserSettingsController.phoenix_controller_pipeline/2
       (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.plug_builder_call/2
       (hub 0.1.0) lib/hub_web/endpoint.ex:1: HubWeb.Endpoint.call/2
       (phoenix 1.7.0-rc.0) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/hub_web/controllers/user_settings_controller_test.exs:11: (test)

.......................................................
Finished in 0.6 seconds (0.4s async, 0.1s sync)
115 tests, 12 failures

Randomized with seed 946352
```

**Comment by danglduy** [comment]
The issue was fixed in this pull request: https://github.com/phoenixframework/phoenix/pull/5081
