### ISSUE TITLE
Phoenix.Transports.LongPoll raises Plug.Conn.AlreadySentError

### ISSUE THREAD

**Issue by zillou** [phoenixframework/phoenix#5189]
Phoenix v1.7.0-rc.0 keeps yielding exceptions like this when using longpoll transport.

```
Request: GET /live/longpoll?_csrf_token=xxx
** (exit) an exception was raised:
    ** (Plug.Conn.AlreadySentError) the response was already sent
        (plug 1.14.0) lib/plug/conn.ex:1804: Plug.Conn.register_before_send/2
        (demo 0.1.0) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.plug_builder_call/2
        (demo 0.1.0) lib/plug/debugger.ex:136: DemoWeb.Endpoint."call (overridable 3)"/2
        (demo 0.1.0) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.call/2
        (phoenix 1.7.0-rc.0) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /private/tmp/demo/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /private/tmp/demo/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /private/tmp/demo/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### Environment

* Elixir version (elixir -v): v1.14.1
* Phoenix version (mix deps): phoenix v1.7.0-rc.0
* Operating system: macOs

A demo project to reproduce this error can be found at: https://github.com/zillou/phx-1.7-longpoll-demo

**Comment by chrismccord** [comment]
I can't recreate this in a basic app. Can you compare notes with my app below with yours an report back? Thanks!

```elixir
signing_salt = :crypto.strong_rand_bytes(8) |> Base.encode16()
secret_base = :crypto.strong_rand_bytes(32) |> Base.encode16()

Application.put_env(:phoenix, :json_library, Jason)

Application.put_env(:sample, SamplePhoenix.Endpoint,
  url: [host: "localhost"],
  http: [
    ip: {0, 0, 0, 0, 0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ],
  server: true,
  pubsub_server: SamplePhoenix.PubSub,
  live_view: [signing_salt: signing_salt],
  secret_key_base: secret_base
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0-rc.0", override: true},
  {:phoenix_live_view, "~> 0.18"}
])

defmodule SamplePhoenix.ErrorView do
  use Phoenix.Component

  def render(_, _), do: "error"
end

defmodule SamplePhoenix.SampleLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  def render("live.html", assigns) do
    ~H"""
    <meta name="csrf-token" content={Phoenix.Controller.get_csrf_token()} />
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.6.10/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.17.10/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content")
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket, {
        transport: window.Phoenix.LongPoll,
        params: {_csrf_token: csrfToken}
      })
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc">+</button>
    <button phx-click="dec">-</button>
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :fetch_session
    plug :protect_from_forgery
    plug :accepts, ["html"]
  end

  scope "/", SamplePhoenix do
    pipe_through :browser

    live "/", SampleLive, :index
  end
end

defmodule SamplePhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample

  @session_options [
    store: :cookie,
    key: "_sample_key",
    signing_salt: "ZcbeUpSS",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  plug Plug.Session, @session_options

  plug Router
end

# Dry run for copying cached mix install from builder to runner
if System.get_env("EXS_DRY_RUN") == "true" do
  System.halt(0)
else
  {:ok, _} =
    Supervisor.start_link(
      [
        {Phoenix.PubSub, name: SamplePhoenix.PubSub},
        SamplePhoenix.Endpoint,
      ],
      strategy: :one_for_one
    )

  Process.sleep(:infinity)
end
```

**Comment by chrismccord** [comment]
Scratch that, I can recreate. I believe it has to do with the code reloader, so stay tuned

**Comment by zillou** [comment]
Thanks Chris.
