### ISSUE TITLE
Receiving this warning despite removing in mix.exs

### ISSUE THREAD

**Issue by charlottemoche** [phoenixframework/phoenix#5201]
* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.7.0-rc.1
* Operating system: mac os

Trying to start the server and receiving this warning:

```
warning: the :phoenix compiler is no longer required in your mix.exs.
Please find the following line in your mix.exs and remove the :phoenix entry:
    compilers: [..., :phoenix, ...] ++ Mix.compilers(),
```

I attempted to remove the entire compilers line per the upgrade video. I also tried removing [:phoenix] and just leaving `compiles: Mix.compilers(). I deleted the build directory and recompiled, and I'm still getting the same message.

Thanks!

**Comment by josevalim** [comment]
Hi @charlottemoche, the warning should include a stacktrace, can you please include it? Also please check for `reloadable_compilers` in your config/config.exs and make sure it is not listed there.

**Comment by charlottemoche** [comment]
Hi @josevalim reloadable_compilers is not listed. Here is the full warning:
```
warning: the :phoenix compiler is no longer required in your mix.exs.

Please find the following line in your mix.exs and remove the :phoenix entry:

    compilers: [..., :phoenix, ...] ++ Mix.compilers(),

  (phoenix 1.7.0-rc.1) lib/mix/tasks/compile.phoenix.ex:8: Mix.Tasks.Compile.Phoenix.run/1
  (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1

==> pow
Compiling 117 files (.ex)
```
