### ISSUE TITLE
"module CAStore is not available" when running mix phx.gen.release --docker

### ISSUE THREAD

**Issue by holsee** [phoenixframework/phoenix#5233]
### Environment

* Elixir version (elixir -v): 1.14.3 (OTP 25)
* Phoenix version (mix deps): 1.7.0-rc2 (master HEAD)
* Operating system: OS X Ventura 13.1 Apple Silicon (M1) 

### Expected behaviour

Mix task to succeed `mix phx.gen.release --docker`

### Actual behaviour

```
$ mix phx.gen.release --docker
* creating rel/overlays/bin/server
* creating rel/overlays/bin/server.bat
* creating rel/overlays/bin/migrate
* creating rel/overlays/bin/migrate.bat
* creating lib/rubberduck_web/release.ex

20:28:24.311 [debug] Fetching latest image information from https://hub.docker.com/v2/namespaces/hexpm/repositories/elixir/tags?name=1.14.3-erlang-25.0.4-debian-bullseye-
** (UndefinedFunctionError) function CAStore.file_path/0 is undefined (module CAStore is not available)
    CAStore.file_path()
    lib/mix/tasks/phx.gen.release.ex:258: Mix.Tasks.Phx.Gen.Release.fetch_body!/1
    lib/mix/tasks/phx.gen.release.ex:205: Mix.Tasks.Phx.Gen.Release.gen_docker/1
    lib/mix/tasks/phx.gen.release.ex:76: Mix.Tasks.Phx.Gen.Release.run/1
    (mix 1.14.3) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by holsee** [comment]
Generated scaffold within ./phoenix/installer @ `07eb6709b2442efd09c626537b7f40429bb3d800` with `mix phx.new rubberduck --umbrella`

**Comment by holsee** [comment]
The issue was the task was being picked up through `archive.install`'d HEAD version of phoenix.  Uninstalling the archive to use the tasks with the dep succeeded.
