### ISSUE TITLE
After latest patch CodeReloader gives: ** (ArgumentError) cannot convert the given list to a string.

### ISSUE THREAD

**Issue by hg-runs** [phoenixframework/phoenix#5236]
### Environment

* Elixir version (elixir -v): **Elixir 1.14.3 (compiled with Erlang/OTP 25)**
* Phoenix version (mix deps): **Latest version from github master**
* Operating system: **Windows 8.1**

### Expected behavior
No error

### Actual behavior

After pulling this patch to CodeReloader:

```
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 12 (delta 8), reused 12 (delta 8), pack-reused 0
Unpacking objects: 100% (12/12), 1.07 KiB | 6.00 KiB/s, done.
From https://github.com/phoenixframework/phoenix
   a0300910..07eb6709  master     -> origin/master
Merge made by the 'recursive' strategy.
 lib/phoenix/code_reloader/server.ex | 16 +++++++++++-----
 1 file changed, 11 insertions(+), 5 deletions(-)

```

I'm getting that error while running a `mix compile`

```
** (ArgumentError) cannot convert the given list to a string.

Please check the given list or call inspect/1 to get the list representation, got:
[build_embedded: false, build_per_environment: true, build_scm: Mix.SCM.Path, config_path: "config/config.exs" .........

    (elixir 1.14.3) lib/list.ex:1084: List.to_string/1
    (elixir 1.14.3) lib/file.ex:1621: File.ls/1
    (phoenix 1.7.0-rc.2) lib/phoenix/code_reloader/server.ex:280: Phoenix.CodeReloader.Server.purge_modules/1
    (phoenix 1.7.0-rc.2) lib/phoenix/code_reloader/server.ex:170: Phoenix.CodeReloader.Server.purge_protocols/1
    (phoenix 1.7.0-rc.2) lib/phoenix/code_reloader/server.ex:183: Phoenix.CodeReloader.Server.mix_compile/4
    (phoenix 1.7.0-rc.2) lib/phoenix/code_reloader/server.ex:73: anonymous fn/3 in Phoenix.CodeReloader.Server.handle_call/3
    (phoenix 1.7.0-rc.2) lib/phoenix/code_reloader/server.ex:296: Phoenix.CodeReloader.Server.proxy_io/1
    (phoenix 1.7.0-rc.2) lib/phoenix/code_reloader/server.ex:71: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib 4.0.1) gen_server.erl:1146: :gen_server.try_handle_call/4
    (stdlib 4.0.1) gen_server.erl:1175: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by elliottneilclark** [comment]
I see the same as well when upgrading our app.
I suspect that https://github.com/phoenixframework/phoenix/commit/e4656fee7eacb6cb9fbf92eaaeaa7b551a55d78e is to blame.

**Comment by josevalim** [comment]
Fixed in master, apologies.
