### ISSUE TITLE
cannot fetch key "_format" from conn.params with accept request header set to json

### ISSUE THREAD

**Issue by jeepers3327** [phoenixframework/phoenix#5257]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.1 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.7.0-rc.2`
* Operating system: `Windows 10 via WSL2 Ubuntu Distro`

### Expected behavior
Should probably respect the `accept` request header and it decide what format it use

### Actual behavior
I have a module function where it uses `put_view` and `render` to render a json view. It works in a when tested in postman but when I try to create an automated test on this function it says `cannot fetch key "_format" from conn.params`. 

I tried adding `put_req_header` to setup block `conn`
```
  setup %{conn: conn} do
    conn =
      conn
      |> Map.replace!(:secret_key_base, MonoWeb.Endpoint.config(:secret_key_base))
      |> init_test_session(%{})

    %{user: user_fixture(), conn: put_req_header(conn, "accept", "application/json")}
  end

  describe "require_authenticated_user/2" do
    test "renders unauthenticated user json if user is not authenticated", %{conn: conn} do
      conn = UserAuth.require_authenticated_user(conn, [])

      assert conn.halted
      assert json_response(conn, 401)["error"] == %{
               "code" => 401,
               "message" => "Unauthenticated user"
             }
    end
  end
```

The test log:
```
  1) test require_authenticated_user/2 renders unauthenticated user json if user is not authenticated (MonoWeb.UserAuthTest)
     test/mono_web/user_auth_test.exs:98
     ** (ArgumentError) cannot fetch key "_format" from conn.params because they were not fetched. Configure and invoke Plug.Parsers to set params based on the request
     code: |> UserAuth.require_authenticated_user([])
     stacktrace:
       (plug 1.14.0) lib/plug/conn/unfetched.ex:35: Plug.Conn.Unfetched.raise_unfetched/3
       (elixir 1.14.1) lib/access.ex:288: Access.get/3
       (phoenix 1.7.0-rc.2) lib/phoenix/controller.ex:890: Phoenix.Controller.render/3
       (mono 0.1.0) lib/mono_web/user_auth.ex:110: MonoWeb.UserAuth.require_authenticated_user/2
       test/mono_web/user_auth_test.exs:104: (test)
```

The fix for this one is to explicitly specify the format via `Phoenix.Controller.put_format`:
```
      conn =
        conn
        |> Phoenix.Controller.put_format(:json)
        |> UserAuth.require_authenticated_user([])
```

**Comment by josevalim** [comment]
_format always override the accepts header, so we need to have both available in order for accepts to work. So it is important to fetch params.
