### ISSUE TITLE
mix phx.new does not generate valid project in umbrella application

### ISSUE THREAD

**Issue by jnnks** [phoenixframework/phoenix#5296]
I am using `phx_new 1.7.0-rc.0` to generate two applications, one standalone and another inside an existing umbrella applications `apps` directory.
When generating the liveview project in the umbrella app, I cannot start the server:
```
Erlang/OTP 24 [erts-12.3.2.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
[...]
 
20:00:57.855 [warning] esbuild version is not configured. Please set it in your config files:

    config :esbuild, :version, "0.16.4"

 
20:00:57.857 [warning] tailwind version is not configured. Please set it in your config files:

    config :tailwind, :version, "3.2.4"

 
20:00:57.862 [error] Could not find hackney dependency.

Please add :hackney to your dependencies:

    {:hackney, "~> 1.9"}

Or set your own Swoosh.ApiClient:

    config :swoosh, :api_client, MyAPIClient

 
20:00:57.862 [notice] Application swoosh exited: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.9.1) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.9.1) lib/swoosh/api_client.ex:42: Swoosh.ApiClient.init/0
            (swoosh 1.9.1) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 8.3.2.3) application_master.erl:293: :application_master.start_it_old/4
 
20:00:57.867 [notice] Application jason exited: :stopped

20:00:57.867 [notice] Application xmerl exited: :stopped
 
20:00:57.868 [notice] Application tailwind exited: :stopped
 
20:00:57.869 [notice] Application esbuild exited: :stopped
 
20:00:57.870 [notice] Application phoenix_live_dashboard exited: :stopped
 
20:00:57.870 [notice] Application telemetry_metrics exited: :stopped
 
20:00:57.870 [notice] Application heroicons exited: :stopped
 
20:00:57.871 [notice] Application phoenix_live_view exited: :stopped
 
20:00:57.872 [notice] Application phoenix_live_reload exited: :stopped
 
20:00:57.872 [notice] Application file_system exited: :stopped
 
20:00:57.872 [notice] Application phoenix_html exited: :stopped
 
20:00:57.873 [notice] Application postgrex exited: :stopped
 
20:00:57.874 [notice] Application ecto_sql exited: :stopped
 
20:00:57.874 [notice] Application db_connection exited: :stopped
 
20:00:57.874 [notice] Application connection exited: :stopped
 
20:00:57.875 [notice] Application phoenix_ecto exited: :stopped
 
20:00:57.876 [notice] Application ecto exited: :stopped
 
20:00:57.876 [notice] Application decimal exited: :stopped
 
20:00:57.877 [notice] Application phoenix exited: :stopped
 
20:00:57.877 [notice] Application castore exited: :stopped

20:00:57.877 [notice] Application websock_adapter exited: :stopped
 
20:00:57.877 [notice] Application websock exited: :stopped
 
20:00:57.877 [notice] Application phoenix_template exited: :stopped
 
20:00:57.878 [notice] Application phoenix_pubsub exited: :stopped
 
20:00:57.878 [notice] Application plug exited: :stopped
 
20:00:57.879 [notice] Application telemetry exited: :stopped
 
20:00:57.880 [notice] Application plug_crypto exited: :stopped
 
20:00:57.880 [notice] Application mime exited: :stopped
 
20:00:57.880 [notice] Application eex exited: :stopped
 
20:00:57.881 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application swoosh: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.9.1) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.9.1) lib/swoosh/api_client.ex:42: Swoosh.ApiClient.init/0
            (swoosh 1.9.1) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 8.3.2.3) application_master.erl:293: :application_master.start_it_old/4
```

Everything works well when not using an umbrella application.

**Comment by jnnks** [comment]
Issue is still present in phx_new-1.7.2

**Comment by thomasdola** [comment]
https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.Web.html

**Comment by jnnks** [comment]
Thanks, I'll check it out!

**Comment by jnnks** [comment]
@thomasdola it seems like the command does not quite fit. I want a "proper" live view app, everything included.
Sorry for the confusion, I put the `--no-ecto` flag in the commands above so that I can start the app, without ecto complaining about the missing database.

**Comment by Gazler** [comment]
This should be fixed on main.

You'll need to clone phoenix and install the archive manually following the instructions from https://github.com/phoenixframework/phoenix/tree/main/installer

**Comment by fnicastri** [comment]
Got same error today,

elixir version:
```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

Phoenix version:
`Phoenix v1.7.10`


Log:
```
 $mix phx.server
==> gold
warning: Plug.Swoosh.MailboxPreview.init/1 is undefined (module Plug.Swoosh.MailboxPreview is not available or is yet to be defined)
  lib/gold/router.ex:41

==> vision
Generated vision app
17:59:57.577 [info] Running Gold.Endpoint with cowboy 2.10.0 at 127.0.0.1:4000 (http)
17:59:57.579 [info] Access Gold.Endpoint at http://localhost:4000
[watch] build finished, watching for changes...
17:59:57.620 [error] Could not find hackney dependency.

Please add :hackney to your dependencies:

    {:hackney, "~> 1.9"}

Or set your own Swoosh.ApiClient:

    config :swoosh, :api_client, MyAPIClient

17:59:57.620 [notice] Application swoosh exited: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.14.2) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.14.2) lib/swoosh/api_client.ex:43: Swoosh.ApiClient.init/0
            (swoosh 1.14.2) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 9.1) application_master.erl:293: :application_master.start_it_old/4
17:59:57.624 [notice] Application finch exited: :stopped
17:59:57.624 [notice] Application nimble_options exited: :stopped
17:59:57.625 [notice] Application nimble_pool exited: :stopped
17:59:57.625 [notice] Application mint exited: :stopped
17:59:57.625 [notice] Application hpax exited: :stopped
17:59:57.625 [notice] Application xmerl exited: :stopped
17:59:57.625 [notice] Application ecto_sql exited: :stopped
17:59:57.625 [notice] Application postgrex exited: :stopped
17:59:57.626 [notice] Application db_connection exited: :stopped
17:59:57.626 [notice] Application dns_cluster exited: :stopped
17:59:57.628 [notice] Application gold exited: :stopped
17:59:57.628 [notice] Application gettext exited: :stopped
17:59:57.628 [notice] Application expo exited: :stopped
17:59:57.629 [notice] Application telemetry_poller exited: :stopped
17:59:57.629 [notice] Application tailwind exited: :stopped
17:59:57.629 [notice] Application esbuild exited: :stopped
17:59:57.629 [notice] Application phoenix_live_dashboard exited: :stopped
17:59:57.630 [notice] Application ecto exited: :stopped
17:59:57.630 [notice] Application telemetry_metrics exited: :stopped
17:59:57.630 [notice] Application phoenix_live_view exited: :stopped
17:59:57.630 [notice] Application phoenix_live_reload exited: :stopped
17:59:57.630 [notice] Application file_system exited: :stopped
17:59:57.630 [notice] Application phoenix exited: :stopped
17:59:57.630 [notice] Application jason exited: :stopped
17:59:57.630 [notice] Application decimal exited: :stopped
17:59:57.630 [notice] Application castore exited: :stopped
17:59:57.630 [notice] Application websock_adapter exited: :stopped
17:59:57.630 [notice] Application plug_cowboy exited: :stopped
17:59:57.630 [notice] Application cowboy_telemetry exited: :stopped
17:59:57.631 [notice] Application cowboy exited: :stopped
17:59:57.631 [notice] Application ranch exited: :stopped
17:59:57.631 [notice] Application cowlib exited: :stopped
17:59:57.631 [notice] Application websock exited: :stopped
17:59:57.631 [notice] Application phoenix_template exited: :stopped
17:59:57.631 [notice] Application phoenix_html exited: :stopped
17:59:57.631 [notice] Application phoenix_pubsub exited: :stopped
17:59:57.631 [notice] Application plug exited: :stopped
17:59:57.632 [notice] Application telemetry exited: :stopped
17:59:57.632 [notice] Application plug_crypto exited: :stopped
17:59:57.632 [notice] Application mime exited: :stopped
17:59:57.632 [notice] Application eex exited: :stopped
17:59:57.632 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application swoosh: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.14.2) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.14.2) lib/swoosh/api_client.ex:43: Swoosh.ApiClient.init/0
            (swoosh 1.14.2) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 9.1) application_master.erl:293: :application_master.start_it_old/4
```

**Comment by fnicastri** [comment]
@josevalim 

I found the issue, when generating a new Phoenix application in an umbrella project
the generator do not add the following lines to /config/dev.exs

```elixir
# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
```
