### ISSUE TITLE
mix phx.server fails due to expired tailwind cert on basic phoenix 1.7.0-rc.3 umbrella project 

### ISSUE THREAD

**Issue by visuelledata** [phoenixframework/phoenix#5301]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.0-rc.3
* Operating system: Windows 10, running via WSL2 - Debian

### Expected behavior
1. mix phx.new myapp --umbrella --no-mailer
2. cd myapp
3. mix ecto.create
4. mix phx.server
5. Open app on localhost

### Actual behavior
1. mix phx.new myapp --umbrella --no-mailer
2. cd myapp
3. mix ecto.create
4. mix phx.server
5. I continually receive this error as the output of `mix phx.server`

```
mix phx.server
[info] Running MyappWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64
[info] Access MyappWeb.Endpoint at http://localhost:4000
[watch] build finished, watching for changes...
[notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2081 generated CLIENT ALERT: Fatal - Certificate Expired

[error] Task #PID<0.586.0> started from MyappWeb.Endpoint terminating
** (RuntimeError) couldn't fetch https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64: {:error, {:failed_connect, [{:to_address, {'objects.githubusercontent.com', 443}}, {:inet, [:inet], {:tls_alert, {:certificate_expired, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2081 generated CLIENT ALERT: Fatal - Certificate Expired\n'}}}]}}
    (tailwind 0.1.10) lib/tailwind.ex:348: Tailwind.fetch_body!/1
    (tailwind 0.1.10) lib/tailwind.ex:235: Tailwind.install/1
    (tailwind 0.1.10) lib/tailwind.ex:215: Tailwind.install_and_run/2
    (phoenix 1.7.0-rc.3) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["tailwind", {Tailwind, :install_and_run, [:default, ["--watch"]]}]
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64
[notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2081 generated CLIENT ALERT: Fatal - Certificate Expired

[error] Task #PID<0.596.0> started from MyappWeb.Endpoint terminating
** (RuntimeError) couldn't fetch https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64: {:error, {:failed_connect, [{:to_address, {'objects.githubusercontent.com', 443}}, {:inet, [:inet], {:tls_alert, {:certificate_expired, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2081 generated CLIENT ALERT: Fatal - Certificate Expired\n'}}}]}}
    (tailwind 0.1.10) lib/tailwind.ex:348: Tailwind.fetch_body!/1
    (tailwind 0.1.10) lib/tailwind.ex:235: Tailwind.install/1
    (tailwind 0.1.10) lib/tailwind.ex:215: Tailwind.install_and_run/2
    (phoenix 1.7.0-rc.3) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["tailwind", {Tailwind, :install_and_run, [:default, ["--watch"]]}]
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64
[notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2081 generated CLIENT ALERT: Fatal - Certificate Expired
```

**Comment by visuelledata** [comment]
Updating WSL fixed this.
