### ISSUE TITLE
[channel_test] [upgrade 1.6 -> 1.7] unable to connect to socket within "non-test" process

### ISSUE THREAD

**Issue by verrchu** [phoenixframework/phoenix#5326]
### Environment
```

Erlang/OTP 24 [erts-12.3.2.6] Elixir (1.12.3)

# mix.lock (phoenix-related)
  "phoenix": {:hex, :phoenix, "1.7.1", "a029bde19d9c3b559e5c3d06c78b76e81396bedd456a6acedb42f9c7b2e535a9", [:mix], [{:castore, ">= 0.0.0", [hex: :castore, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:phoenix_pubsub, "~> 2.1", [hex: :phoenix_pubsub, repo: "hexpm", optional: false]}, {:phoenix_template, "~> 1.0", [hex: :phoenix_template, repo: "hexpm", optional: false]}, {:phoenix_view, "~> 2.0", [hex: :phoenix_view, repo: "hexpm", optional: true]}, {:plug, "~> 1.14", [hex: :plug, repo: "hexpm", optional: false]}, {:plug_cowboy, "~> 2.6", [hex: :plug_cowboy, repo: "hexpm", optional: true]}, {:plug_crypto, "~> 1.2", [hex: :plug_crypto, repo: "hexpm", optional: false]}, {:telemetry, "~> 0.4 or ~> 1.0", [hex: :telemetry, repo: "hexpm", optional: false]}, {:websock_adapter, "~> 0.4", [hex: :websock_adapter, repo: "hexpm", optional: false]}], "hexpm", "ea9d4a85c3592e37efa07d0dc013254fda445885facaefddcbf646375c116457"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "4.4.0", "0672ed4e4808b3fbed494dded89958e22fb882de47a97634c0b13e7b0b5f7720", [:mix], [{:ecto, "~> 3.3", [hex: :ecto, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.14.2 or ~> 3.0", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:plug, "~> 1.9", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm", "09864e558ed31ee00bd48fcc1d4fc58ae9678c9e81649075431e69dbabb43cc1"},
  "phoenix_html": {:hex, :phoenix_html, "3.3.1", "4788757e804a30baac6b3fc9695bf5562465dd3f1da8eb8460ad5b404d9a2178", [:mix], [{:plug, "~> 1.5", [hex: :plug, repo: "hexpm", optional: true]}], "hexpm", "bed1906edd4906a15fd7b412b85b05e521e1f67c9a85418c55999277e553d0d3"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.3.3", "3a53772a6118d5679bf50fc1670505a290e32a1d195df9e069d8c53ab040c054", [:mix], [{:file_system, "~> 0.2.1 or ~> 0.3", [hex: :file_system, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.4", [hex: :phoenix, repo: "hexpm", optional: false]}], "hexpm", "766796676e5f558dbae5d1bdb066849673e956005e3730dfd5affd7a6da4abac"},
  "phoenix_pubsub": {:hex, :phoenix_pubsub, "2.1.1", "ba04e489ef03763bf28a17eb2eaddc2c20c6d217e2150a61e3298b0f4c2012b5", [:mix], [], "hexpm", "81367c6d1eea5878ad726be80808eb5a787a23dee699f96e72b1109c57cdd8d9"},
  "phoenix_template": {:hex, :phoenix_template, "1.0.1", "85f79e3ad1b0180abb43f9725973e3b8c2c3354a87245f91431eec60553ed3ef", [:mix], [{:phoenix_html, "~> 2.14.2 or ~> 3.0", [hex: :phoenix_html, repo: "hexpm", optional: true]}], "hexpm", "157dc078f6226334c91cb32c1865bf3911686f8bcd6bcff86736f6253e6993ee"},
  "phoenix_view": {:hex, :phoenix_view, "2.0.2", "6bd4d2fd595ef80d33b439ede6a19326b78f0f1d8d62b9a318e3d9c1af351098", [:mix], [{:phoenix_html, "~> 2.14.2 or ~> 3.0", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:phoenix_template, "~> 1.0", [hex: :phoenix_template, repo: "hexpm", optional: false]}], "hexpm", "a929e7230ea5c7ee0e149ffcf44ce7cf7f4b6d2bfe1752dd7c084cdff152d36f"},
```

### Expected behavior
we have a bunch of channel tests where we spawn a separate process wihtin a test and connect to a socket from within that separate rpocess in order to check difference in behaviour between "actor" process (test process) and "observer" process (separately spawned process)

### Actual behavior
After we *had to* upgrade our phoenix version form 1.6+ to 1.7.1 all our tests which spawn processes which connect to sockets stopped passing and judging from the error message sit is _by design_

Here is an example of a real test that we have and which happens to be failing after upgrade

```
test "visitor can't join twice", %{} do
  {:ok, socket} =
    connect(VisitorSocket, %{"token" => generate_visitor_jwt(visitor)})

  {:ok, _resp, _socket} = subscribe_and_join(socket, "channel")

  second_join =
    Task.async(fn ->
      {:ok, socket} =
        connect(VisitorSocket, %{"token" => generate_visitor_jwt(visitor)})

      {:ok, _resp, _socket} = subscribe_and_join(socket, "channel")
    end)

  Task.yield(second_join)
end
```

and here is the error
```
  1) test visitor can't join twice (Acceptance.ChannelVisitorTest)
     test/acceptance/channel_visitor_test.exs:85
     ** (EXIT from #PID<0.804.0>) an exception was raised:
         ** (ArgumentError) socket/1-3 can only be invoked from the test process
             (phoenix 1.7.1) lib/phoenix/test/channel_test.ex:272: Phoenix.ChannelTest.fetch_test_supervisor!/0
             (phoenix 1.7.1) lib/phoenix/test/channel_test.ex:308: Phoenix.ChannelTest.__connect__/4
             test/acceptance/channel_visitor_test.exs:94: anonymous fn/2 in Acceptance.ChannelVisitorTest."test visitor can't join twice"/1
             (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
             (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
             (stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

# question
what is the proper way to test the difference of behavior between "acting" and "observing" sockets if it is forbidden to establish socket connection within non-test processes?

**Comment by verrchu** [comment]
# update

I found a way to make the tests work by not relying on `Task` module and manually registering spawned processes under `ExUnit.OnExitHandler` but it is not exactly nice

```
test "visitor can't join twice", %{} do
  {:ok, socket} =
    connect(VisitorSocket, %{"token" => generate_visitor_jwt(visitor)})

  {:ok, _resp, _socket} = subscribe_and_join(socket, "channel")

  {pid, ref} =
    Process.spawn(
      fn ->
        {:ok, socket} =
          connect(VisitorSocket, %{"token" => generate_visitor_jwt(visitor)})

        {:ok, _resp, _socket} = subscribe_and_join(socket, "channel")
      end,
      [:monitor]
    )

  :ok = ExUnit.OnExitHandler.register(pid)

  receive do
    {:DOWN, ^ref, _, _, _} -> :ok
  end
end
```

**Comment by josevalim** [comment]
Do you need to start the second process? Can't you establish several connections from the same process?

Other than that, the fix was necessary to avoid leaking processes in channel tests. OnExitHandler is private API, so it was not mean to be invoked directly (hence it may not be nice) and it may break. So if establishing from the same process does not work, we will certainly need to extend the existing API.

**Comment by verrchu** [comment]
@josevalim I suppose I really need to establish connections from different processes so that I can check that each process receives different messages

**Comment by josevalim** [comment]
So can you please send a PR that adds socket/4, where the four argument is a keyword list of options? The only option we will support for now is the `:test_process`, which we can default to `self()` if not given. Then you simply has to pass it from your task. WDYT?

**Comment by verrchu** [comment]
oh ok I'll try to come up with a PR some time this week

thanks for the idea
