### ISSUE TITLE
Running `mix archive.install hex phx_new` fails

### ISSUE THREAD

**Issue by ondrejnyvlt** [phoenixframework/phoenix#5413]
When I try to run `mix archive.install hex phx_new`, I encounter varying errors.

### Environment

* Elixir version (elixir -v): `Elixir 1.14.4 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.7.2`
* Operating system: MacOS 13.1 (M1)

### Expected behavior

The command should install phoenix application generator.

### Actual behavior

When I run the command, it outputs:

```sh
$ mix archive.install hex phx_new 1.7.2
Resolving Hex dependencies...
Resolution completed in 0.029s
New:
  phx_new 1.7.2
* Getting phx_new (Hex package)
All dependencies are up to date
Compiling 11 files (.ex)
```

and then it throws

```sh
** (FunctionClauseError) no function clause matching in Mix.Tasks.Local.Phx.__info__/1

    The following arguments were given to Mix.Tasks.Local.Phx.__info__/1:

        # 1
        :exports_md5

    Mix.Tasks.Local.Phx.__info__/1
    (mix 1.14.4) lib/mix/compilers/elixir.ex:495: Mix.Compilers.Elixir.each_module/4
    (elixir 1.14.4) lib/kernel/parallel_compiler.ex:534: Kernel.ParallelCompiler.wait_for_messages/7
    (elixir 1.14.4) lib/kernel/parallel_compiler.ex:204: Kernel.ParallelCompiler.spawn_workers/5
    (elixir 1.14.4) lib/kernel/parallel_compiler.ex:177: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.14.4) lib/mix/compilers/elixir.ex:158: Mix.Compilers.Elixir.compile/7
    (mix 1.14.4) lib/mix/state.ex:15: Mix.State.lock/2
    (mix 1.14.4) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
```

or

```sh
fish: Job 1, 'mix archive.install hex phx_new…' terminated by signal SIGBUS (Misaligned address error)
```

I also tried to specify particular versions (1.7.2, 1.7.1, 1.7.0, 1.6.0, ...), but the problem persists.

**Comment by josevalim** [comment]
Can you try uninstalling any current version before installing the new one?

**Comment by ondrejnyvlt** [comment]
@josevalim Ok, I uninstalled everything and started anew, and now it seems to work correctly.
