### ISSUE TITLE
Bug: Unique constraint added to model will cause generated liveview test to fail without saying why

### ISSUE THREAD

**Issue by loganmac** [phoenixframework/phoenix#5456]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.2
* Operating system: WSL2 on Windows 11

### Expected behavior
Generated liveview test should say why the assertion is failing

### Actual behavior
Liveview test (specifically the `Index > saves new MODEL_NAME` test) fails, but it's hard to tell why.

error:
```bash
1) test Index saves new thing (MyappWeb.ThingLiveTest)
     test/myapp_web/live/thing_live_test.exs:26
     ** (ArgumentError) expected MyappWeb.ThingLive.Index to patch to "/things", but got none
     code: assert_patch(index_live, ~p"/things")
     stacktrace:
       (phoenix_live_view 0.18.18) lib/phoenix_live_view/test/live_view_test.ex:1314: Phoenix.LiveViewTest.assert_navigation/4
       (phoenix_live_view 0.18.18) lib/phoenix_live_view/test/live_view_test.ex:1214: Phoenix.LiveViewTest.assert_patch/3
       test/myapp_web/live/thing_live_test.exs:42: (test)
```

### Steps to reproduce
Add a unique constraint on the model after the generation.  So: `mix phx.gen.live Fake Thing things name:string`. Then add a unique index in your migration, and a unique constraint to the Ecto changeset for the model.

I found out this was the problem by removing the unique_constraint on the changeset, and then it raised the error.

**Comment by loganmac** [comment]
@chrismccord the reason for the issue was really that the test was failing but it was hard to track down why it was failing, causing a poor developer experience. 

Maybe there is a good way to debug that liveview test that I’m not aware of, I was just raising awareness that it was really frustrating that the tests just fails and doesn’t give any indication as to what is wrong or why, and it’s hard to tell why that assert is failing in the test.
