### ISSUE TITLE
phx.gen.json with namespace (--web) creates duplicate changeset_json.ex

### ISSUE THREAD

**Issue by princemaple** [phoenixframework/phoenix#5475]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.2
* Operating system: Windows 11

### Expected behavior
Not to generate extra `changeset_json.ex`.

### Actual behavior
When there is already a `changeset_json.ex` generated without namespace, running `phx.gen.json` with a namespace `--web NameSpace` would generate another `changeset_json.ex` with `MyApp.ChangesetJSON` (note: same module name as the one in root) at `name_space/changeset_json.ex`

It's apparently not needed.

**Comment by chrismccord** [comment]
@varshneydevansh it’s yours! Thank you! ❤️

**Comment by varshneydevansh** [comment]
So, yesterday I did the Phoenix setup, and today I tried to understand how it works. Then I replicate the issue with the following commands.
```
first I ran - 
mix phx.gen.json Accounts User users name:string --web hello_dev

then this - 
mix phx.gen.json Accounts User comment name:string comment:string --web hello_dev

then this - 
mix phx.gen.json Accounts User users name:string

and at last - 
mix phx.gen.json Accounts User users name:string --web Namespace
```
 What I got is in the image below -

![image](https://github.com/phoenixframework/phoenix/assets/20411128/69000508-e22e-4c4f-acad-96fb6b72b736)

There were three changeset_json.ex files generated, and all three were similar, and then I looked into what this exactly does to ensure data integrity and for handling errors when inserting, updating or deleting database records and in this case, only one gets used which depends on the order in which the files are compiled. (Correct me if I am wrong)


So, for this, my proposed solution is to use an **if-check** in `def files_to_be_generated()`   at `phoenix\lib\mix\tasks\phx.gen.json.ex`  to see whether `changeset_json.ex` already exists or not.

**Comment by varshneydevansh** [comment]
This is what I came up with -

 ```elixir
def files_to_be_generated(%Context{schema: schema, context_app: context_app}) do
    singular = schema.singular
    web = Mix.Phoenix.web_path(context_app)
    test_prefix = Mix.Phoenix.web_test_path(context_app)
    web_path = to_string(schema.web_path)
    controller_pre = Path.join([web, "controllers", web_path])
    test_pre = Path.join([test_prefix, "controllers", web_path])

    # Check if changeset_json.ex already exists
    changeset_json_path = Path.join([controller_pre, "changeset_json.ex"])
    does_changeset_json_exists = File.exists?(changeset_json_path)

    files_generated = [
      {:eex, "controller.ex", Path.join([controller_pre, "#{singular}_controller.ex"])},
      {:eex, "json.ex", Path.join([controller_pre, "#{singular}_json.ex"])},
      {:eex, "controller_test.exs", Path.join([test_pre, "#{singular}_controller_test.exs"])},
      {:new_eex, "fallback_controller.ex", Path.join([web, "controllers/fallback_controller.ex"])}
    ]
    if !does_changeset_json_exists do
      files_generated ++ [{:new_eex, "changeset_json.ex", changeset_json_path}] # changeset_json.ex does not exist, adding it to the list
    else
      files_generated   # changeset_json.ex already exists returing the rest of the list
    end

  end
```
I did try to **run the test** also with `mix test` This was the result of that -

```
Finished in 85.3 seconds (5.9s async, 79.3s sync)
11 doctests, 883 tests, 62 failures

Randomized with seed 192471
```

**Comment by varshneydevansh** [comment]
So, what I did today is, I tried to create the project from my local updated repo. This is how I did-

I added the `{:phoenix, path: "C:/Users/varsh/Documents/phoenix", override: true},`  in mix.exs in the created project  **C:\Users\varsh\Documents\hello_local_repo** then ran the command `mix deps.get` 

and it was still generating the `changeset_json` file in new namespaces (refer the below image)

![image](https://github.com/phoenixframework/phoenix/assets/20411128/695dfcba-24b5-4092-86e6-7ed340e4128b)


Then again I changed the above code `def files_to_be_generated()` with the following -

```elixir
  @doc false
  def files_to_be_generated(%Context{schema: schema, context_app: context_app}) do
    singular = schema.singular
    web = Mix.Phoenix.web_path(context_app)
    test_prefix = Mix.Phoenix.web_test_path(context_app)
    web_path = to_string(schema.web_path)
    controller_pre = Path.join([web, "controllers", web_path])
    test_pre = Path.join([test_prefix, "controllers", web_path])

    # Always use the root controllers directory for changeset_json_path
    root_controller_pre = Path.join([web, "controllers"])
    changeset_json_path = Path.join([root_controller_pre, "changeset_json.ex"])

    does_changeset_json_exists = File.exists?(changeset_json_path)

    files_generated = [
      {:eex, "controller.ex", Path.join([controller_pre, "#{singular}_controller.ex"])},
      {:eex, "json.ex", Path.join([controller_pre, "#{singular}_json.ex"])},
      {:eex, "controller_test.exs", Path.join([test_pre, "#{singular}_controller_test.exs"])},
      {:new_eex, "fallback_controller.ex", Path.join([web, "controllers/fallback_controller.ex"])}
    ]
    if !does_changeset_json_exists do
      files_generated ++ [{:new_eex, "changeset_json.ex", changeset_json_path}] # changeset_json.ex does not exist, adding it to the list
    else
      files_generated   # changeset_json.ex already exists returing the rest of the list
    end

  end
```


and then I created a new project **C:\Users\varsh\Documents\hello_local_repo_2** then ran the command `mix deps.get` 


and this was the output - 

![image](https://github.com/phoenixframework/phoenix/assets/20411128/7e4c92d2-7384-4e89-97ae-8aaa80c48175)

Another - 


![image](https://github.com/phoenixframework/phoenix/assets/20411128/f114c881-25aa-4437-8db9-490a8dff7e82)

I even ran the mix test again in the local phoenix directory and this was the result -
```

 15) test test_config_inject/2 injects after "use Mix.Config" when hashing_library is argon2 (Mix.Tasks.Phx.Gen.Auth.InjectorTest)
     test/mix/tasks/phx.gen.auth/injector_test.exs:320
     Assertion with == failed
     code:  assert injected ==
              "use Mix.Config\r\n\r\n# Only in tests, remove the complexity from the password hashing algorithm\r\nconfig :argon2_elixir, t_cost: 1, m_cost: 8\r\n"
     left:  "use Mix.Config\r\n\r\n# Only in tests, remove the complexity from the password hashing algorithm\r\r\nconfig :argon2_elixir, t_cost: 1, m_cost: 8\r\n"
     right: "use Mix.Config\r\n\r\n# Only in tests, remove the complexity from the password hashing algorithm\r\nconfig :argon2_elixir, t_cost: 1, m_cost: 8\r\n"
     stacktrace:
       test/mix/tasks/phx.gen.auth/injector_test.exs:329: (test)

...............
== Compilation error in file test/phoenix/controller/render_test.exs ==
** (RuntimeError) could not load Phoenix.HTML.Engine to use with .html.eex templates. You can configure your own format encoder for HTML but we recommend adding phoenix_html as a dependency as it provides XSS protection.
    (phoenix_template 1.0.0) lib/phoenix/template/eex_engine.ex:18: Phoenix.Template.EExEngine.options_for/1
    (phoenix_template 1.0.0) lib/phoenix/template/eex_engine.ex:9: Phoenix.Template.EExEngine.compile/2
    (phoenix_template 1.0.0) lib/phoenix/template.ex:321: anonymous fn/4 in Phoenix.Template.__compile_all__/5
    (elixir 1.14.5) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.14.5) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (phoenix_template 1.0.0) lib/phoenix/template.ex:317: Phoenix.Template.__compile_all__/5
    c:/Users/varsh/Documents/phoenix/test/fixtures/views.exs:1: (file)
    (stdlib 4.3.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.3.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.3.1) erl_eval.erl:454: :erl_eval.expr/6
    (stdlib 4.3.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.3.1) erl_eval.erl:454: :erl_eval.expr/6
    (stdlib 4.3.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.3.1) erl_eval.erl:454: :erl_eval.expr/6
    (stdlib 4.3.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.3.1) erl_eval.erl:454: :erl_eval.expr/6
    (stdlib 4.3.1) erl_eval.erl:492: :erl_eval.expr/6
    (stdlib 4.3.1) erl_eval.erl:136: :erl_eval.exprs/6
    (phoenix_view 2.0.0) c:/Users/varsh/Documents/phoenix/test/fixtures/views.exs:1: Phoenix.View.__before_compile__/1
```

I think I am still missing something. 
Furthermore, I even ran this before testing.

```
If you cloned a while ago, get the latest changes from upstream, and update your fork:

git checkout main
git pull upstream main
git push
```

**Comment by varshneydevansh** [comment]
Should I create the PR? Or if anyone can guide me with the above result, what should I do.

**Comment by varshneydevansh** [comment]
> Should I create the PR? Or if anyone can guide me with the above result, what should I do.

@princemaple should I test more?

**Comment by chrismccord** [comment]
@varshneydevansh yes please send a PR and we can discuss necessary changes (if any) on that side. Thank you and thanks for waiting patiently while I cleared some other things off my plate!

**Comment by princemaple** [comment]
https://github.com/phoenixframework/phoenix/blob/9dd4689443bd94539ca6c6cc430afeb5fe3f85dc/lib/mix/tasks/phx.gen.json.ex#LL143C89-L143C89

I think changing this line from

```elixir
{:new_eex, "changeset_json.ex", Path.join([controller_pre, "changeset_json.ex"])},
```

to be just like `fallback_controller.ex` is sufficient:

```elixir
{:new_eex, "changeset_json.ex", Path.join([web_path, "controllers/changeset_json.ex"])},
```

Then fix the tests :)

**Comment by varshneydevansh** [comment]
I made changes according to the above-mentioned by @princemaple, and it's **working correctly without generating** the extra `changeset_json.ex`. Which was expected.

```elixir
@doc false
  def files_to_be_generated(%Context{schema: schema, context_app: context_app}) do
    singular = schema.singular
    web = Mix.Phoenix.web_path(context_app)
    test_prefix = Mix.Phoenix.web_test_path(context_app)
    web_path = to_string(schema.web_path)
    controller_pre = Path.join([web, "controllers", web_path])
    test_pre = Path.join([test_prefix, "controllers", web_path])

    [
      {:eex, "controller.ex", Path.join([controller_pre, "#{singular}_controller.ex"])},
      {:eex, "json.ex", Path.join([controller_pre, "#{singular}_json.ex"])},
      {:new_eex, "changeset_json.ex", Path.join([web, "controllers/changeset_json.ex"])},
      {:eex, "controller_test.exs", Path.join([test_pre, "#{singular}_controller_test.exs"])},
      {:new_eex, "fallback_controller.ex", Path.join([web, "controllers/fallback_controller.ex"])}
    ]
  end
```
Then I updated my current code base with -
```
>> git checkout main
>> git pull upstream main
>> git push
```

And this was the output of the last test result `mix test` -
```
Finished in 87.6 seconds (6.0s async, 81.5s sync)
11 doctests, 883 tests, 64 failures

Randomized with seed 543721
```
![image](https://github.com/phoenixframework/phoenix/assets/20411128/baf81706-d2c6-48e8-ac7c-3276e0fb95c7)



I greatly appreciate Po for simplifying my unnecessarily complex code, and I greatly appreciate Chris assigning me this opportunity.

I am now sending my PR.

**Comment by djgoku** [comment]
Great work!

It looks like this can now be closed as the PR has been merged.
