### ISSUE TITLE
Exception is printed twice in the browser

### ISSUE THREAD

**Issue by damir** [phoenixframework/phoenix#5494]
### Environment

* Elixir version: 1.15.0
* Phoenix version: 1.7.6
* Operating system: macOS

### Actual behavior

```
Compiling 1 file (.ex)

== Compilation error in file lib/demo_app_web/router.ex ==
** (ArgumentError) could not infer :as option because a live action was given and the LiveView does not have a "Live" suffix. Please pass :as explicitly or make sure your LiveView is named like "FooLive" or "FooLive.Index"
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/router.ex:439: Phoenix.LiveView.Router.inferred_as/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/router.ex:369: Phoenix.LiveView.Router.__live__/4
    lib/demo_app_web/router.ex:25: (module)
    (elixir 1.14.0) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7

** (ArgumentError) could not infer :as option because a live action was given and the LiveView does not have a "Live" suffix. Please pass :as explicitly or make sure your LiveView is named like "FooLive" or "FooLive.Index"
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/router.ex:439: Phoenix.LiveView.Router.inferred_as/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/router.ex:369: Phoenix.LiveView.Router.__live__/4
    lib/demo_app_web/router.ex:25: (module)
    (elixir 1.14.0) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

```
Compiling 1 file (.ex)

== Compilation error in file lib/demo_app_web/router.ex ==
** (ArgumentError) could not infer :as option because a live action was given and the LiveView does not have a "Live" suffix. Please pass :as explicitly or make sure your LiveView is named like "FooLive" or "FooLive.Index"
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/router.ex:439: Phoenix.LiveView.Router.inferred_as/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/router.ex:369: Phoenix.LiveView.Router.__live__/4
    lib/demo_app_web/router.ex:25: (module)
    (elixir 1.14.0) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by phoebe100** [comment]
In Phoenix.CodeReloader.Server, we have the following lines:
```
# Diagnostics are written to stderr and therefore not captured,
# so we send them to the group leader here
Proxy.diagnostics(Process.group_leader(), diagnostics)
```
I'm not sure whether the comment is (still) true. If the compiler writes the diagnostics to stdout, then this line would produce the duplicate error

**Comment by josevalim** [comment]
I believe we need that line for other diagnostics, such as warnings. Although I don't understand why `== Compilation error in file lib/demo_app_web/router.ex ==` is showing up. That is printed to stderr and we are not meant to be capturing it.

**Comment by Gazler** [comment]
The first error is coming from the page itself, and the second error is coming from the live_reload frame. You can verify this by going to http://localhost:4000/phoenix/live_reload/frame

I think this is specific to router errors since both pages hit the endpoint which tries to compile the router.
