### ISSUE TITLE
Phoenix fails to properly initialize tailwind v3.2.7 under SmartOS

### ISSUE THREAD

**Issue by brianewell** [phoenixframework/phoenix#5501]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.6 (Hex package) (mix)
* Operating system: SmartOS instance image v22.4.0

### Actual behavior

```
$ mix phx.new hello
...
Fetch and install dependencies? [Yn] Y
...
$ cd hello
$ vim config/dev.exs # edited for connectivity to db, and to listen to 0.0.0.0, since this is a dev container I'll need to access remotely.
$ mix ecto.create
...
$ mix phx.server```
[error] I'm so sorry but `file_system` does NOT support your current system {:unix, :sunos} for now.
[warning] Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.

[info] Running HelloWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:4000 (http)
[info] Access HelloWeb.Endpoint at http://localhost:4000
[watch] build finished, watching for changes...
```

Access the page from a browser on my desktop, and I get a giant iconed mess, followed by the following console message on the server:

```
[info] GET /
[debug] Processing with HelloWeb.PageController.home/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 165ms
[info] GET /assets/app.css
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /assets/app.css (HelloWeb.Router)
    (hello 0.1.0) lib/phoenix/router.ex:487: HelloWeb.Router.call/2
    (hello 0.1.0) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.plug_builder_call/2
    (hello 0.1.0) lib/plug/debugger.ex:136: HelloWeb.Endpoint."call (overridable 3)"/2
    (hello 0.1.0) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.call/2
    (phoenix 1.7.6) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.10.0) /home/test/hello/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.10.0) /home/test/hello/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.10.0) /home/test/hello/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

After some google-fu, it appears that tailwind isn't generating assets.css, attempted to manually trigger said generation was met with the following:

```
$ mix assets.setup
03:06:18.463 [debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.7/tailwindcss-linux-x64
$ mix assets.build
** (Mix) `mix tailwind default` exited with 140
```

With no clear indication of where to proceed from here.

### Expected behavior

An experience much more similar to what is presented in tutorials.

**Comment by chrismccord** [comment]
This looks specific to smartOS and the tailwind standalone-binary package. You might have luck checking over on the tailwind repo, but I don't think this is something we can take care of within phoenix. Thanks!

**Comment by cneira** [comment]
@brianewell  I found the following workaround in the elixir forum, the downside is that you need to install nodejs.

1. Install nodejs on the zone where your elixir app is.
    
2. Add a package.json file to the assets directory
    
```json
{     "name": "my_app",     
      "version": "1.0.0",
      "description": "",
      "main": "js/app.js", 
      "scripts":{
      "deploy": "NODE_ENV=production tailwindcss -o ../priv/static/assets/app.css"
      },
      "dependencies": {
             "@tailwindcss/forms": "^0.5.7",
               "tailwindcss": "^3.4.3" 
           } 
}
```
3. Run the “npm install” command from the ‘assets’ directory.
4. Run the “npm run deploy” command from the ‘assets’ directory.
