### ISSUE TITLE
Phoenix.Endpoint.SyncCodeReloadPlug issues CREATE TABLE even though repo is read-only

### ISSUE THREAD

**Issue by IwoHerka** [phoenixframework/phoenix#5569]
### Environment

* Elixir version (elixir -v):

```bash
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]
Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

* Phoenix version (mix deps):

```elixir
{:phoenix, "~> 1.7.2"},
{:phoenix_ecto, "~> 4.4"},
{:ecto_sql, "~> 3.10"},
{:myxql, ">= 0.6.0"},
 ```

* Operating system:

Windows/Ubuntu 22.04.2 LTS (WSL2)

### Actual behavior

When sending request to my controller, `Phoenix.Endpoint.SyncCodeReloadPlug` issues 
`CREATE TABLE IF NOT EXISTS schema_migrations` query which fails, because my database connection is read-only (my database user has no rights to issue `CREATE`).

My Ecto repo is configured as follows:

```elixir
use Ecto.Repo,
  otp_app: :foo
  adapter: Ecto.Adapters.MyXQL,
  read_only: true
```

Stacktrace:

```bash
[error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :foo, Foo.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

[error] #PID<0.1200.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1199.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /foo
** (exit) an exception was raised:
    ** (MyXQL.Error) (1142) CREATE command denied to user 'foo_api_ro'@'<ip>' for table 'schema_migrations'

    query: CREATE TABLE IF NOT EXISTS `schema_migrations` (`version` bigint, `inserted_at` datetime, PRIMARY KEY (`version`)) ENGINE = INNODB
        (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
        (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
        (ecto_sql 3.10.2) lib/ecto/migrator.ex:756: Ecto.Migrator.verbose_schema_migration/3
        (ecto_sql 3.10.2) lib/ecto/migrator.ex:564: Ecto.Migrator.lock_for_migrations/4
        (ecto_sql 3.10.2) lib/ecto/migrator.ex:486: Ecto.Migrator.migrations/3
        (phoenix_ecto 4.4.2) lib/phoenix_ecto/check_repo_status.ex:99: Phoenix.Ecto.CheckRepoStatus.migrations/3
        (phoenix_ecto 4.4.2) lib/phoenix_ecto/check_repo_status.ex:57: Phoenix.Ecto.CheckRepoStatus.check_pending_migrations!/2
        (phoenix_ecto 4.4.2) lib/phoenix_ecto/check_repo_status.ex:31: anonymous fn/3 in Phoenix.Ecto.CheckRepoStatus.call/2
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_ecto 4.4.2) lib/phoenix_ecto/check_repo_status.ex:30: Phoenix.Ecto.CheckRepoStatus.call/2
        (foo 0.1.0) lib/foo _web/endpoint.ex:1: FooWeb.Endpoint.plug_builder_call/2
        (foo 0.1.0) deps/plug/lib/plug/debugger.ex:136: FooWeb.Endpoint."call (overridable 3)"/2
        (foo 0.1.0) lib/foo _web/endpoint.ex:1: FooWeb.Endpoint.call/2
        (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /home/poly/P/foo -api/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /home/poly/P/foo -api/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /home/poly/P/foo -api/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```
      
### Expected behavior

I would expect for Phoenix to respect `read_only: true` on my repository and check if `schema_migrations` table exist (in my case it does exist) without issuing `CREATE` statement. Ideally, it would work without `read_only: true`, to support read-only users on the database level.

**Comment by Gazler** [comment]
I'm not sure on the exact use case here, but if you are using the application with a read-only repository, it means that the Ecto.Repo functions which write to the database are not defined.

There is still an expectation that your applications have the correct tables, otherwise it won't function.

https://hexdocs.pm/ecto/Ecto.Repo.html#module-read-only-repositories

**Comment by ValedL** [comment]
I'm experiencing the same issue.
The use case for my application for instance is that I connect to a production DB for analytics purposes where only 1 table is exposed in read only mode.
