### ISSUE TITLE
The module Finch was given as a child to a supervisor but it does not exist

### ISSUE THREAD

**Issue by felipero** [phoenixframework/phoenix#5570]
### Environment

* Elixir version (elixir -v): 1.15.5
* Phoenix version (mix deps): 1.7.7
* Operating system: OSX Darwin - M1 chip

### Actual behavior
I create a brand new phoenix app with `mix phx.new` I generated the authentication with ` mix phx.gen.auth Accounts User users --hashing-lib argon2`. 

When I try to run the app with `mix phx.server` I get this error:
```
** (Mix) Could not start application steps: exited in: Steps.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Finch was given as a child to a supervisor but it does not exist
            (elixir 1.15.5) lib/supervisor.ex:764: Supervisor.init_child/1
            (elixir 1.15.5) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
            (elixir 1.15.5) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
            (elixir 1.15.5) lib/supervisor.ex:750: Supervisor.init/2
            (elixir 1.15.5) lib/supervisor.ex:669: Supervisor.start_link/2
            (kernel 9.0.2) application_master.erl:293: :application_master.start_it_old/4
```

`mix test` runs fine.

### Expected behavior
App should run normally.

**Comment by felipero** [comment]
Apparently my mistake. After starting fresh in the 3rd time it worked. Not sure what I did wrong.
