### ISSUE TITLE
mix test doesn't work in docker container running on apple silicon

### ISSUE THREAD

**Issue by cultofmetatron** [phoenixframework/phoenix#5614]
### Environment

* Elixir version (elixir -v): 1.14-otp-25
* Phoenix version (mix deps): 1.6.16
* Operating system: host: OSX 14.1, docker container: elixir:1.14-otp-25-alpine on apple silicon

### Actual behavior

I run docker conpose, here's teh docker file
```
FROM elixir:1.14-otp-25-alpine

### add these so that reloading works
RUN apk add inotify-tools

ENV APP_HOME /app

### Install rebar and hex
### Install OS packages for nodejs, npm, git etc.
RUN mix local.rebar --force
RUN mix local.hex --force
RUN mix archive.install --force hex phx_new 1.6.16
RUN apk add --no-cache --update nodejs npm bash openssl git make gcc g++
RUN mix local.rebar --force

WORKDIR ${APP_HOME}
#RUN mix deps.get

# Mount $APP_HOME directory as a volume
VOLUME  $APP_HOME

EXPOSE 4000 4001

CMD ["mix", "phx.server"]
```

then I run 
```
docker compose run -p 4000:4000 -p 4001:4001 app bash
```

now here's the strange part. I can book up the server, I can run migrations so the db is definitly running and the server is able to connect to it. 

however if I try to run tests, `MIX_ENV=test mix test` the system can't ocnnect

```

19:42:59.837 [error] Postgrex.Protocol (#PID<0.23393.0>) disconnected: ** (DBConnection.ConnectionError) #PID<0.96.0> checked in the connection owned by #PID<0.23493.0>

#PID<0.96.0> triggered the checkin at location:

    (elixir 1.14.5) lib/kernel/parallel_compiler.ex:517: Kernel.ParallelCompiler.wait_for_messages/7
    (elixir 1.14.5) lib/kernel/parallel_compiler.ex:204: Kernel.ParallelCompiler.spawn_workers/5
    (elixir 1.14.5) lib/kernel/parallel_compiler.ex:177: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.14.5) lib/mix/compilers/test.ex:98: Mix.Compilers.Test.require/3
    (mix 1.14.5) lib/mix/compilers/test.ex:60: Mix.Compilers.Test.require_and_run/4
    (mix 1.14.5) lib/mix/tasks/test.ex:546: Mix.Tasks.Test.do_run/3
    (mix 1.14.5) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.5) lib/mix/task.ex:475: Mix.Task.run_alias/6


Client #PID<0.23493.0> is still using a connection from owner at location:

    :prim_inet.recv0/3
    (postgrex 0.17.3) lib/postgrex/protocol.ex:3188: Postgrex.Protocol.msg_recv/4
    (postgrex 0.17.3) lib/postgrex/protocol.ex:2910: Postgrex.Protocol.recv_close/3
    (postgrex 0.17.3) lib/postgrex/protocol.ex:1472: Postgrex.Protocol.close_parse_describe_flush/3
    (db_connection 2.6.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.6.0) lib/db_connection.ex:1497: DBConnection.prepare/4
    (db_connection 2.6.0) lib/db_connection.ex:1490: DBConnection.run_prepare/4
    (db_connection 2.6.0) lib/db_connection.ex:1502: DBConnection.run_prepare_execute/5

The connection itself was checked out by #PID<0.23493.0> at location:

    (ecto_sql 3.10.2) lib/ecto/adapters/postgres/connection.ex:70: Ecto.Adapters.Postgres.Connection.prepare_execute/5


19:42:59.847 [error] Task #PID<0.23493.0> started from Blinq.Supervisor terminating
** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (blinq_api_server 0.1.1) lib/blinq_api_server/services/payment_sense/pat_connection_manager.ex:108: Blinq.PaymentSense.PatConnectionManager.mount_enabled_restaurants/0
    (blinq_api_server 0.1.1) lib/blinq_api_server/application.ex:117: anonymous fn/0 in Blinq.Application.start/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.90455320/0 in Blinq.Application.start/2>
    Args: []
19:42:59.864 [error] Task #PID<0.23537.0> started from Blinq.Supervisor terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.23537.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1044: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (blinq_api_server 0.1.1) lib/blinq_api_server/services/payment_sense/pat_connection_manager.ex:108: Blinq.PaymentSense.PatConnectionManager.mount_enabled_restaurants/0
    (blinq_api_server 0.1.1) lib/blinq_api_server/application.ex:117: anonymous fn/0 in Blinq.Application.start/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.90455320/0 in Blinq.Application.start/2>
    Args: []
19:42:59.865 [error] Task #PID<0.23538.0> started from Blinq.Supervisor terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.23538.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1044: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (blinq_api_server 0.1.1) lib/blinq_api_server/services/payment_sense/pat_connection_manager.ex:108: Blinq.PaymentSense.PatConnectionManager.mount_enabled_restaurants/0
    (blinq_api_server 0.1.1) lib/blinq_api_server/application.ex:117: anonymous fn/0 in Blinq.Application.start/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.90455320/0 in Blinq.Application.start/2>
    Args: []
19:42:59.865 [error] Task #PID<0.23539.0> started from Blinq.Supervisor terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.23539.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1044: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (blinq_api_server 0.1.1) lib/blinq_api_server/services/payment_sense/pat_connection_manager.ex:108: Blinq.PaymentSense.PatConnectionManager.mount_enabled_restaurants/0
    (blinq_api_server 0.1.1) lib/blinq_api_server/application.ex:117: anonymous fn/0 in Blinq.Application.start/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.90455320/0 in Blinq.Application.start/2>
    Args: []

```

since I can run migrations against teh test database when I run `mix ecto.migrate`, it can't be the environmental variables in test.exs. 

When I run this exact sequence on an intel mac or my popos linux machine, everythign just works

### Expected behavior

tests should run.

**Comment by josevalim** [comment]
This is most likely an emulation issue. You can read this comment for more information: https://github.com/livebook-dev/livebook/blob/main/Dockerfile#L16-L22

I would also try using something other than Alpine, just in case, as musl is often less tested than gcc.
