### ISSUE TITLE
`row_click` on CoreComponents `<.table>` component 

### ISSUE THREAD

**Issue by joladev** [phoenixframework/phoenix#5731]
### Environment

* Elixir version (elixir -v): 1.16.0
* Phoenix version (mix deps): 1.7.11
* Operating system: OSX 14.2.1

### Actual behavior

When adding a `row_click` attribute to the `<.table>` component that comes with the Phoenix generator it runs the function per column while mounting, erroring if the function returns something that isn't HTML safe.

Example to reproduce 

```
    <.table id="id" row_click={&IO.inspect/1} rows={[%{title: "why"}]}>
      <:col :let={row} label="title">
        <%= row.title %>
      </:col>
    </.table>
```

The terminal output

```
[info] GET /
[debug] Processing with SighWeb.PageController.home/2
  Parameters: %{}
  Pipelines: [:browser]
%{title: "why"}
[info] Sent 500 in 170ms
[error] GenServer #PID<0.1257.0> terminating
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %{title: "why"} of type Map. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
    (phoenix_html 4.0.0) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
    (phoenix_html 4.0.0) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
    (phoenix_html 4.0.0) lib/phoenix_html.ex:238: Phoenix.HTML.build_attrs/1
    (phoenix_html 4.0.0) lib/phoenix_html.ex:191: Phoenix.HTML.attributes_escape/1
    (sigh 0.1.0) lib/sigh_web/components/core_components.ex:493: anonymous fn/5 in SighWeb.CoreComponents."table (overridable 1)"/1
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (sigh 0.1.0) lib/sigh_web/components/core_components.ex:494: anonymous fn/3 in SighWeb.CoreComponents."table (overridable 1)"/1
    (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (sigh 0.1.0) lib/sigh_web/components/core_components.ex:476: anonymous fn/2 in SighWeb.CoreComponents."table (overridable 1)"/1
    (phoenix_live_view 0.20.9) lib/phoenix_live_view/engine.ex:150: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
    (phoenix_live_view 0.20.9) lib/phoenix_live_view/engine.ex:166: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
    (phoenix 1.7.11) lib/phoenix/controller.ex:1008: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
    (telemetry 1.2.1) /Users/johanna/workspace/sigh/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix 1.7.11) lib/phoenix/controller.ex:974: Phoenix.Controller.render_and_send/4
    (sigh 0.1.0) lib/sigh_web/controllers/page_controller.ex:1: SighWeb.PageController.action/2
    (sigh 0.1.0) lib/sigh_web/controllers/page_controller.ex:1: SighWeb.PageController.phoenix_controller_pipeline/2
    (phoenix 1.7.11) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (sigh 0.1.0) lib/sigh_web/endpoint.ex:1: SighWeb.Endpoint.plug_builder_call/2
    (sigh 0.1.0) deps/plug/lib/plug/debugger.ex:136: SighWeb.Endpoint."call (overridable 3)"/2
    (sigh 0.1.0) lib/sigh_web/endpoint.ex:1: SighWeb.Endpoint.call/2
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.78>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.3115368613.3204448258.69052>, start_time: -576459882106935076, start_metadata: %{remote_port: 64643, remote_address: {127, 0, 0, 1}, telemetry_span_context: #Reference<0.3115368613.3204448258.69052>, parent_telemetry_span_context: #Reference<0.3115368613.3204448262.63456>}}}, %{opts: %{websocket: [], http_1: [], http_2: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {SighWeb.Endpoint, []}}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true, websocket_enabled: true}}
```

Fresh Phoenix project that shows the behavior (just start it with `mix phx.server` and go to localhost:4000) and add the above table HTML. Alternatively use the repo I set up:

https://github.com/joladev/table-row-click-bug

### Expected behavior

The `row_click` function runs when the row is clicked, and never while rendering the page.

**Comment by chrismccord** [comment]
The row_click is for a JS command (so a %JS{} struct) and run *on the client* when the row is clicked, so the JS command is the only supported value to be returned from the function, which is called when the row is rendered and placed into the DOM. In this case, the error is correct as it's trying to place the result of the IO.inspect call into the DOM.  If you think we should generate a better `doc:` for the row_click attribute, we'd gladly accept a PR. Thanks!
