### ISSUE TITLE
Socket.js option "sessionStorage" isn't optional. Opening a socket will fail if you don't define one.

### ISSUE THREAD

**Issue by lylejantzi3rd** [phoenixframework/phoenix#5825]
### Environment

* Elixir version (elixir -v): Node.js v20.12.2
* Phoenix version (mix deps): 1.7.11
* Operating system: Fedora 40

### Actual behavior

Opening a socket results in an immediate error. Downgrading to 1.7.10 or providing sessionStorage as an option fixes it. This probably just needs some null checking.

```javascript
import { Socket } from 'phoenix'
const socket = new Socket('wss://ladida.com/socket', params)
```

Results in the program terminating with the following error:

```
file:///home/username/code/ladida/node_modules/phoenix/priv/static/phoenix.mjs:1003
    this.sessionStore = opts.sessionStorage || global.sessionStorage;
                                                      ^
TypeError: Cannot read properties of undefined (reading 'sessionStorage')
    at new Socket (file:///home/username/code/ladida/node_modules/phoenix/priv/static/phoenix.mjs:1003:55)
    at file:///home/username/code/ladida/index.js:71:16
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
```

### Expected behavior

Socket opens as expected

**Comment by lylejantzi3rd** [comment]
Thanks!
