### ISSUE TITLE
Module Collectable is unavailable

### ISSUE THREAD

**Issue by gmalkas** [phoenixframework/phoenix#635]
Hi,

I'm trying to get my release to run with Phoenix 0.9.0 but I encounter the following error when running `./bin/my_app foreground`:

```bash
13:19:34.290 [info] Application phoenix exited: exited in: Phoenix.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: Collectable.into/1 (module Collectable is not available)
            (elixir) Collectable.into(%{})
            (elixir) lib/enum.ex:907: Enum.into/3
            (phoenix) lib/phoenix/template.ex:170: Phoenix.Template.compiled_format_encoders/0
            (phoenix) lib/phoenix/template.ex:158: Phoenix.Template.format_encoder/1
            (phoenix) lib/phoenix.ex:13: Phoenix.start/2
            (kernel) application_master.erl:272: :application_master.start_it_old/4
{"Kernel pid terminated",application_controller,"{application_start_failure,phoenix,{bad_return,{{'Elixir.Phoenix',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Collectable',into,[#{}],[]},{'Elixir.Enum',into,3,[{fi
le,\"lib/enum.ex\"},{line,907}]},{'Elixir.Phoenix.Template',compiled_format_encoders,0,[{file,\"lib/phoenix/template.ex\"},{line,170}]},{'Elixir.Phoenix.Template',format_encoder,1,[{file,\"lib/phoenix/template.ex\
"},{line,158}]},{'Elixir.Phoenix',start,2,[{file,\"lib/phoenix.ex\"},{line,13}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}
```

It seems to work with latest Phoenix from master.

Any idea? Let me know if you need more info regarding my dependencies/environment.

Thanks!

**Comment by josevalim** [comment]
It has been fixed in master indeed. It was a bug when doing releases.

**Comment by gmalkas** [comment]
Awesome! Will wait for 0.9.1 then. Thanks.
