### ISSUE TITLE
Deprecation warnings with Plug 0.11.2 and Phoenix 10.0

### ISSUE THREAD

**Issue by DevL** [phoenixframework/phoenix#745]
Plug 0.11.2 deprecates `Plug.Builder.compile/1` and `Plug.Builder.compile/2` in favour of `Plug.Builder.compile/3`.

```
warning: Plug.Builder.compile/1 and compile/2 is deprecated, please use compile/3 instead
    (phoenix) lib/phoenix/router.ex:265: Phoenix.Router.plug/0
    (phoenix) lib/phoenix/router.ex:185: Phoenix.Router."MACRO-__using__"/2
    (elixir) src/elixir_dispatch.erl:187: :elixir_dispatch.expand_macro_fun/6
    (elixir) src/elixir_dispatch.erl:171: :elixir_dispatch.expand_require/5
```

**Comment by DevL** [comment]
This is already fixed in master.
