### ISSUE TITLE
dependency error on fresh app

### ISSUE THREAD

**Issue by skyeagle** [phoenixframework/phoenix#834]
I have just created fresh app with phoenix 0.12.0 and I got dependency error on `brunch`:

```
[info] Running App.Endpoint with Cowboy on port 4000 (http)

module.js:340
    throw err;
          ^
Error: Cannot find module '.../node_modules/brunch/bin/brunch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

```
nodejs --version
v0.10.38
```

**Comment by josevalim** [comment]
Thanks for the report. Can you copy the contents of your `config/dev.exs` file please? Other than that, I would try updating node (I am running on 0.12.x fwiw).

**Comment by skyeagle** [comment]
I've switched to node 0.12.2 and recreated the app. It doesn't make sense, I have the same error.

config/dev.exs
```
use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :test_app, TestApp.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  cache_static_lookup: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch"]]

# Watch static and templates for browser reloading.
config :test_app, TestApp.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif)$},
      ~r{web/views/.*(ex)$},
      ~r{web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Configure your database
config :test_app, TestApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "test_app_dev"
```

```
nodejs --version
v0.12.2
``

**Comment by josevalim** [comment]
Sorry, I have no idea what is happening then. :( It is very weird the path it is looking up contains 3 dots:

    Cannot find module '.../node_modules/brunch/bin/brunch'

it is supposed to be only:

    Cannot find module 'node_modules/brunch/bin/brunch'

What happens if you do `npm install` and try again?

**Comment by josevalim** [comment]
Ok I have one last idea. In your `config/config.exs` you have this:

```elixir
root: Path.expand("..", __DIR__),
```

If you replace it by:

```elixir
root: Path.dirname(__DIR__),
```

Does it fix the error?

**Comment by skyeagle** [comment]
Dots are appeared here because I replaced my full path with them.

Running `sudo npm install` helped me! 

You are extremely helpfull! Thanks a lot!
