### ISSUE TITLE
New project gives compile error

### ISSUE THREAD

**Issue by ahmetabdi** [phoenixframework/phoenix#877]
```
$ mix phoenix.new test
$ cd test
$ mix phoenix.server
```

```
== Compilation error on file web/views/page_view.ex ==
** (CompileError) web/views/page_view.ex:2: module Phoenix.HTML is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    web/views/page_view.ex:2: Test.PageView (module)
    expanding macro: Test.Web.__using__/1
    web/views/page_view.ex:2: Test.PageView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/page_view.ex:2: Test.PageView (module)


== Compilation error on file web/views/layout_view.ex ==
** (CompileError) web/views/layout_view.ex:2: module Phoenix.HTML is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    web/views/layout_view.ex:2: Test.LayoutView (module)
    expanding macro: Test.Web.__using__/1
    web/views/layout_view.ex:2: Test.LayoutView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/layout_view.ex:2: Test.LayoutView (module)


== Compilation error on file web/views/error_view.ex ==
** (CompileError) web/views/error_view.ex:2: module Phoenix.HTML is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    web/views/error_view.ex:2: Test.ErrorView (module)
    expanding macro: Test.Web.__using__/1
    web/views/error_view.ex:2: Test.ErrorView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/error_view.ex:2: Test.ErrorView (module)
```

**Comment by josevalim** [comment]
Which Phoenix version?

    mix phoenix.new --version

**Comment by ahmetabdi** [comment]
Phoenix v0.12.0

**Comment by josevalim** [comment]
Ah, please install latest. This has been fixed!

More info here: http://www.phoenixframework.org/v0.13.0/docs/up-and-running

Thank you!
