### ISSUE TITLE
Mixed up template assigns in test environment?

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix#907]
I'm getting the following error when running a controller test I have:

```console
test/controllers/property_controller_test.exs:63
     ** (KeyError) key :id not found in: %Ecto.Changeset{changes: %{}, errors: [size: "can't be blank"], filters: %{}, model: %Manang.Property{__meta__: %Ecto.Schema.Metadata{source: "properties", state: :loaded}, address: nil, id: 236, inserted_at: %Ecto.DateTime{day: 21, hour: 13, min: 39, month: 5, sec: 8, usec: 0, year: 2015}, size: nil, updated_at: %Ecto.DateTime{day: 21, hour: 13, min: 39, month: 5, sec: 8, usec: 0, year: 2015}, user: %Manang.User{__meta__: %Ecto.Schema.Metadata{source: "users", state: :loaded}, email: nil, id: 247, inserted_at: %Ecto.DateTime{day: 21, hour: 13, min: 39, month: 5, sec: 8, usec: 0, year: 2015}, name: nil, password: nil, properties: #Ecto.Association.NotLoaded<association :properties is not loaded>, role: nil, updated_at: %Ecto.DateTime{day: 21, hour: 13, min: 39, month: 5, sec: 8, usec: 0, year: 2015}}, user_id: 247}, optional: [], params: %{"user_id" => "247"}, repo: nil, required: [:size, :user_id], valid?: false, validations: []}
     stacktrace:
       (manang) web/templates/property/edit.html.eex:36: Manang.PropertyView."edit.html"/1
       (phoenix) lib/phoenix/view.ex:197: Phoenix.View.render_within/3
       (phoenix) lib/phoenix/view.ex:429: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:533: Phoenix.Controller.do_render/4
       (manang) web/controllers/property_controller.ex:1: Manang.PropertyController.phoenix_controller_pipeline/2
       (manang) lib/phoenix/router.ex:297: Manang.Router.dispatch/2
       (manang) lib/phoenix/router.ex:2: Manang.Router.call/2
       (manang) lib/manang/endpoint.ex:1: Manang.Endpoint.phoenix_endpoint_pipeline/1
```

It points to a line that has this code `<%= render "form.html", changeset: @changeset, conn: @conn,
            action: property_path(@conn, :update, @property.id) %>`. I was wondering why I was getting a `to_param/1` error for `nil` and tried calling `id` on `@property` and that's the error I get when running the test.

What's weird is that `@property` shouldn't be a `Changeset`. It should be a `Property` model. Below is the edit action in the `PropertyController`:

```elixir
 def edit(conn, %{"id" => id}) do
    property = Repo.get(Property, id)
    changeset = Property.changeset(property)
    render(conn, "edit.html", property: property, changeset: changeset)
 end
```

This works fine in development, but in test it keeps failing because of the above behavior. Below is the test I have for it:

```elixir
  test "does not update chosen resource and renders errors when data is invalid",
      %{conn: conn, user: user} do
    property = Repo.insert %Property{user_id: user.id}
    params = [id: property.id, property: %{}, address: %{}]
    conn = put conn, property_path(conn, :update, property), params
    assert html_response(conn, 200) =~ "Edit property"
  end
```

Is there anything I'm doing wrong or are the assigns for the template getting messed up in the test environment?

**Comment by josevalim** [comment]
Thanks! Everything seems correct... can you provide a test case or a repo where we can try this out?

**Comment by gjaldon** [comment]
@josevalim just added you as collaborator to the project I'm working on. If you run `mix test` from there, the single failing test will point you to the problem.

**Comment by josevalim** [comment]
The issue is in the controller. This line in the `update` action to be more specific:

    changeset = {property, address} = changeset(conn, params, property)

It is replacing the variable `property` by a changeset. That's why you have a changeset down below.

**Comment by gjaldon** [comment]
Thank you for the time and sorry for the trouble!

**Comment by josevalim** [comment]
No problems!
